### ISSUE TITLE
bug in opening 3D matrix

### ISSUE THREAD

**Issue by sambreak** [spyder-ide/spyder#10628]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/Users/zenko/Documents/OPT/anaconda3/lib/python3.6/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 449, in createEditor
    if not editor.setup_and_check(value, title=key, readonly=readonly):
  File "/Users/zenko/Documents/OPT/anaconda3/lib/python3.6/site-packages/spyder/widgets/variableexplorer/arrayeditor.py", line 619, in setup_and_check
    self.data.flags.writeable = True
ValueError: cannot set WRITEABLE flag to True of this array

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.25.0 (OK)
numpy >=1.7      :  1.16.4 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.3 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment]
This is fixed in our latest version. Please update by opening Terminal.app and running there

    conda install spyder=3.3.6

**Comment by sambreak** [comment]
I still have the same problem, despite the fact that I updated the version.
Do you need more information? or the message error that pops up?

best,
VZ

Le mer. 6 nov. 2019 à 19:25, Carlos Cordoba <notifications@github.com> a
écrit :

**Comment by ccordoba12** [comment]
That's not possible. Please verify that Spyder is at version 3.3.6 or install it in a different environment if necessary.

**Comment by sambreak** [comment]
I am a beginner with Python and programming in general. So, when I install
the 3.3.6 version in the terminal, the last step shows

Proceed ([y]/n)?.... What am I supposed to do here? and how do I know in
which environment is the new version installed?

Le jeu. 7 nov. 2019 à 17:34, Carlos Cordoba <notifications@github.com> a
écrit :

**Comment by sambreak** [comment]
Hello,

it's all good, I fixed the problem.

Many thanks for the help.

Best regards,

VZ

Le jeu. 7 nov. 2019 à 21:02, vjollca zenko <vjollca.zenko@gmail.com> a
écrit :
