### ISSUE TITLE
Spyder hangs on qthelpers.py (line 93: app = SpyderApplication(['Spyder']))

### ISSUE THREAD

**Issue by tokorhon** [spyder-ide/spyder#11407]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Spyder hangs on module qthelpers.py at line 93. 
`app = SpyderApplication(['Spyder'])`

I have tried with Anaconda, WinPython, install by pip and source code from GitHub. They all have the same problem. When running the GitHub version under PyCharm debugger I managed to find the line where it happens.

### What steps reproduce the problem?

1.  git clone https://github.com/spyder-ide/spyder.git
2.  python bootstrap.py under PyCharm debugger
3.  set breakpoint at line 93 on file qthelpers.py

### What is the expected output? What do you see instead?

Output from PyCharm debugger:

C:\Python\Python38\python.exe C:/Python/spyder/bootstrap.py
Executing Spyder from source checkout
Revision 21f75f873, Branch: master
01. Patched sys.path with C:\Python\spyder
02. PyQt5 is detected, selecting
03. Imported Spyder 5.0.0.dev0
    [Python 3.8.0 64bits, Qt 5.12.6, PyQt5 5.12.3 on Windows]
04. Running Spyder
Bootstrap completed in 00:00:11.1269

Process finished with exit code -1073741819 (0xC0000005)

After that an error dialog from Windows "Python has stopped working" appears.

## Versions

* Spyder version: 5.0.0.dev0 (same problem with version 4.0.1 and 3.3.6) 
* Python version: 3.8.0 (also tried 3.7.5)
* Qt version: 5.12.6
* PyQt version: 5.12.3
* Operating System name/version: Windows 7

**Comment by ccordoba12** [comment]
This probably happens because another Qt5 installation that it's interfering with Anaconda and WinPython.

Please search for this pattern `Qt5*.dll` and uninstall/remove those files if they are placed outside Anaconda or WinPython.

**Comment by tokorhon** [comment]
Thanks for your reply. There are several Qt5*.dlls outside Anaconda and WinPython (like pgAdmin4, RStudio, FireShark) but none of those are in path. I also checked that there are no Qt5*.dlls loaded in memory using [ListDLLs](https://docs.microsoft.com/en-us/sysinternals/downloads/listdlls) utility.
 
Problem details in Windows error dialog is

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	python.exe
  Application Version:	3.8.150.1013
  Application Timestamp:	5da4ced9
  Fault Module Name:	**ig9icd64.dll**
  Fault Module Version:	21.20.16.4550
  Fault Module Timestamp:	582615c8
  Exception Code:	c0000005
  Exception Offset:	00000000005d0100
  OS Version:	6.1.7601.2.1.0.256.4
  Locale ID:	1035
  Additional Information 1:	94c6
  Additional Information 2:	94c6af18acce34d7b05c0a84e6ef48b7
  Additional Information 3:	a3c2
  Additional Information 4:	a3c28d8bbc546659fff99773f7c36c33

Module ig9icd64.dll is part of Intel's HD Graphics 520 driver version 21.20.16.4550.

**Comment by ccordoba12** [comment]
Ok, that's progress. So there's an incompatibility with your graphics card driver.

Please open a system prompt (cmd.exe), run there

    spyder --reset

and try again. That should fix the problem.

**Comment by tokorhon** [comment]
Unfortunately --reset did not fix the problem. Running spyder --reset produces the same Windows error dialog "Python has stopped working" with following information

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	pythonw.exe
  Application Version:	3.8.150.1013
  Application Timestamp:	5da4ceda
  Fault Module Name:	ig9icd64.dll
  Fault Module Version:	21.20.16.4550
  Fault Module Timestamp:	582615c8
  Exception Code:	c0000005
  Exception Offset:	00000000005d0100
  OS Version:	6.1.7601.2.1.0.256.4
  Locale ID:	1035
  Additional Information 1:	be4f
  Additional Information 2:	be4fa62bb5a24687256bb9f232cf9bbe
  Additional Information 3:	7c26
  Additional Information 4:	7c26a11002e94e82fe3d455aafe23326

There must be something special how Spyder uses Qt5 since all other Qt5 applications I use work fine.

**Comment by ccordoba12** [comment]
I don't think so. This looks most probably related to an incompatibility between the Qt version you're using and the Intel driver version you have installed.

See

https://bugreports.qt.io/browse/QTBUG-71976
https://bugreports.qt.io/browse/QTBUG-66915

Since the first bug is closed, it seems this problem is fixed in Qt 5.12. However, we're not setting the right OpenGL implementation used by Qt in that version (see #11227).

Therefore, I'm closing this one as a duplicate of #11227. We're planning to fix that problem in our next version. In the meantime, there's nothing you can do about it, sorry.
