### ISSUE TITLE
LSP cycling : restarting ... ready ... restarting ...

### ISSUE THREAD

**Issue by Ticonderoga** [spyder-ide/spyder#12225]
### Issue Report Checklist

* [x ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I use latest version (last commit e3326bd531d16ff3551855a56882f8df129f5dfc) with conda and for some reason the LSP is not working and I have a notification on the bottom bar LSP python restarting and then ready and it cycles for ever

### What steps reproduce the problem?

1. Just launch spyder via python bootstrap.py

### What is the expected output? What do you see instead?
LSP working normally. Linting and completion and everything related to LSP is not working but everything else seems OK !!

### Paste Traceback/Error Below (if applicable)

see the spyder-debug.log

[spyder-debug.log](https://github.com/spyder-ide/spyder/files/4450984/spyder-debug.log)

## Versions

* Spyder version: 5.0.0.dev0 - Revision e3326bd53
* Python version: Python 3.7.6 64bits
* Qt version: 5.12.5
* PyQt version: 5.12.3 on [Linux]
* Operating System name/version: Archlinux with conda

### Dependencies

[conda_list.log](https://github.com/spyder-ide/spyder/files/4451002/conda_list.log)

**Comment by ccordoba12** [comment]
Please upload or send us privately these files:

    /home/phil/Cours/Python L2/GitHub_Info_L2/JeuHanoi.py
    /home/phil/Papers/Annales_SFT_2020/Recueil.py

so we can understand what's happening in your case.

**Comment by ccordoba12** [comment]
@UniqASL, another way you can help us is by opening a terminal and starting Spyder with this command:

    spyder --debug-info verbose --debug-output file

After doing that, a file called `spyder-debug.log` will be generated in the same directory where you ran that command. Please upload it here.

And before closing Spyder, please also go to the the menu `Tools > LSP logs` (which is only shown in debug mode):

![Selección_002](https://user-images.githubusercontent.com/365293/78836131-16664a80-79b7-11ea-80d7-4f93c77cc6df.png)

click on the two entries shown on it to open those files in the editor, and upload their contents here too.

Thanks!

**Comment by Ticonderoga** [comment]
Thanks for the reply,

The bug is not related with my py files because it could be reproduced with no files in the history or previously loaded. I think I have already provided a log file in the first post. Have a look at 

https://github.com/spyder-ide/spyder/files/4450984/spyder-debug.log

and 

https://github.com/spyder-ide/spyder/files/4451002/conda_list.log

**Comment by Ticonderoga** [comment]
I have done as you mentionned and here are the LSP_log :
[client_python.log](https://github.com/spyder-ide/spyder/files/4454720/client_python.log)
[client_python_19948.log](https://github.com/spyder-ide/spyder/files/4454721/client_python_19948.log)
[server_python.log](https://github.com/spyder-ide/spyder/files/4454722/server_python.log)
[server_python_19948.log](https://github.com/spyder-ide/spyder/files/4454723/server_python_19948.log)

and for reason it's looking for my main python install for pyls but not in myenv (conda install). Moreover I thought it was not necessary to install pyls from conda because it's already included in the spyder repo. Any clue ?

**Comment by Ticonderoga** [comment]
I finally found the solution ... I think it's a misunderstanding between conda/requirements.txt and the installation via the github sources. So to be clear you have to install python-language-server from conda if you want to use 

`python bootstrap.py`

Thanks for everything. I really hope that Spyder will switch to a newer version of pyqt and then be able to use spyder with the python installed by default in my Archlinux. I'm not a huge fan of conda ...

I really love the spyder-IDE it's my every day IDE for python. Great work !!

**Comment by ccordoba12** [comment]
> So to be clear you have to install python-language-server from conda if you want to use
> 
> python bootstrap.py

Sure you do. Glad you found the solution!

**Comment by goanpeca** [comment]
>So to be clear you have to install python-language-server from conda if you want to use

Should not this work also with pip @ccordoba12 ?

**Comment by ccordoba12** [comment]
Sure, but it looks like @Ticonderoga was mixing system and conda deps.

**Comment by EkaterinaAbramova** [comment]
Hello, :)

My Spyder Script hangs and becomes really slow for about 15 seconds, several times a day. I noticed that at the bottom of the script during those slow times it says LSP Restarting. This last for a short while and then the Spyder speeds back up again to normal typing speed and the LSP says 'ready'. I have not noticed this on any other release, what is happening please?

On a separate issue it gives me notifications for errors (red cross at the start of a line) where there is no error. If I restart Spyder then the red cross disappears (since as mentioned there is no error).

Please could you address both of the above issues?

**Comment by ccordoba12** [comment]
> My Spyder Script hangs and becomes really slow for about 15 seconds, several times a day. I noticed that at the bottom of the script during those slow times it says LSP Restarting. This lasts for a short while and then the Spyder speeds back up again to normal typing speed and the LSP says 'ready'. I have not noticed this on any other release, what is happening please?

We still don't know why that happens, sorry. It seems to arise after some period of time and in a random way. That's why it's been so hard for us to track.

> On a separate issue Spyder gives me notifications for errors (red cross at the start of a line) where there is no error. If I restart Spyder then the red cross disappears (since as mentioned there is no error).

Some of those errors should be fixed in our next version (4.1.3), to be released next week. If they keep appearing for you, please open a new issue about them with a clear way to reproduce them.

**Comment by EkaterinaAbramova** [comment]
Thank you very much. 

My Spyder keeps hanging for more than 3 minutes and needs fully closing & re-opening because of the LSP Restarting issue. I have lost quite a bit of unsaved work, since even though I do get autosave pop up window (image attached) asking 'what would you like to do', unfortunately there is no other option but to use the one and only 'cancel' button. Is it normal that I can't open an autosaved file? If not how do I do it please / why is only the cancel button available? 

Have a lovely day and thank you,

<img width="673" alt="Screenshot 2020-05-03 at 14 38 56" src="https://user-images.githubusercontent.com/1406362/81006148-edff2e00-8e46-11ea-9ecd-7625afbd9bfb.png">

**Comment by jitseniesen** [comment]
In your picture, you should be able to scroll to the right and see more buttons. Strangely enough, there is no horizontal scroll bar, is that something specific to Mac? I haven't used one in ages. In case Spyder will crash again in the future, I think the autosave files are stored in the folder `~/.spyder/autosave` on a Mac, and you can copy them yourself if you want.

**Comment by EkaterinaAbramova** [comment]
I was not able to scroll or use any buttons but the cancel one (as a matter of fact you can see I did not have any other columns than the one given), and no Restore button available. 

I believe this issue has now been resolved by the developers just now since for the first time (and I have had to do many re-starts due to this LSP Restarting issue), when I re-opened Spyder following another crash, 15 min after posting my original post, miraculously I now see the buttons :). 

Thank you to whoever sorted this out, much appreciated. 

<img width="668" alt="Screenshot 2020-05-04 at 20 58 07" src="https://user-images.githubusercontent.com/1406362/81012999-60c1d680-8e52-11ea-9325-22c614e5173c.png">

**Comment by singhalarchit** [comment]
I am facing similar issues with Spyder. I am running latest version. Spyder freezes with LSP Python: restarting and I have to force quit the app which causes me to lose my unsaved changes and session variables. I am really getting frustrated as it happens almost every day.

**Comment by redhairedcelt** [comment]
Hey all, I'm still having a similar issue to what singhalarchit describes. Unlike Ticonderoga who opened this issue, I'm using the Conda installed version and do not have a mix of system and conda dependencies.

**Comment by NinaMathiasen** [comment]
> I am facing similar issues with Spyder. I am running latest version. Spyder freezes with LSP Python: restarting and I have to force quit the app which causes me to lose my unsaved changes and session variables. I am really getting frustrated as it happens almost every day.

I also have this problem.

**Comment by jyauri** [comment]
I am having this  issue too. Spyder LSP icon in the status bar is restarting many times while coding and when it happens, the editor freeze and next go to definition, linting and autocomplete stop. However, clicking on this restarting LSP button, Spyder works normally, but after some minutes this happens again.

I only have the latest Spyder 4.1.3 installed with Anaconda in Win10.

**Comment by golanguage** [comment]
For spyder4 & spyder 5 alpha4, I have same issue. 
so as above advise, I run "spyder --debug-info verbose --debug-output file", and show a pop diag window, I choose show more, it say 

-File "c:\users\liong\appdata\local\programs\python\python37\lib\site-packages\pyls_jsonrpc\endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "c:\users\liong\appdata\local\programs\python\python37\lib\site-packages\pyls_jsonrpc\endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "c:\users\liong\appdata\local\programs\python\python37\lib\site-packages\pyls_jsonrpc\dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "c:\users\liong\appdata\local\programs\python\python37\lib\site-packages\pyls\python_ls.py", line 209, in m_initialize
    processId, _kwargs.get('capabilities', {}))
  File "c:\users\liong\appdata\local\programs\python\python37\lib\site-packages\pyls\config\config.py", line 53, in __init__
    entry_point.load()
  File "c:\users\liong\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 2446, in load
    self.require(*args, **kwargs)
  File "c:\users\liong\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 2469, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "c:\users\liong\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 770, in resolve
    raise DistributionNotFound(req, requirers)

pkg_resources.DistributionNotFound: The 'typed-ast>=1.4.0' distribution was not found and is required by black. _

I forcefully upgrade/reinstall typed-ast to 1.4.2, LSP is ready now.

**Comment by kkasra12** [comment]
Hey all, I still have the same problem using spyder5.0.3.
I installed using conda:
```
conda install spyder
```
Also, code completion is not working in the editor.
My configuration is:
```
Python 3.8.5 64-bit | Qt 5.12.10 | PyQt5 5.12.3 | Linux 5.4.0-52-generic 
```
here are the outputs for the `spyder --debug-info verbose --debug-output file` command:
[spyder-debug.log](https://github.com/spyder-ide/spyder/files/6566246/spyder-debug.log)
[server_python_83879.log](https://github.com/spyder-ide/spyder/files/6566247/server_python_83879.log)
[transport_python_83879.log](https://github.com/spyder-ide/spyder/files/6566248/transport_python_83879.log)

and this is output for the `conda list` command
[condalist.log](https://github.com/spyder-ide/spyder/files/6566250/condalist.log)

note that I have tried `spyder --reset`, but no result
