### ISSUE TITLE
The right scroll bar is missing in Spyder 4 on MacOS 10.15

### ISSUE THREAD

**Issue by aosavas** [spyder-ide/spyder#12637]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
The scroll bar on the right hand side that shows overview of issues, highlighted items, etc... is missing in Spyder 4.1.2 and 4.x.x releases on MacOS 10.15.4

### What steps reproduce the problem?

1. I have tried to use "spyder --reset" no luck 
2. I have downgraded to 3.3.6 and it works

![image](https://user-images.githubusercontent.com/46607096/81224565-ea3de980-8fb5-11ea-8d82-d3353366d577.png)

3. I have upgraded to 4.0.0, missing.

![image](https://user-images.githubusercontent.com/46607096/81224763-3852ed00-8fb6-11ea-873e-a65587fbc2de.png)

### What is the expected output? What do you see instead?
I am not seeing the scroll bar that I am used to on 3.x versions. Talked to @bcolsen and he suggested that I should open a bug at github.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
spyder                    4.1.2                    py37_0  
spyder-kernels            1.9.0                    py37_0  
* Python version: 
python                    3.7.3                h359304d_0  
python-chromedriver-binary 83.0.4103.14.0   py37hc8dfbb8_0    conda-forge
python-dateutil           2.8.1                      py_0  
python-jsonrpc-server     0.3.4                      py_0  
python-language-server    0.31.10                  py37_0  
python-libarchive-c       2.9                        py_0  
python.app                2                        py37_9  
python_abi                3.7                     1_cp37m    conda-forge
* Qt version: 
qt                        5.9.7                h468cd18_1  
qtawesome                 0.7.0                      py_0  
qtconsole                 4.7.3                      py_0  
qtpy                      1.9.0                      py_0  
qt                        5.9.7                h468cd18_1  
qtawesome                 0.7.0                      py_0  
qtconsole                 4.7.3                      py_0  
qtpy                      1.9.0                      py_0  
* PyQt version: 
pyqt                      5.9.2            py37h655552a_2  
* Operating System name/version: 
MacOS 10.15.4

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7      :  0.2.1 (OK)
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.4.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.5.0 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.3 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.0.3 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  None (OK)
numpy >=1.7                    :  None (OK)
pandas >=0.13.1                :  None (OK)
scipy >=0.17.0                 :  None (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by goanpeca** [comment]
@aosavas you mean the scrollbar that shows lint information or the normal scrollbar to move up and down?

**Comment by bcolsen** [comment]
It's the scroll flags area. It was a bit more obvious in the gitter chat images

**Comment by aosavas** [comment]
Yeah, the secondary scroll bar that shows the errors or highlighted items
on the right...

The regular scroll bar to go up and down is there.

**Comment by aosavas** [comment]
@goanpeca hi Gonzalo, I was wondering if you have any update on this issue?

**Comment by ccordoba12** [comment]
@impact27, have you observed this in the latest macOS?

**Comment by impact27** [comment]
I have it with masOS 10.15.4
![SCROLL](https://user-images.githubusercontent.com/6740194/82036145-d0309500-96a0-11ea-9c35-b12add039bdf.png)

**Comment by aosavas** [comment]
The interesting is, it works on 3.6 with the same MacOS.

**Comment by goanpeca** [comment]
Hi @aosavas

I have not been managed to reproduce this, but I use 36 as my default dev env. Will try with 3.7 and 3.8.

Thanks for the information.

**Comment by jnsebgosselin** [comment]
It seems like something is wrong in @impact screenshot. The default scrollbar and scrollflag bar are not supposed to overlap like that, or are they?

**Comment by goanpeca** [comment]
>It seems like something is wrong in @impact screenshot. The default scrollbar and scrollflag bar are not supposed to overlap like that, or are they?

Good point @jnsebgosselin , they should not overlap!

**Comment by impact27** [comment]
Why not? This is a nice way to save some space!

**Comment by impact27** [comment]
> > It seems like something is wrong in @impact screenshot. The default scrollbar and scrollflag bar are not supposed to overlap like that, or are they?
> 
> Good point @jnsebgosselin , they should not overlap!

Are you sure? in mac, the scroll bar is supposed to be small and disappear when not in use. 

https://developer.apple.com/design/human-interface-guidelines/macos/windows-and-views/scroll-views/

> By default, scroll bars are transient and only appear during user interaction.

**Comment by aosavas** [comment]
Yeah pretty sure, if you want we can do a quick zoom and show you in first
hand...

Just upgraded to 4.1.3 and the issue still there... You can see that I am
highlighting "browser" in 4.1.3, and nothing on the right scroll bar. If I
scroll up and down, nothing changes on the scroll bar. It is always there.
[image: image.png]

Same file, same action in 3.3.6 shows as below. You can see all the
highlighted items. If I scroll up and down, I see the secondary scroll as
well with the highlights... I guess what is showing below moves to the left
and the real page scroll shows up as well in 3.3.6.

So it seems like the main scroll bar is hidden in 3.3.6 but the scroll with
the function/feature I am missing is there by default and the main scroll
appears only when I scroll up and down on the right-hand side of the
default scroll (the feature that's not functioning in 4.1.3 for me at
least).
[image: image.png]

**Comment by goanpeca** [comment]
@aosavas answering by email will not upload images, you will need to come to the issue tracker :-)

**Comment by goanpeca** [comment]
Ok, so the issue is that they are overlapping. 

<img width="773" alt="Screen Shot 2020-05-15 at 12 39 21" src="https://user-images.githubusercontent.com/3627835/82079824-1e499680-96a9-11ea-9f16-acc36b35bcf2.png">

As soon as the normal scrollbar appears it completely blocks the other scroll flag.

**Comment by aosavas** [comment]
Would you like me to post the pictures at github?

**Comment by aosavas** [comment]
Not exactly... as in my view, the normal scroll bar is the default one and
always blocks it. Hence I can't see the other one at any given time...

**Comment by goanpeca** [comment]
On my mac if mi file is longer than the screen view, the scrollbar will appear and block it, it seems

**Comment by goanpeca** [comment]
>Would you like me to post the pictures at github?

Please do :-) !

**Comment by aosavas** [comment]
4.1.3 image
![image](https://user-images.githubusercontent.com/46607096/82086468-8ce41f80-96bc-11ea-8920-1642bf776ee3.png)

3.6.6 image
![image](https://user-images.githubusercontent.com/46607096/82086496-953c5a80-96bc-11ea-8858-0b41d7cd8d8e.png)

**Comment by goanpeca** [comment]
@aosavas could you open a new file with just this content?
```python
d = {}
d.
```

You should be able to see the scrollbar (since the nomrmal one should be hidden?)

**Comment by aosavas** [comment]
@goanpeca Yep, that's it...

So how to make the regular scroll bar, optional like in 3.6.6?

![image](https://user-images.githubusercontent.com/46607096/82088200-552aa700-96bf-11ea-80d9-45fca98fdaa7.png)

**Comment by goanpeca** [comment]
I can go ahead and try to fix this ;-) will let you know

**Comment by aosavas** [comment]
Thank you !!! :)

**Comment by aosavas** [comment]
@goanpeca Hi, I was just wondering what would be the time frame for the fix. I really like 4.* but this is preventing me to stay in 3.3.6. Thanks for the great support!!!

**Comment by goanpeca** [comment]
Spyder 4.1.4 will be available in mid June, so that is when it will become available for install. If you want to run from source as soon as it is merged you could install from the 4.x branch

**Comment by aosavas** [comment]
@goanpeca Perfect!!! thanks...

**Comment by mrclary** [comment]
Was #12852 supposed to fix this issue? Because I still see it on MacOS 10.14.6. Note that the arrow selector of the class and method selector is also hidden behind the scroll bar in the upper right corner of the Editor.

<details><summary>Dependencies</summary>
<p>

# Mandatory:
applaunchservices >=0.1.7      :  0.2.1 (OK)
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.4.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.17.0                   :  0.17.0 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.5.2 (OK)
pyls >=0.33.0;<0.34.0          :  v4.1.3+175.g06edb40f0 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.4 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.0.3 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.10.0.dev0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.17 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
</p>
</details>

<img width="1792" alt="Screen Shot 2020-06-06 at 8 34 03 AM" src="https://user-images.githubusercontent.com/9618975/83948355-9c451d00-a7d1-11ea-8ce0-909267da819e.png">

**Comment by aosavas** [comment]
@goanpeca Hi, do you know when in June it will be available? Also based on the previous comment not sure if it is already fixed or not.

**Comment by goanpeca** [comment]
Not yet fixed. But will work on that for 4.1.4

>do you know when in June it will be available? 

End of June maybe 🤷 ?

**Comment by aosavas** [comment]
@ccordoba12 Hi, I assume this issue is fixed in 4.1.4 (upcoming release). May I please ask what is the ETA on that release?
