### ISSUE TITLE
Creation time be changed

### ISSUE THREAD

**Issue by senlin198** [spyder-ide/spyder#13276]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Hello Spyder developers,When I first save my python file Spyder can normally save my python file,But second save my python file it changed my creation time of python file.

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.1.3
* Python version: 3.7
* Qt version: 
* PyQt version: 
* Operating System name/version: Windows 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by goanpeca** [comment]
Hi @senlin198, thanks for your report. It seems that has already been fixed at https://github.com/spyder-ide/spyder/pull/11443.

Cheers!

----

@andfoy could you please check if this is a regression?

Thanks

**Comment by senlin198** [comment]
> Hi @senlin198, thanks for your report. It seems that has already been fixed at #11443.
> 
> Cheers!
> 
> @andfoy could you please check if this is a regression?
> 
> Thanks

Thanks! Cheers!

**Comment by ccordoba12** [comment]
@goanpeca, there's a test for this.

@senlin198, you need to provide us a reproducible use case to see in what circumstances this error is still happening.

**Comment by senlin198** [comment]
> @goanpeca, there's a test for this.
> 
> @senlin198, you need to provide us a reproducible use case to see in what circumstances this error is still happening.

I just saved my python file then it happening
