### ISSUE TITLE
launching correct version of spyder

### ISSUE THREAD

**Issue by Fizz04** [spyder-ide/spyder#13611]
Hi all-

I've been using Spyder for a couple years.  I start up Anaconda Navigator, then i change the environment to python 2.7, and then i launch spyder.  The title of the spyder window says "python 2.7".  And all was good for a long time.

However, i did an update recently, and now things aren't working as before.  Now when i try to launch Spyder, it always launches as Python 3.7.  Even when i put the environment to 2.7, it still comes up as Python 3.7.  I hadn't done anything to change my environments, and they seem to still be installed, but i can't for the life of me figure out how to get python 2.7 inside of Spyder.

Here are the steps:
1: start anaconda navigator
2: change environment to python 2.7 (the Applications on dialog)
3: Launch Spyder 3.3.3 (according to Navigator)

Expected behavior:  Spyder 3.3.3 window running Python 2.7.

Actual behavior:  Spyder 4.1.4 window running Python 3.7.

Versions:
Anaconda Navigator: 1.9.12
Spyder:  4.1.4  ?
OS:  Linux Mint 20 (based on Ubuntu 20).

It's as though Navigator isn't acknowledging that it's in the 2.7 environment anymore.  As mentioned, all was fine before i did a recent update (conda update anaconda-navigator).

Hope someone can help.  Thanks!

-Fizz

**Comment by steff456** [comment]
Hi @Fizz04,

Are you trying to launch Spyder 4.1.4 or Spyder 3.3.3 in a python 2.7 environment?
Please note that we removed support for Python 2.7 a couple of months ago and we recommend to migrate all your code to Python 3 as soon as you can.

**Comment by Fizz04** [comment]
Hi steff456-

When i am in Navigator, i set my environment to python 2.7.  I see the Spyder icon which says "Spyder 3.3.3".  But when i click on the launch button, it actually launches 4.1.4.

Unfortunately, the code i am using involves a third party, and modifying it to python 3 is not an option.  So I need to be able to run python 2.7.

How can i run under 2.7?

-Fizz

**Comment by steff456** [comment]
Hi @Fizz04,

In this issue https://github.com/spyder-ide/spyder/issues/13510 we explain how you can run Python 2.7 in Spyder 4.1.4
Please let me know if this works for you

**Comment by Fizz04** [comment]
Hi steff456

I will check out that link.  But isn't there an issue when Navigator says it's 3.3.3 but it actually launches 4.1.4?

Chris

**Comment by Fizz04** [comment]
Hi steff456

Issue #13510 says i have 3 options.  The first is:  
_Create a conda environment with Spyder 3.3.6, which is the stable version for Spyder 3 that supports Python 2._

But i should already have this.  I've been running a Python 2.7 environment for a couple years.  But this update seems to have messed that up.  It's like Anaconda won't "engage" the 2.7 environment anymore.  It says it is, but it always launches the default apps, rather than the environment-specific ones.

-FIzz

**Comment by steff456** [comment]
Can you please try to run spyder from the terminal using the following commands,

```
conda activate your-env-py-2
sypder
```

Please note that in that environment you need to have Spyder 3.3.6 installed, you can check by searching the version after typing `conda list`. If you can see closely in the discussion, we recommend you to upgrade to Spyder 4 and change the kernel from the IPython console to use python 2.7. Let me know if that helps.

**Comment by Fizz04** [comment]
When i run it through the console, i am able to launch Spyder 3.3.3.  I never had to do that before.  Are you saying in order to launch it through Anaconda Navigator now i need 3.3.6?  What changed that 3.3.3 won't launch through Navigator anymore?

I have a second machine which is near-identical. On it i have updated to Spyder.  In Navigator, it says the version is Spyder 4.0.1.  But when i launch it, it's Spyder 4.1.4, which is what i have in my base environment.  So it's the same issue- regardless of which environment i set in Navigator, it launches the base environment version of Spyder.

So how can i get it to actually launch the correct version of Spyder from Navigator?  Why does Navigator always launch the base environment version?  It never behaved this way before the last update.

But if i have to use Spyder 4, how can i tell it to use python 2.7 via IPython?


-Fizz

**Comment by steff456** [comment]
> When i run it through the console, i am able to launch Spyder 3.3.3. I've never had to launch through the console before. Are you saying in order to launch it through Anaconda Navigator now i need 3.3.6? What changed that 3.3.3 won't launch through Navigator anymore?

You can try to run Spyder 3.3.3 from the console as well, I thought you had installed Spyder 3.3.6.

> I have a second machine which is near-identical. On it i have updated to Spyder. In Navigator, it says the Spyder version is 4.0.1. But when i launch it, it's Spyder 4.1.4, which is what i have in my base environment. So it's the same issue- regardless of which environment i set in Navigator, it launches the base environment version of Spyder.
> So how can i get it to actually launch the correct version of Spyder from Navigator? Why does Navigator always launch the base environment version? It never behaved this way before the last update. I mean, what's the point of setting up separate environments if it's always going to launch the base environment?

I think this is an error from Anaconda Navigator rather than Spyder, so please go ahead and open an issue in https://github.com/conda/conda/issues

> But if i have to use Spyder 4, how can i tell it to use python 2.7 via IPython?

For you to use Spyder 4 with a Python 2.7 kernel you have to first create an environment of Python 2.7
```
conda create -n py2 python=2.7
conda activate py2
pip install spyder-kernels
```

Then deactivate this environment and start Spyder 4 from your base environment
```
conda deactivate
spyder
``` 

Once Spyder 4 is opened, you go to `Preferences > Python Interpreter > Python Interpreter` and check the option to `Use the following Python interpreter` and search your python executable, in Linux you will find it inside the anaconda folder as something like this `~/anaconda3/envs/my-py2-env/bin/python`. Then you will have a python 2 kernel for you to work with. If you want, this video will explain show you how to do this https://www.youtube.com/watch?v=Ul79ihg41Rs&t

Let me know if this helps

**Comment by Fizz04** [comment]
> You can try to run Spyder 3.3.3 from the console as well, I thought you had installed Spyder 3.3.6.

That's what i mean- i can only get Spyder (any other than the base environment version) to work using the console.

> I think this is an error from Anaconda Navigator rather than Spyder, so please go ahead and open an issue in https://github.com/conda/conda/issues

Yes, i think so too.  Guess i posted this in the wrong section.  I will post there too.


-Fizz

**Comment by Fizz04** [comment]
> For you to use Spyder 4 with a Python 2.7 kernel you have to first create an environment of Python 2.7
> ```
> conda create -n py2 python=2.7
> conda activate py2
> pip install spyder-kernels
> ```
> Then deactivate this environment and start Spyder 4 from your base environment
> ```
> conda deactivate
> spyder
> ``` 
> Once Spyder 4 is opened, you go to `Preferences > Python Interpreter > Python Interpreter` and check the option to `Use the following Python interpreter` and search your python executable, in Linux you will find it inside the anaconda folder as something like this `~/anaconda3/envs/my-py2-env/bin/python`. Then you will have a python 2 kernel for you to work with. If you want, this video will explain show you how to do this https://www.youtube.com/watch?v=Ul79ihg41Rs&t

Ah, ok, I've actually tried this (though i already had the py27 environment installed).  It gives me a warning that running this version in conjunction with Spyder running 3.7 may cause issues.  So i'd prefer to keep things consistent as before.

Maybe i should go back to the previous version of anaconda.  Is there a way to that?

-Fizz

**Comment by steff456** [comment]
> Maybe i should go back to the previous version of anaconda. Is there a way to that?

Please review in the anaconda site if that is possible

**Comment by Fizz04** [comment]
I posted the issue in the Anaconda Navigator, as you advised.  But i've seen no replies yet.  What else can i do?

-Fizz

**Comment by steff456** [comment]
Hi @Fizz04,

> Ah, ok, I've actually tried this (though i already had the py27 environment installed). It gives me a warning that running this version in conjunction with Spyder running 3.7 may cause issues. So i'd prefer to keep things consistent as before.

This is a warning we added so people that don't know what's happening know that there's been an important change that may break things in Spyder. As long as you understand that your the kernel in the ipython console will be running in your newly py2 environment you can use it as I instructed before

> I posted the issue in the Anaconda Navigator, as you advised. But i've seen no replies yet. What else can i do?

There's nothing more that I can do, the response in the issue tracker vary a lot among different projects so please be patient.

**Comment by steff456** [comment]
I'm closing this issue because there wasn't a follow-up response after more than a week. If your error persists please re-open this issue and reply with the requested information.

Thanks for reporting!

**Comment by Fizz04** [comment]
I haven't seen any reply from the Conda boards about this, it's been more than a month i think.  So the issue remains.   I'm not sure who to ask about any possible fix otherwise.  Thanks!
-Fizz

**Comment by dalthviz** [comment]
@Fizz04 maybe try to install in your base env anaconda-navigator 1.9.7 (the previous version). You should be able to do it by activating your base env and running `conda install anaconda-navigator=1.9.7` from a terminal

**Comment by Fizz04** [comment]
> @Fizz04 maybe try to install in your base env anaconda-navigator 1.9.7 (the previous version). You should be able to do it by activating your base env and running `conda install anaconda-navigator=1.9.7` from a terminal

So, i have given this a try and it now launches the correct version of Spyder as expected.  But after Spyder launches, i get an Application Launch Error.  It reads:

libGL error: MESA-LOADER: failed to open radeonsi (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open radeonsi (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: swrast

I've never seen these before.  What are these about?

-Fizz

**Comment by dalthviz** [comment]
Hi @Fizz04 that messages seem related with the drivers of your graphics card. I think there is not much we can do to help you further, sorry :/

I'm closing this one since there is not much we can do from our side but if you manage to find more info regarding the issue feel free to post it here

**Comment by Fizz04** [comment]
Please do not close this thread.   This seems particular to something in Spyder itself.  The graphics drivers are from the kernel (no external 3rd party).  I did not have this error on earlier versions of Conda or Spyder, and i did not have this version on the latest version until this downgrade.  So i would like to get feedback from the community about possible causes.

**Comment by dalthviz** [comment]
Makes sense @Fizz04 will leave the issue open :+1:

**Comment by Fizz04** [comment]
Great!  Thanks much!

**Comment by Miguel-LlamasLanza** [comment]
Hi, I do not have many insights about possible causes, but I would like to mention that I get similar Application Launch Error.
In my case, I have a clean installation of everything (Ubuntu, conda and spyder). When launching spyder I get the following:
```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
```
At the moment Spyder seems to work fine. I was just checking about these messages in the Spyder issues when I found this thread, so I decided to add it here in case it is useful. 
If you think it is useful that I open a new issue, tell me please.

**Comment by ccordoba12** [comment]
@Miguel-LlamasLanza, please open a terminal and run

    sudo apt install libgl1-mesa-dri

That should fix that problem.

**Comment by Miguel-LlamasLanza** [comment]
@ccordoba12 
I tried also running `sudo apt install --reinstall libgl1-mesa-dri`, in case there was something wrong with the installation of this library. Still getting the same messages.

I have found out that the two files refered to in the message (`swrast_dri.so` and `iris_dri.so`) are actually stored in `/usr/lib/x86_64-linux-gnu/dri/`, instead of `/usr/lib/dri/`. This is the problably why spyder does not find it. Maybe you find it useful to know that I have Ubuntu 22.04.2 LTS and I am using  Spyder 5.4.2 (Python 3.10.10).

**Comment by ccordoba12** [comment]
Are you using conda or conda-forge packages?

**Comment by Miguel-LlamasLanza** [comment]
I only have one conda-forge package (`statsmodels`). All the ohers are conda packages.
Just to check, I created a new conda environment and installed only spyder with conda. Same messages appear.

**Comment by ccordoba12** [comment]
Ok, please install Spyder from conda-forge and try again.

**Comment by Miguel-LlamasLanza** [comment]
I tried from conda-forge. Those errors disappear, but these appear:
```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.                                                    
fromIccProfile: failed minimal tag size sanity                                                                                                                
/home/lmiguel/anaconda3/envs/test_env/lib/python3.11/site-packages/jupyter_client/threaded.py:73: RuntimeWarning: ZMQStream only supports the base zmq.Socket class.                                                                                                                                                        
                                                                                                                                                              
                Use zmq.Socket(shadow=other_socket)                                                                                                           
                or `ctx.socket(zmq.DEALER, socket_class=zmq.Socket)`                                                                                          
                to create a base zmq.Socket object,                                                                                                           
                no matter what other kind of socket your Context creates.                                                                                     
                                                                                                                                                              
  self.stream = zmqstream.ZMQStream(self.socket, self.ioloop)                                                                                                 
/home/lmiguel/anaconda3/envs/test_env/lib/python3.11/site-packages/jupyter_client/threaded.py:73: RuntimeWarning: ZMQStream only supports the base zmq.Socket class.                                                                                                                                                        
                                                                                                                                                              
                Use zmq.Socket(shadow=other_socket)                                                                                                           
                or `ctx.socket(zmq.SUB, socket_class=zmq.Socket)`                                                                                             
                to create a base zmq.Socket object,                                                                                                           
                no matter what other kind of socket your Context creates.                                                                                     
                                                                                                                                                              
  self.stream = zmqstream.ZMQStream(self.socket, self.ioloop) 
```

**Comment by ccordoba12** [comment]
I'm going to close this issue because I consider it's solved thanks to Conda-forge and there's nothing we can do about it directly in Spyder.

**Comment by Miguel-LlamasLanza** [comment]
I have just installed spyder through conda-forge in a new environment and the error messages are still there. Again, I have not yet encountered any issue within spyder, but I thought it is worth reporting since conda-forge does not seem to solve the issue in all cases. I don't know if it has to do with the versions, but just in case, in this environment I am using python 3.10, and spyder 5.4.3.
