### ISSUE TITLE
Conda Environment Status Shows Full Path

### ISSUE THREAD

**Issue by mrclary** [spyder-ide/spyder#14136]
## Problem Description
@steff456 
Environment status shows full path to conda environment, rather than just environment name.
Pyenv environment status shows correctly.

<img width="528" alt="Screen Shot 2020-11-03 at 8 40 33 AM" src="https://user-images.githubusercontent.com/9618975/98029880-126f9f00-1dc5-11eb-9e03-16ab80b02792.png">
<img width="262" alt="Screen Shot 2020-11-03 at 8 40 51 AM" src="https://user-images.githubusercontent.com/9618975/98029893-16032600-1dc5-11eb-9645-644cf1814580.png">

## Versions

* Spyder version: 4.2.0.dev0 0dfbe8967
* Python version: 3.7.9 64-bit
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 19.6.0

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7      :  0.2.1 (OK)
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree >=3.0.2           :  3.1.0 (OK)
IPython >=4.0                  :  7.18.1 (OK)
jedi =0.17.2                   :  0.17.2 (OK)
jsonschema >=3.2.0             :  3.2.0 (OK)
nbconvert >=4.0                :  6.0.7 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.7.2 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.35.0;<1.0.0           :  test-selector-01+92.g0dfbe8967 (OK)
pyls_black >=0.4.6             :  0.4.6 (OK)
pyls_spyder >=0.1.1            :  0.1.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  1.0.1 (OK)
qtconsole >=4.7.7              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
setuptools >=39.0.0            :  50.3.0.post20201006 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.10.0.dev0 (OK)
three_merge >=0.1.1            :  0.1.1 (OK)
watchdog >=0.10.3              :  0.10.3 (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.3.2 (OK)
numpy >=1.7                    :  1.19.2 (OK)
pandas >=1.1.1                 :  1.1.3 (OK)
scipy >=0.17.0                 :  1.5.2 (OK)
sympy >=0.7.3                  :  1.6.2 (OK)
```

**Comment by steff456** [comment]
@mrclary, can you please show me in a system terminal what happens when you type `conda env list --json` ?

**Comment by mrclary** [comment]
```
(spy-dev) >> conda env list --json
{
  "envs": [
    "/Users/rclary/opt/miniconda3",
    "/Users/rclary/opt/miniconda3/envs/c2w_37",
    "/Users/rclary/opt/miniconda3/envs/spy-conda",
    "/Users/rclary/opt/miniconda3/envs/spy-dev"
  ]
}
(spy-dev) >> 
```

**Comment by mrclary** [comment]
@steff456, do you not see the full path to the directory of the python interpreter for conda environments on your system?

**Comment by steff456** [comment]
In my system I see the name, 

![image](https://user-images.githubusercontent.com/20992645/98032952-c6335780-1de2-11eb-9fcb-c0eb522b4a6a.png)

Are you running Spyder from the macOS app? I'm running Spyder from the terminal, so maybe something weird happened for the macOS app

**Comment by mrclary** [comment]
I'm running from bootstrap in terminal; although this also shows up in Spyder.app

**Comment by steff456** [comment]
Can you try to reset Spyder and see if that works?

**Comment by mrclary** [comment]
Okay, I have to backtrack. It only _appeared_ to manifest on bootstrap. After switching back-and-forth in the preferences, the status resets properly. So, it looks like it is _only_ an issue in Spyder.app and is due to `get_list_conda_envs` returning an empty dictionary. I'll investigate further and report back.

I was using this environment previously, so it was probably already in Spyder's list of environments; this was likely the reason for the status issue.

**Comment by mrclary** [comment]
Okay, I found the problem. subprocess calls for conda were getting messed up by environment variables (probably PYTHONHOME) from the macOS application. All should be fixed with #14123

**Comment by steff456** [comment]
Thanks @mrclary!

**Comment by CAM-Gerlach** [comment]
I still see the full path instead of the env name on Windows, though it may be a side effect of the fact that the new feature is not working at all, per #14160
