### ISSUE TITLE
Go to definition not working

### ISSUE THREAD

**Issue by leyojoseph** [spyder-ide/spyder#14236]
Hello,
I have spyder 4.2.0 on my lab  computer (Windows 10). For some reason, "Go to definition " or CTRL G is no more working.
But  I have Spyder version 4.0.1 on another computer and "Go to definition" is working. How to fix this on Spyder 4.2.0

**Comment by steff456** [comment]
Hi @leyojoseph,

Can you please tell me what are you trying to use to go to definition so I can try it and see if I get the same error?

**Comment by leyojoseph** [comment]
Right click on any import module and select go to definition or CTRL G. This should to take you to the module. 
![image](https://user-images.githubusercontent.com/67446653/99303848-2ed4f800-2817-11eb-84bb-487a2072016a.png)

**Comment by steff456** [comment]
Are you inside a spyder project? If you create a spyder project in the directory where you are working, does the go to definition work?

**Comment by OverLordGoldDragon** [comment]
Go to definition has been unstable in 4.2.0 for me also, not working despite module being on path via PYTHONPATH manager. Haven't observed closely enough to describe when precisely it fails though.

**Comment by Andres-Hernandez** [comment]
For me it simply does not even show as an option in the right-click menu:
![image](https://user-images.githubusercontent.com/13715648/99780186-693fdd00-2b16-11eb-9f11-e4caf687320b.png)

**Comment by Ikhwansong** [comment]
In my case, i encountered the same error. 
I re-installed the spyder 4.1.3 and it worked again.

**Comment by jsh9** [comment]
I had to downgrade to an older Spyder version too.  The newest Spyder versions are basically unusable for me because of this bug.

I saw that this ticket has been deferred several times (from v4.2.1 to v4.2.2 and now to "missing")...

**Comment by steff456** [comment]
Hi @Ikhwansong and @jsh9 what OS are you working on? I'm not able to reproduce this issue in macOS or linux

**Comment by Ikhwansong** [comment]
> Hi @Ikhwansong and @jsh9 what OS are you working on? I'm not able to reproduce this issue in macOS or linux

# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
_libgcc_mutex=0.1=main
alabaster=0.7.12=pyhd3eb1b0_0
argh=0.26.2=py38_0
astroid=2.5=py38h06a4308_1
async_generator=1.10=pyhd3eb1b0_0
atomicwrites=1.4.0=py_0
attrs=20.3.0=pyhd3eb1b0_0
autopep8=1.5.5=pyhd3eb1b0_0
babel=2.9.0=pyhd3eb1b0_0
backcall=0.2.0=pyhd3eb1b0_0
blas=1.0=mkl
bleach=3.3.0=pyhd3eb1b0_0
blosc=1.21.0=h8c45485_0
brotli=1.0.9=he6710b0_2
brotlipy=0.7.0=py38h27cfd23_1003
brunsli=0.1=h2531618_0
bzip2=1.0.8=h7b6447c_0
ca-certificates=2021.1.19=h06a4308_1
certifi=2020.12.5=py38h06a4308_0
cffi=1.14.5=py38h261ae71_0
chardet=4.0.0=py38h06a4308_1003
charls=2.1.0=he6710b0_2
cloudpickle=1.6.0=py_0
colorama=0.4.4=pyhd3eb1b0_0
cryptography=3.4.6=py38hd23ed53_0
cudatoolkit=10.2.89=hfd86e86_1
cycler=0.10.0=py38_0
cytoolz=0.11.0=py38h7b6447c_0
dask-core=2021.3.0=pyhd3eb1b0_0
dbus=1.13.18=hb2f20db_0
decorator=4.4.2=pyhd3eb1b0_0
defusedxml=0.7.1=pyhd3eb1b0_0
diff-match-patch=20200713=py_0
docutils=0.16=py38_1
easydict=1.9=pypi_0
entrypoints=0.3=py38_0
expat=2.2.10=he6710b0_2
ffmpeg=4.2.2=h20bf706_0
flake8=3.8.4=py_0
fontconfig=2.13.1=h6c09931_0
freetype=2.10.4=h5ab3b9f_0
future=0.18.2=py38_1
giflib=5.1.4=h14c3975_1
glib=2.67.4=h36276a3_1
gmp=6.2.1=h2531618_2
gnutls=3.6.5=h71b1129_1002
gst-plugins-base=1.14.0=h8213a91_2
gstreamer=1.14.0=h28cd5cc_2
h5py=3.2.1=pypi_0
hdf5storage=0.1.17=pypi_0
icu=58.2=he6710b0_3
idna=2.10=pyhd3eb1b0_0
imagecodecs=2021.1.11=py38h581e88b_1
imageio=2.9.0=py_0
imagesize=1.2.0=pyhd3eb1b0_0
importlib-metadata=2.0.0=py_1
importlib_metadata=2.0.0=1
intel-openmp=2020.2=254
intervaltree=3.1.0=py_0
ipykernel=5.3.4=py38h5ca1d4c_0
ipython=7.21.0=py38hb070fc8_0
ipython_genutils=0.2.0=pyhd3eb1b0_1
isort=5.7.0=pyhd3eb1b0_0
jedi=0.15.2=py38_0
jeepney=0.6.0=pyhd3eb1b0_0
jinja2=2.11.3=pyhd3eb1b0_0
joblib=1.0.1=pyhd3eb1b0_0
jpeg=9b=h024ee3a_2
jsonschema=3.2.0=py_2
jupyter_client=6.1.7=py_0
jupyter_core=4.7.1=py38h06a4308_0
jupyterlab_pygments=0.1.2=py_0
jxrlib=1.1=h7b6447c_2
keyring=22.3.0=py38h06a4308_0
kiwisolver=1.3.1=py38h2531618_0
lame=3.100=h7b6447c_0
lazy-object-proxy=1.5.2=py38h27cfd23_0
lcms2=2.11=h396b838_0
ld_impl_linux-64=2.33.1=h53a641e_7
lerc=2.2.1=h2531618_0
libaec=1.0.4=he6710b0_1
libdeflate=1.7=h27cfd23_5
libffi=3.3=he6710b0_2
libgcc-ng=9.1.0=hdf63c60_0
libgfortran-ng=7.3.0=hdf63c60_0
libopus=1.3.1=h7b6447c_0
libpng=1.6.37=hbc83047_0
libsodium=1.0.18=h7b6447c_0
libspatialindex=1.9.3=he6710b0_0
libstdcxx-ng=9.1.0=hdf63c60_0
libtiff=4.1.0=h2733197_1
libuuid=1.0.3=h1bed415_2
libuv=1.40.0=h7b6447c_0
libvpx=1.7.0=h439df22_0
libwebp=1.0.1=h8e7db2f_0
libxcb=1.14=h7b6447c_0
libxml2=2.9.10=hb55368b_3
libzopfli=1.0.3=he6710b0_0
lz4-c=1.9.3=h2531618_0
markupsafe=1.1.1=py38h7b6447c_0
matplotlib=3.3.4=py38h06a4308_0
matplotlib-base=3.3.4=py38h62a2d02_0
mccabe=0.6.1=py38_1
mistune=0.8.4=py38h7b6447c_1000
mkl=2020.2=256
mkl-service=2.3.0=py38he904b0f_0
mkl_fft=1.3.0=py38h54f3939_0
mkl_random=1.1.1=py38h0573a6f_0
nbclient=0.5.3=pyhd3eb1b0_0
nbconvert=6.0.7=py38_0
nbformat=5.1.2=pyhd3eb1b0_1
ncurses=6.2=he6710b0_1
nest-asyncio=1.5.1=pyhd3eb1b0_0
nettle=3.4.1=hbb512f6_0
networkx=2.5=py_0
ninja=1.10.2=py38hff7bd54_0
numpy=1.19.2=py38h54aff64_0
numpy-base=1.19.2=py38hfa32c7d_0
numpydoc=1.1.0=pyhd3eb1b0_1
olefile=0.46=py_0
opencv-python=4.5.1.48=pypi_0
openh264=2.1.0=hd408876_0
openjpeg=2.3.0=h05c96fa_1
openssl=1.1.1j=h27cfd23_0
packaging=20.9=pyhd3eb1b0_0
pandas=1.2.3=py38ha9443f7_0
pandoc=2.11=hb0f4dca_0
pandocfilters=1.4.3=py38h06a4308_1
parso=0.5.2=py_0
pcre=8.44=he6710b0_0
pexpect=4.8.0=pyhd3eb1b0_3
pickleshare=0.7.5=pyhd3eb1b0_1003
pillow=8.1.2=py38he98fc37_0
pip=21.0.1=py38h06a4308_0
pluggy=0.13.1=py38_0
prompt-toolkit=3.0.8=py_0
psutil=5.8.0=py38h27cfd23_1
ptyprocess=0.7.0=pyhd3eb1b0_2
pycodestyle=2.6.0=pyhd3eb1b0_0
pycparser=2.20=py_2
pydocstyle=5.1.1=py_0
pyflakes=2.2.0=pyhd3eb1b0_0
pygments=2.8.1=pyhd3eb1b0_0
pylint=2.7.2=py38h06a4308_1
pyls-spyder=0.2.1=pyhd3eb1b0_0
pyopenssl=20.0.1=pyhd3eb1b0_1
pyparsing=2.4.7=pyhd3eb1b0_0
pyqt=5.9.2=py38h05f1152_4
pyrsistent=0.17.3=py38h7b6447c_0
pysocks=1.7.1=py38h06a4308_0
python=3.8.8=hdb3f193_4
python-dateutil=2.8.1=pyhd3eb1b0_0
python-jsonrpc-server=0.3.4=py_1
python-language-server=0.31.9=py38_0
pytorch=1.8.0=py3.8_cuda10.2_cudnn7.6.5_0
pytz=2021.1=pyhd3eb1b0_0
pywavelets=1.1.1=py38h7b6447c_2
pyxdg=0.27=pyhd3eb1b0_0
pyyaml=5.4.1=py38h27cfd23_1
pyzmq=20.0.0=py38h2531618_1
qdarkstyle=2.8.1=py_0
qt=5.9.7=h5867ecd_1
qtawesome=1.0.1=py_0
qtconsole=5.0.2=pyhd3eb1b0_0
qtpy=1.9.0=py_0
readline=8.1=h27cfd23_0
requests=2.25.1=pyhd3eb1b0_0
rope=0.18.0=py_0
rtree=0.8.0=pypi_0
scikit-image=0.17.2=py38hdf5156a_0
scikit-learn=0.24.1=py38ha9443f7_0
scipy=1.6.1=py38h91f5cce_0
secretstorage=3.3.1=py38h06a4308_0
setuptools=52.0.0=py38h06a4308_0
sip=4.19.13=py38he6710b0_0
six=1.15.0=py38h06a4308_0
snappy=1.1.8=he6710b0_0
snowballstemmer=2.1.0=pyhd3eb1b0_0
sortedcontainers=2.3.0=pyhd3eb1b0_0
sphinx=3.5.2=pyhd3eb1b0_0
sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
sphinxcontrib-htmlhelp=1.0.3=pyhd3eb1b0_0
sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
sphinxcontrib-serializinghtml=1.1.4=pyhd3eb1b0_0
spyder=4.1.3=py38_0
spyder-kernels=1.9.1=py38_0
spyder_parso_requirement=1.0=0
sqlite=3.35.0=hdfb4753_0
testpath=0.4.4=pyhd3eb1b0_0
threadpoolctl=2.1.0=pyh5ca1d4c_0
tifffile=2021.3.5=pyhd3eb1b0_1
tk=8.6.10=hbc83047_0
toml=0.10.1=py_0
toolz=0.11.1=pyhd3eb1b0_0
torchaudio=0.8.0=py38
torchvision=0.9.0=py38_cu102
tornado=6.1=py38h27cfd23_0
traitlets=5.0.5=pyhd3eb1b0_0
typing_extensions=3.7.4.3=pyha847dfd_0
ujson=1.35=py38h7b6447c_0
urllib3=1.26.3=pyhd3eb1b0_0
watchdog=1.0.2=py38h06a4308_1
wcwidth=0.2.5=py_0
webencodings=0.5.1=py38_1
wheel=0.36.2=pyhd3eb1b0_0
wrapt=1.12.1=py38h7b6447c_1
wurlitzer=2.0.1=py38_0
x264=1!157.20191217=h7b6447c_0
xz=5.2.5=h7b6447c_0
yaml=0.2.5=h7b6447c_0
yapf=0.31.0=pyhd3eb1b0_0
zeromq=4.3.3=he6710b0_3
zfp=0.5.5=h2531618_4
zipp=3.4.0=pyhd3eb1b0_0
zlib=1.2.11=h7b6447c_3
zstd=1.4.5=h9ceee32_0

This is my packagelist exported by conda list --export command.
Please refer this list.

And i am using Linux as my operating system so far.

The "go to definition" and whatever any commands work well!

**Comment by jsh9** [comment]
@steff456 I'm using macOS.

Please see details of how to reproduce this bug here: https://github.com/spyder-ide/spyder/issues/14604

**Comment by jsh9** [comment]
@ccordoba12 @steff456 

Hi, may I ask whether there are any plans to fix this bug? This bug completely breaks the user experience of Spyder, and hence forces me to be stuck in version 4.1.3.

Thanks!

**Comment by steff456** [comment]
Hi @jsh9,

We've been focused in the release of Spyder 5 and right now we are focusing on stabilizing some issues on that version. Once we do that we will try to add this issue into the high priority ones but I cannot give you any time frame. If you are really interested in seeing this fixed soon I encourage you to contribute to the project, we can guide you in fixing this PR.

**Comment by jsh9** [comment]
Could you give me a link to the method that is called when "Go to definition" is clicked on?  And could you show me how your team usually diagnose and/or debug issues, for example, print logs to somewhere, or monitor values of variables?

I'd interested to try to fix it, but I do not have much expertise with this software.

**Comment by a-allard** [comment]
Hi all,

I'm having the same issue with "Go to definition" not working.  Running spyder 5.0.1 on Ubuntu 20.04.

No error message or anything is produced.  Nothing happens at all (when either Ctrl+G or the menu option is used).

Here is the info about my install:
* Spyder version: 5.0.1 None
* Python version: 3.8.5 64-bit
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Linux 5.8.0-48-generic

Dependencies:

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.8.1 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.0 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
setuptools >=39.0.0           :  56.0.0 (OK)
sphinx >=0.6.6                :  3.5.4 (OK)
spyder_kernels >=2.0.1;<2.1.0 :  2.0.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  22.0.3 (OK)

# Optional:
cython >=0.21                 :  0.29.23 (OK)
matplotlib >=2.0.0            :  3.4.1 (OK)
numpy >=1.7                   :  1.20.2 (OK)
pandas >=1.1.1                :  1.2.4 (OK)
scipy >=0.17.0                :  1.6.3 (OK)
sympy >=0.7.3                 :  1.8 (OK)

Hope this helps.

**Comment by tupsukka** [comment]
Issues here too. Go to definition are not working. Also links from console error printout to lines and files are not working. 
Win10, packages updated via Anaconda.

**Comment by Ikhwansong** [comment]
Hi, recently  i make a success of finding stable version assembly. 

The version names are below
1. python <=3.8
2. spyder ==4.1.3
3. spyder-kenels ==1.9.3
4. parso ==0.5.2

here is the footprint of conda list
<details>
    <summary>자세히</summary>


 # This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
_libgcc_mutex=0.1=main
alabaster=0.7.12=pyhd3eb1b0_0
argh=0.26.2=py38_0
astroid=2.5=py38h06a4308_1
async_generator=1.10=pyhd3eb1b0_0
atomicwrites=1.4.0=py_0
attrs=20.3.0=pyhd3eb1b0_0
autopep8=1.5.6=pyhd3eb1b0_0
babel=2.9.0=pyhd3eb1b0_0
backcall=0.2.0=pyhd3eb1b0_0
blas=1.0=mkl
bleach=3.3.0=pyhd3eb1b0_0
brotlipy=0.7.0=py38h27cfd23_1003
bzip2=1.0.8=h7b6447c_0
ca-certificates=2021.4.13=h06a4308_1
certifi=2020.12.5=py38h06a4308_0
cffi=1.14.5=py38h261ae71_0
chardet=4.0.0=py38h06a4308_1003
cloudpickle=1.6.0=py_0
colorama=0.4.4=pyhd3eb1b0_0
cryptography=3.4.7=py38hd23ed53_0
cudatoolkit=10.2.89=hfd86e86_1
cycler=0.10.0=py38_0
cytoolz=0.11.0=py38h7b6447c_0
dask-core=2021.4.0=pyhd3eb1b0_0
dbus=1.13.18=hb2f20db_0
decorator=4.4.2=pyhd3eb1b0_0
defusedxml=0.7.1=pyhd3eb1b0_0
diff-match-patch=20200713=py_0
docutils=0.17=py38h06a4308_1
easydict=1.9=pypi_0
entrypoints=0.3=py38_0
expat=2.3.0=h2531618_2
ffmpeg=4.3=hf484d3e_0
flake8=3.9.0=pyhd3eb1b0_0
fontconfig=2.13.1=h6c09931_0
freetype=2.10.4=h5ab3b9f_0
fsspec=0.9.0=pyhd3eb1b0_0
future=0.18.2=py38_1
glib=2.68.1=h36276a3_0
gmp=6.2.1=h2531618_2
gnutls=3.6.15=he1e5248_0
gst-plugins-base=1.14.0=h8213a91_2
gstreamer=1.14.0=h28cd5cc_2
h5py=3.2.1=pypi_0
hdf5storage=0.1.17=pypi_0
icu=58.2=he6710b0_3
idna=2.10=pyhd3eb1b0_0
imageio=2.9.0=pyhd3eb1b0_0
imagesize=1.2.0=pyhd3eb1b0_0
importlib-metadata=3.10.0=py38h06a4308_0
importlib_metadata=3.10.0=hd3eb1b0_0
intel-openmp=2020.2=254
intervaltree=3.1.0=py_0
ipykernel=5.3.4=py38h5ca1d4c_0
ipython=7.22.0=py38hb070fc8_0
ipython_genutils=0.2.0=pyhd3eb1b0_1
isort=5.8.0=pyhd3eb1b0_0
jedi=0.15.2=py38_0
jeepney=0.6.0=pyhd3eb1b0_0
jinja2=2.11.3=pyhd3eb1b0_0
joblib=1.0.1=pyhd3eb1b0_0
jpeg=9b=h024ee3a_2
jsonschema=3.2.0=py_2
jupyter_client=6.1.12=pyhd3eb1b0_0
jupyter_core=4.7.1=py38h06a4308_0
jupyterlab_pygments=0.1.2=py_0
keyring=22.3.0=py38h06a4308_0
kiwisolver=1.3.1=py38h2531618_0
lame=3.100=h7b6447c_0
lazy-object-proxy=1.6.0=py38h27cfd23_0
lcms2=2.12=h3be6417_0
ld_impl_linux-64=2.33.1=h53a641e_7
libffi=3.3=he6710b0_2
libgcc-ng=9.1.0=hdf63c60_0
libgfortran-ng=7.3.0=hdf63c60_0
libiconv=1.15=h63c8f33_5
libidn2=2.3.0=h27cfd23_0
libpng=1.6.37=hbc83047_0
libsodium=1.0.18=h7b6447c_0
libspatialindex=1.9.3=h2531618_0
libstdcxx-ng=9.1.0=hdf63c60_0
libtasn1=4.16.0=h27cfd23_0
libtiff=4.1.0=h2733197_1
libunistring=0.9.10=h27cfd23_0
libuuid=1.0.3=h1bed415_2
libuv=1.40.0=h7b6447c_0
libxcb=1.14=h7b6447c_0
libxml2=2.9.10=hb55368b_3
locket=0.2.1=py38h06a4308_1
lz4-c=1.9.3=h2531618_0
markupsafe=1.1.1=py38h7b6447c_0
matplotlib=3.3.4=py38h06a4308_0
matplotlib-base=3.3.4=py38h62a2d02_0
mccabe=0.6.1=py38_1
mistune=0.8.4=py38h7b6447c_1000
mkl=2020.2=256
mkl-service=2.3.0=py38he904b0f_0
mkl_fft=1.3.0=py38h54f3939_0
mkl_random=1.1.1=py38h0573a6f_0
nbclient=0.5.3=pyhd3eb1b0_0
nbconvert=6.0.7=py38_0
nbformat=5.1.3=pyhd3eb1b0_0
ncurses=6.2=he6710b0_1
nest-asyncio=1.5.1=pyhd3eb1b0_0
nettle=3.7.2=hbbd107a_1
networkx=2.5.1=pyhd3eb1b0_0
ninja=1.10.2=hff7bd54_1
numpy=1.19.2=py38h54aff64_0
numpy-base=1.19.2=py38hfa32c7d_0
numpydoc=1.1.0=pyhd3eb1b0_1
olefile=0.46=py_0
opencv-python=4.5.1.48=pypi_0
openh264=2.1.0=hd408876_0
openssl=1.1.1k=h27cfd23_0
packaging=20.9=pyhd3eb1b0_0
pandas=1.2.4=py38h2531618_0
pandoc=2.12=h06a4308_0
pandocfilters=1.4.3=py38h06a4308_1
parso=0.5.2=py_0
partd=1.2.0=pyhd3eb1b0_0
pcre=8.44=he6710b0_0
pexpect=4.8.0=pyhd3eb1b0_3
pickleshare=0.7.5=pyhd3eb1b0_1003
pillow=8.2.0=py38he98fc37_0
pip=21.0.1=py38h06a4308_0
pluggy=0.13.1=py38h06a4308_0
prompt-toolkit=3.0.17=pyh06a4308_0
psutil=5.8.0=py38h27cfd23_1
ptyprocess=0.7.0=pyhd3eb1b0_2
pycodestyle=2.6.0=pyhd3eb1b0_0
pycparser=2.20=py_2
pydocstyle=6.0.0=pyhd3eb1b0_0
pyflakes=2.2.0=pyhd3eb1b0_0
pygments=2.8.1=pyhd3eb1b0_0
pylint=2.7.4=py38h06a4308_1
pyopenssl=20.0.1=pyhd3eb1b0_1
pyparsing=2.4.7=pyhd3eb1b0_0
pyqt=5.9.2=py38h05f1152_4
pyrsistent=0.17.3=py38h7b6447c_0
pysocks=1.7.1=py38h06a4308_0
python=3.8.8=hdb3f193_5
python-dateutil=2.8.1=pyhd3eb1b0_0
python-jsonrpc-server=0.3.4=py_1
python-language-server=0.31.9=py38_0
pytorch=1.8.1=py3.8_cuda10.2_cudnn7.6.5_0
pytz=2021.1=pyhd3eb1b0_0
pywavelets=1.1.1=py38h7b6447c_2
pyxdg=0.27=pyhd3eb1b0_0
pyyaml=5.4.1=py38h27cfd23_1
pyzmq=20.0.0=py38h2531618_1
qdarkstyle=3.0.2=pyhd3eb1b0_0
qt=5.9.7=h5867ecd_1
qtawesome=1.0.2=pyhd3eb1b0_0
qtconsole=5.0.3=pyhd3eb1b0_0
qtpy=1.9.0=py_0
readline=8.1=h27cfd23_0
requests=2.25.1=pyhd3eb1b0_0
rope=0.18.0=py_0
rtree=0.9.4=py38_1
scikit-image=0.18.1=py38ha9443f7_0
scikit-learn=0.24.1=py38ha9443f7_0
scipy=1.6.2=py38h91f5cce_0
secretstorage=3.3.1=py38h06a4308_0
setuptools=52.0.0=py38h06a4308_0
sip=4.19.13=py38he6710b0_0
six=1.15.0=py38h06a4308_0
snowballstemmer=2.1.0=pyhd3eb1b0_0
sortedcontainers=2.3.0=pyhd3eb1b0_0
sphinx=3.5.3=pyhd3eb1b0_0
sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
sphinxcontrib-htmlhelp=1.0.3=pyhd3eb1b0_0
sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
sphinxcontrib-serializinghtml=1.1.4=pyhd3eb1b0_0
spyder=4.1.3=py38_0
spyder-kernels=1.9.3=py38_0
sqlite=3.35.4=hdfb4753_0
testpath=0.4.4=pyhd3eb1b0_0
threadpoolctl=2.1.0=pyh5ca1d4c_0
tifffile=2020.10.1=py38hdd07704_2
tk=8.6.10=hbc83047_0
toml=0.10.2=pyhd3eb1b0_0
toolz=0.11.1=pyhd3eb1b0_0
torchaudio=0.8.1=py38
torchvision=0.9.1=py38_cu102
tornado=6.1=py38h27cfd23_0
traitlets=5.0.5=pyhd3eb1b0_0
typing_extensions=3.7.4.3=pyha847dfd_0
ujson=1.35=py38h7b6447c_0
urllib3=1.26.4=pyhd3eb1b0_0
watchdog=1.0.2=py38h06a4308_1
wcwidth=0.2.5=py_0
webencodings=0.5.1=py38_1
wheel=0.36.2=pyhd3eb1b0_0
wrapt=1.12.1=py38h7b6447c_1
wurlitzer=2.1.0=py38h06a4308_0
xz=5.2.5=h7b6447c_0
yaml=0.2.5=h7b6447c_0
yapf=0.31.0=pyhd3eb1b0_0
zeromq=4.3.4=h2531618_0
zipp=3.4.1=pyhd3eb1b0_0
zlib=1.2.11=h7b6447c_3
zstd=1.4.9=haebb681_0
</details>

**Comment by ccordoba12** [comment]
@tupsukka, the "Go to definition" error will be fixed in our next version (5.0.2), to be released shortly. The problem with links in the console was fixed in 5.0.1, which is not part of Anaconda yet.

**Comment by Gilbert-W** [comment]
I just had this issue in spyder 5.0.3. 

The Go to definition option wasn't appearing in the right-click menu, nor could I get it with CTRL-G.

Fixed by resetting spyder to factory default settings. Sort of annoying, but it worked...

**Comment by jsh9** [comment]
This bug is still present for Version 5.0.5.

Specifically, "go to definition" does not work when trying to go to a script in the same folder (same issue as https://github.com/spyder-ide/spyder/issues/14604), and "go to definition" only works when trying to go to scripts in another folder.

(Operating system: macOS)

**Comment by ccordoba12** [comment]
Ok, I'll close this one in favor of issue #13358 because it's older and I'll try to solve it in 5.1.0, to be released this weekend.
