### ISSUE TITLE
Spyder 4.2.1 - erroneous missing rtree dependency

### ISSUE THREAD

**Issue by pythonic2020** [spyder-ide/spyder#14466]
I just installed spyder 4.2.1 (conda-forge) into a conda environment running Python 3.7.9.  When I start spyder, a window pops up and states that a dependency is missing, namely rtree >=0.8.3.  

![Untitled](https://user-images.githubusercontent.com/61034042/102723660-a5598f80-42c6-11eb-8247-92d7417776a1.png)

However, rtree 0.9.5 is installed.  

```
# Name                    Version                   Build  Channel
rtree                     0.9.5            py37h13cc57e_0    conda-forge
```

Removing/reinstalling rtree and spyder doesn't stop the warning.  Is this a bug, or is there something wrong with my environment?

**Comment by LeeSunBowen** [comment]
I met this problem yesterday and many methods couldn't work. Finally I re-installed the last anaconda and updated spyder, it was solved. You can try it if you have no other idea, good luck.

**Comment by steff456** [comment]
Hi @pythonic2020,

Can you please create a new environment and install spyder 4.2.1 and see if the error happens in a clean environment?

```
conda create -n test-env python=3.7.9
conda activate test-env
conda install spyder=4.2.1
```

**Comment by ccordoba12** [comment]
@steff456, 4.2.1 is still not available in the defaults channel, so this could be an issue with conda-forge.

**Comment by pythonic2020** [comment]
I got the same issue after creating test env thus:

conda create -n test-env python=3.7.9
conda activate test-env
conda install spyder=4.2.1 -c conda-forge

**Comment by manfred2020** [comment]
same here

**Comment by steff456** [comment]
@pythonic2020 and @manfred2020 when you do `conda list` in the env does rtree appear?

**Comment by manfred2020** [comment]
yes, version 0.9.7.

but... i had a completely different experience a few days ago:
i had some problems with a script that uses geopandas. error message was, that "spatialindex_c-64.dll" could not be found ("OSError: could not find or load spatialindex_c-64.dll"). (my script worked all the weeks before, i don't what happened). 
so i searched the internet and one tipp was, to copy the script (which existed in "...\anaconda3\Library\bin" to "...\anaconda3\envs\MyEnvironmentName\Lib\site-packages\rtree"

since then everything worked as before, my geopands script works and spyder 4.2.1 works, no more rtree message.

what's your opinion on that?

**Comment by pythonic2020** [comment]
Hi @steff456,

Yes.
```
> conda list rtree
# packages in environment at C:\Users\me\Miniconda3\envs\forge:
#
# Name                    Version                   Build  Channel
rtree                     0.9.7            py37h13cc57e_0    conda-forge
```

**Comment by dalthviz** [comment]
Note: Maybe this is related with the way we are checking the versions of the packages. I think in https://github.com/spyder-ide/spyder/pull/14014 we manage to improve the way we detect the version of packages but maybe for the rtree `conda-forge` version is not enough?

**Comment by ccordoba12** [comment]
@dalthviz, that's what I think too. Could you set a conda env on Windows and install 4.2.1 with conda-forge to see if you're seeing the same message?

**Comment by dalthviz** [comment]
@ccordoba12 I was unable to reproduce this... This the list of packages installed in my env:

#### conda list output

<details>

```
# packages in environment at C:\Users\Daniel\Anaconda3\envs\s4.2.1:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
argh                      0.26.2          pyh9f0ad1d_1002    conda-forge
astroid                   2.4.2            py37hc8dfbb8_1    conda-forge
async_generator           1.10                       py_0    conda-forge
atomicwrites              1.4.0              pyh9f0ad1d_0    conda-forge
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
autopep8                  1.5.4              pyh9f0ad1d_0    conda-forge
babel                     2.9.0              pyhd3deb0d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
bcrypt                    3.2.0            py37h4ab8f01_1    conda-forge
black                     20.8b1                     py_1    conda-forge
bleach                    3.2.1              pyh9f0ad1d_0    conda-forge
brotlipy                  0.7.0           py37h0013d47_1001    conda-forge
ca-certificates           2020.12.5            h5b45459_0    conda-forge
certifi                   2020.12.5        py37h03978a9_1    conda-forge
cffi                      1.14.4           py37hd8e9650_1    conda-forge
chardet                   4.0.0            py37h03978a9_1    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
cloudpickle               1.6.0                      py_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
cryptography              3.3.1            py37hd8e9650_0    conda-forge
dataclasses               0.7                pyhb2cacf7_7    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
diff-match-patch          20200713           pyh9f0ad1d_0    conda-forge
docutils                  0.16             py37h03978a9_3    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
flake8                    3.8.4                      py_0    conda-forge
future                    0.18.2           py37h03978a9_3    conda-forge
helpdev                   0.7.1              pyhd8ed1ab_0    conda-forge
icu                       68.1                 h0e60522_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
importlib-metadata        3.3.0            py37h03978a9_3    conda-forge
importlib_metadata        3.3.0                hd8ed1ab_3    conda-forge
intervaltree              3.0.2                      py_0    conda-forge
ipykernel                 5.4.2            py37h7b7c402_0    conda-forge
ipython                   7.19.0           py37heaed05f_1    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
isort                     5.7.0              pyhd8ed1ab_0    conda-forge
jedi                      0.17.2           py37h03978a9_1    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
jpeg                      9d                   h8ffe710_0    conda-forge
jsonschema                3.2.0                      py_2    conda-forge
jupyter_client            6.1.11             pyhd8ed1ab_0    conda-forge
jupyter_core              4.7.0            py37h03978a9_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
keyring                   21.8.0           py37h03978a9_0    conda-forge
lazy-object-proxy         1.4.3            py37h4ab8f01_2    conda-forge
libclang                  11.0.0          default_h5c34c98_2    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libspatialindex           1.9.3                he025d50_3    conda-forge
markupsafe                1.1.1            py37hcc03f2d_3    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.4           py37hcc03f2d_1003    conda-forge
mypy_extensions           0.4.3            py37h03978a9_3    conda-forge
nbclient                  0.5.1                      py_0    conda-forge
nbconvert                 6.0.7            py37h03978a9_3    conda-forge
nbformat                  5.0.8                      py_0    conda-forge
nest-asyncio              1.4.3              pyhd8ed1ab_0    conda-forge
numpydoc                  1.1.0                      py_1    conda-forge
openssl                   1.1.1i               h8ffe710_0    conda-forge
packaging                 20.8               pyhd3deb0d_0    conda-forge
pandoc                    2.11.3.2             h8ffe710_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
paramiko                  2.7.2              pyh9f0ad1d_0    conda-forge
parso                     0.7.0              pyh9f0ad1d_0    conda-forge
pathspec                  0.8.1              pyhd3deb0d_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pip                       20.3.3             pyhd8ed1ab_0    conda-forge
pluggy                    0.13.1           py37hf50a25e_3    conda-forge
prompt-toolkit            3.0.10             pyha770c72_0    conda-forge
psutil                    5.8.0            py37hcc03f2d_1    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pycodestyle               2.6.0              pyh9f0ad1d_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pydocstyle                5.1.1                      py_0    conda-forge
pyflakes                  2.2.0              pyh9f0ad1d_0    conda-forge
pygments                  2.7.3              pyhd8ed1ab_0    conda-forge
pylint                    2.6.0            py37hc8dfbb8_1    conda-forge
pyls-black                0.4.6              pyh9f0ad1d_0    conda-forge
pyls-spyder               0.3.0              pyhd8ed1ab_0    conda-forge
pynacl                    1.4.0            py37h230ea1a_2    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.12.3           py37h03978a9_6    conda-forge
pyqt-impl                 5.12.3           py37hf2a7229_6    conda-forge
pyqt5-sip                 4.19.18          py37hf2a7229_6    conda-forge
pyqtchart                 5.12             py37hf2a7229_6    conda-forge
pyqtwebengine             5.12.1           py37hf2a7229_6    conda-forge
pyrsistent                0.17.3           py37hcc03f2d_2    conda-forge
pysocks                   1.7.1            py37hf50a25e_2    conda-forge
python                    3.7.9           h7840368_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-jsonrpc-server     0.4.0              pyh9f0ad1d_0    conda-forge
python-language-server    0.36.2             pyhd8ed1ab_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.5             pyhd8ed1ab_0    conda-forge
pywin32                   228              py37hcc03f2d_1    conda-forge
pywin32-ctypes            0.2.0           py37h03978a9_1003    conda-forge
pyyaml                    5.3.1            py37hcc03f2d_2    conda-forge
pyzmq                     20.0.0           py37h0d95fc2_1    conda-forge
qdarkstyle                2.8.1              pyhd8ed1ab_2    conda-forge
qt                        5.12.9               h5909a2a_2    conda-forge
qtawesome                 1.0.2              pyhd8ed1ab_0    conda-forge
qtconsole                 5.0.1              pyhd8ed1ab_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
regex                     2020.11.13       py37hcc03f2d_1    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
rope                      0.18.0             pyh9f0ad1d_0    conda-forge
rtree                     0.9.7            py37h13cc57e_1    conda-forge
setuptools                49.6.0           py37h03978a9_3    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snowballstemmer           2.0.0                      py_0    conda-forge
sortedcontainers          2.3.0              pyhd8ed1ab_0    conda-forge
sphinx                    3.4.3              pyhd8ed1ab_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.3                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.4                      py_0    conda-forge
spyder                    4.2.1            py37h03978a9_0    conda-forge
spyder-kernels            1.10.1           py37h03978a9_0    conda-forge
sqlite                    3.34.0               h8ffe710_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
textdistance              4.2.0              pyhd8ed1ab_0    conda-forge
three-merge               0.1.1              pyh9f0ad1d_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tornado                   6.1              py37hcc03f2d_1    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
typed-ast                 1.4.2            py37hcc03f2d_0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
ujson                     4.0.1            py37hf2a7229_2    conda-forge
urllib3                   1.26.2             pyhd8ed1ab_0    conda-forge
vc                        14.2                 hb210afc_2    conda-forge
vs2015_runtime            14.28.29325          h5e1d092_0    conda-forge
watchdog                  1.0.2            py37h03978a9_1    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
win_inet_pton             1.1.0            py37h03978a9_2    conda-forge
wincertstore              0.2             py37h03978a9_1006    conda-forge
wrapt                     1.11.2           py37h4ab8f01_1    conda-forge
yaml                      0.2.5                he774522_0    conda-forge
yapf                      0.30.0             pyh9f0ad1d_0    conda-forge
zeromq                    4.3.3                h0e60522_3    conda-forge
zipp                      3.4.0                      py_0    conda-forge
zlib                      1.2.11            h62dcd97_1010    conda-forge
```

</details> 

However I noticed that the build version of the `rtree` package changed (the `1` at the end in my packages list is a `0` in the version given by @pythonic2020 ):

         rtree                     0.9.7            py37h13cc57e_1    conda-forge

Then I think a new build of the package is available! @manfred2020 @pythonic2020 could you try to reinstall `rtree`? (check that the version installed has the `1` at the end). Thanks!

**Comment by pythonic2020** [comment]
I get the spyder erroneous dependency warning with the same conda-forge rtree build (py37h13cc57e_1) as you.

**Comment by dalthviz** [comment]
And is there any other difference between your env and the one I created @pythonic2020 ? Any new info in order to reproduce this is greatly appreciated :)

**Comment by ccordoba12** [comment]
@pythonic2020, please open the Anaconda Prompt, run the following command

    conda list

and post the output here. I think your problem is related to installation issues.

**Comment by pythonic2020** [comment]
I executed these commands, and the problem does **not** occur:

```
conda create -n test-env -c conda-forge python=3.7.9
conda activate test-env
conda install spyder -c conda-forge
spyder
```

The above uses the latest rtree version (build ...57e_1) and spyder 4.2.1.  No problems.

If an environment has mixed packages from pkgs/main and conda-forge, the problem occurs with spyder 4.2.1.  If you execute the commands I posted above:

```
conda create -n test-env python=3.7.9
conda activate test-env
conda install spyder=4.2.1 -c conda-forge
```
the missing dependency warning occurs.  Here is output of package list:

```
> conda list
# packages in environment at C:\Users\Me\Miniconda3\envs\test-env:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
argh                      0.26.2          pyh9f0ad1d_1002    conda-forge
astroid                   2.4.2            py37hc8dfbb8_1    conda-forge
async_generator           1.10                       py_0    conda-forge
atomicwrites              1.4.0              pyh9f0ad1d_0    conda-forge
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
autopep8                  1.5.4              pyh9f0ad1d_0    conda-forge
babel                     2.9.0              pyhd3deb0d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
bcrypt                    3.2.0            py37h4ab8f01_1    conda-forge
black                     20.8b1                     py_1    conda-forge
bleach                    3.2.1              pyh9f0ad1d_0    conda-forge
brotlipy                  0.7.0           py37h0013d47_1001    conda-forge
ca-certificates           2020.12.5            h5b45459_0    conda-forge
certifi                   2020.12.5        py37h03978a9_1    conda-forge
cffi                      1.14.4           py37hd8e9650_1    conda-forge
chardet                   4.0.0            py37h03978a9_1    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
cloudpickle               1.6.0                      py_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
cryptography              3.3.1            py37hd8e9650_0    conda-forge
dataclasses               0.7                pyhb2cacf7_7    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
diff-match-patch          20200713           pyh9f0ad1d_0    conda-forge
docutils                  0.16             py37h03978a9_3    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
flake8                    3.8.4                      py_0    conda-forge
future                    0.18.2           py37h03978a9_3    conda-forge
helpdev                   0.7.1              pyhd8ed1ab_0    conda-forge
icu                       64.2                 he025d50_1    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
importlib-metadata        3.3.0            py37h03978a9_3    conda-forge
importlib_metadata        3.3.0                hd8ed1ab_3    conda-forge
intervaltree              3.0.2                      py_0    conda-forge
ipykernel                 5.4.2            py37h7b7c402_0    conda-forge
ipython                   7.19.0           py37heaed05f_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
isort                     5.7.0              pyhd8ed1ab_0    conda-forge
jedi                      0.17.2           py37h03978a9_1    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
jpeg                      9d                   h8ffe710_0    conda-forge
jsonschema                3.2.0                      py_2    conda-forge
jupyter_client            6.1.11             pyhd8ed1ab_0    conda-forge
jupyter_core              4.7.0            py37h03978a9_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
keyring                   21.8.0           py37h03978a9_0    conda-forge
lazy-object-proxy         1.4.3            py37h4ab8f01_2    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libspatialindex           1.9.3                he025d50_3    conda-forge
markupsafe                1.1.1            py37hcc03f2d_3    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.4           py37hcc03f2d_1003    conda-forge
mypy_extensions           0.4.3            py37h03978a9_3    conda-forge
nbclient                  0.5.1                      py_0    conda-forge
nbconvert                 6.0.7            py37h03978a9_3    conda-forge
nbformat                  5.0.8                      py_0    conda-forge
nest-asyncio              1.4.3              pyhd8ed1ab_0    conda-forge
numpydoc                  1.1.0                      py_1    conda-forge
openssl                   1.1.1i               h8ffe710_0    conda-forge
packaging                 20.8               pyhd3deb0d_0    conda-forge
pandoc                    2.11.3.2             h8ffe710_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
paramiko                  2.7.2              pyh9f0ad1d_0    conda-forge
parso                     0.7.0              pyh9f0ad1d_0    conda-forge
pathspec                  0.8.1              pyhd3deb0d_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pip                       20.3.3           py37haa95532_0
pluggy                    0.13.1           py37hf50a25e_3    conda-forge
prompt-toolkit            3.0.10             pyha770c72_0    conda-forge
psutil                    5.8.0            py37hcc03f2d_1    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pycodestyle               2.6.0              pyh9f0ad1d_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pydocstyle                5.1.1                      py_0    conda-forge
pyflakes                  2.2.0              pyh9f0ad1d_0    conda-forge
pygments                  2.7.3              pyhd8ed1ab_0    conda-forge
pylint                    2.6.0            py37hc8dfbb8_1    conda-forge
pyls-black                0.4.6              pyh9f0ad1d_0    conda-forge
pyls-spyder               0.3.0              pyhd8ed1ab_0    conda-forge
pynacl                    1.4.0            py37h230ea1a_2    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.9.2            py37h6538335_4    conda-forge
pyrsistent                0.17.3           py37hcc03f2d_2    conda-forge
pysocks                   1.7.1            py37hf50a25e_2    conda-forge
python                    3.7.9                h60c2a47_0
python-dateutil           2.8.1                      py_0    conda-forge
python-jsonrpc-server     0.4.0              pyh9f0ad1d_0    conda-forge
python-language-server    0.36.2             pyhd8ed1ab_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.5             pyhd8ed1ab_0    conda-forge
pywin32                   228              py37hcc03f2d_1    conda-forge
pywin32-ctypes            0.2.0           py37h03978a9_1003    conda-forge
pyyaml                    5.3.1            py37hcc03f2d_2    conda-forge
pyzmq                     20.0.0           py37h0d95fc2_1    conda-forge
qdarkstyle                2.8.1              pyhd8ed1ab_2    conda-forge
qt                        5.9.7                h506e8af_3    conda-forge
qtawesome                 1.0.2              pyhd8ed1ab_0    conda-forge
qtconsole                 5.0.1              pyhd8ed1ab_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
regex                     2020.11.13       py37hcc03f2d_1    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
rope                      0.18.0             pyh9f0ad1d_0    conda-forge
rtree                     0.9.7            py37h13cc57e_1    conda-forge
setuptools                51.0.0           py37haa95532_2
sip                       4.19.8          py37h6538335_1000    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snowballstemmer           2.0.0                      py_0    conda-forge
sortedcontainers          2.3.0              pyhd8ed1ab_0    conda-forge
sphinx                    3.4.3              pyhd8ed1ab_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.3                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.4                      py_0    conda-forge
spyder                    4.2.1            py37h03978a9_0    conda-forge
spyder-kernels            1.10.1           py37h03978a9_0    conda-forge
sqlite                    3.33.0               h2a8f88b_0
testpath                  0.4.4                      py_0    conda-forge
textdistance              4.2.0              pyhd8ed1ab_0    conda-forge
three-merge               0.1.1              pyh9f0ad1d_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tornado                   6.1              py37hcc03f2d_1    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
typed-ast                 1.4.2            py37hcc03f2d_0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
ujson                     4.0.1            py37hf2a7229_2    conda-forge
urllib3                   1.26.2             pyhd8ed1ab_0    conda-forge
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
watchdog                  1.0.2            py37h03978a9_1    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.36.2             pyhd3eb1b0_0
win_inet_pton             1.1.0            py37h03978a9_2    conda-forge
wincertstore              0.2                      py37_0
wrapt                     1.11.2           py37h4ab8f01_1    conda-forge
yaml                      0.2.5                he774522_0    conda-forge
yapf                      0.30.0             pyh9f0ad1d_0    conda-forge
zeromq                    4.3.3                h0e60522_3    conda-forge
zipp                      3.4.0                      py_0    conda-forge
zlib                      1.2.11               h62dcd97_4
```
So, I agree that it could be an installation issue.  The problem also occurs in the following environment with mixed package repos:
```

> conda list
# packages in environment at C:\Users\Me\Miniconda3\envs\forge37:
#
# Name                    Version                   Build  Channel
_tflow_select             2.3.0                     eigen
absl-py                   0.11.0             pyhd3eb1b0_1
aiohttp                   3.7.3            py37hcc03f2d_0    conda-forge
alabaster                 0.7.12                   py37_0
anyio                     2.0.2            py37h03978a9_3    conda-forge
appdirs                   1.4.4                      py_0
argh                      0.26.2                   py37_0
argon2-cffi               20.1.0           py37he774522_1
astroid                   2.4.2                    py37_0
astunparse                1.6.3                      py_0
async-timeout             3.0.1                    py37_0
async_generator           1.10             py37h28b3542_0
atomicwrites              1.4.0                      py_0
attrs                     20.3.0             pyhd3eb1b0_0
autopep8                  1.5.4                      py_0
babel                     2.9.0              pyhd3eb1b0_0
backcall                  0.2.0                      py_0
bcrypt                    3.2.0            py37he774522_0
beautifulsoup4            4.9.3              pyhb0f4dca_0
black                     20.8b1                     py_1    conda-forge
bleach                    3.2.1                      py_0
blinker                   1.4                      py37_0
blosc                     1.21.0               h0e60522_0    conda-forge
bokeh                     2.2.3                    py37_0
branca                    0.4.2              pyhd8ed1ab_0    conda-forge
brotlipy                  0.7.0           py37h2bbff1b_1003
bs4                       4.9.3                         0
bzip2                     1.0.8                he774522_0
ca-certificates           2020.12.8            haa95532_0
cachetools                4.2.0              pyhd3eb1b0_0
cairo                     1.16.0            hd28d34b_1006    conda-forge
certifi                   2020.12.5        py37haa95532_0
cffi                      1.14.4           py37hcd4344a_0
cfitsio                   3.470                he774522_6
chardet                   3.0.4           py37haa95532_1003
click                     7.1.2                      py_0
click-plugins             1.1.1                      py_0
cligj                     0.7.1            py37haa95532_0
cloudpickle               1.6.0                      py_0
colorama                  0.4.4              pyhd3eb1b0_0
cryptography              3.3.1            py37hcd4344a_0
curl                      7.71.1               h4b64cdc_8    conda-forge
cycler                    0.10.0                   py37_0
cytoolz                   0.11.0           py37he774522_0
dask-core                 2020.12.0          pyhd3eb1b0_0
dataclasses               0.7                      py37_0
decorator                 4.4.2                      py_0
defusedxml                0.6.0                      py_0
descartes                 1.1.0                      py_4
diff-match-patch          20200713                   py_0
docutils                  0.16                     py37_1
entrypoints               0.3                      py37_0
expat                     2.2.10               h33f27b4_2
fiona                     1.8.18           py37hc779931_0    conda-forge
flake8                    3.8.4                      py_0
folium                    0.12.0             pyhd8ed1ab_0    conda-forge
freetype                  2.10.4               hd328e21_0
freexl                    1.0.6                h2bbff1b_0
future                    0.18.2                   py37_1
fuzzywuzzy                0.18.0             pyhd8ed1ab_0    conda-forge
gast                      0.3.3                      py_0
gdal                      3.1.4            py37hebdd5d2_0    conda-forge
geopandas                 0.8.1                      py_0
geos                      3.8.1                h33f27b4_0
geotiff                   1.6.0                h8884d1a_3    conda-forge
gettext                   0.19.8.1          h1a89ca6_1005    conda-forge
glib                      2.66.4               he2d232f_1    conda-forge
google-auth               1.24.0             pyhd3eb1b0_0
google-auth-oauthlib      0.4.1                      py_2    conda-forge
google-pasta              0.2.0                      py_0
graphviz                  2.38                 hfd603c8_2
grpcio                    1.34.0           py37h04d2302_1    conda-forge
h5py                      2.10.0          nompi_py37h23cfb99_105    conda-forge
hdf4                      4.2.13               h712560f_2
hdf5                      1.10.6          nompi_h5268f04_1114    conda-forge
icu                       67.1                 h33f27b4_0    conda-forge
idna                      2.10                       py_0
imageio                   2.9.0                      py_0
imagesize                 1.2.0                      py_0
importlib-metadata        3.3.0            py37h03978a9_3    conda-forge
importlib_metadata        3.3.0                hd8ed1ab_3    conda-forge
intel-openmp              2020.3             h57928b3_311    conda-forge
intervaltree              3.1.0                      py_0
ipykernel                 5.4.2            py37h7b7c402_0    conda-forge
ipympl                    0.6.2              pyhd8ed1ab_0    conda-forge
ipython                   7.19.0           py37hd4e2768_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
ipywidgets                7.6.3              pyhd3eb1b0_0
isort                     5.7.0              pyhd8ed1ab_0    conda-forge
jedi                      0.17.2           py37haa95532_1
jellyfish                 0.8.2                    pypi_0    pypi
jinja2                    2.11.2                     py_0
joblib                    1.0.0              pyhd3eb1b0_0
jpeg                      9d                   h8ffe710_0    conda-forge
json5                     0.9.5                      py_0
jsonschema                3.2.0                      py_2
jupyter_client            6.1.11             pyhd8ed1ab_0    conda-forge
jupyter_core              4.7.0            py37haa95532_0
jupyter_server            1.2.1            py37h03978a9_0    conda-forge
jupyterlab                3.0.3              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.1.2                      py_0
jupyterlab_server         2.1.1              pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1
jupyterthemes             0.20.0                     py_1    conda-forge
kealib                    1.4.14               ha3510f1_0    conda-forge
keras-applications        1.0.8                      py_1
keras-preprocessing       1.1.0                      py_1
keyring                   21.8.0           py37haa95532_0
kiwisolver                1.3.1            py37h8c56517_1    conda-forge
krb5                      1.17.2               hbae68bd_0    conda-forge
lazy-object-proxy         1.4.3            py37h2bbff1b_2
lesscpy                   0.13.0                     py_1    conda-forge
libblas                   3.9.0                     7_mkl    conda-forge
libboost                  1.67.0               hd9e427e_4
libcblas                  3.9.0                     7_mkl    conda-forge
libclang                  10.0.1          default_hf44288c_1    conda-forge
libcurl                   7.71.1               h4b64cdc_8    conda-forge
libffi                    3.3                  h0e60522_2    conda-forge
libgdal                   3.1.4                h0e5aa5a_0    conda-forge
libglib                   2.66.4               h5320221_1    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
libkml                    1.3.0                he5f2a48_4
liblapack                 3.9.0                     7_mkl    conda-forge
libnetcdf                 4.7.4           nompi_h3a9aa94_107    conda-forge
libpng                    1.6.37               h2a8f88b_0
libpq                     12.3                 h4f54205_3    conda-forge
libprotobuf               3.14.0               h23ce68f_0
libsodium                 1.0.18               h62dcd97_0
libspatialindex           1.9.3                h33f27b4_0
libspatialite             5.0.0                hf693123_0    conda-forge
libssh2                   1.9.0                h7a1dbc1_1
libtiff                   4.2.0                hc10be44_0    conda-forge
libwebp-base              1.1.0                he774522_3
libxml2                   2.9.10               hb89e7f3_3
libxslt                   1.1.34               he774522_0
lxml                      4.6.2            py37h9b66d53_0
lz4-c                     1.9.3                h8ffe710_0    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markdown                  3.3.3            py37haa95532_0
markupsafe                1.1.1            py37hfa6e2cd_1
matplotlib                3.3.3            py37h03978a9_0    conda-forge
matplotlib-base           3.3.3            py37h3379fd5_0    conda-forge
mccabe                    0.6.1                    py37_1
mistune                   0.8.4           py37hfa6e2cd_1001
mkl                       2020.4             hb70f87d_311    conda-forge
mock                      4.0.3              pyhd3eb1b0_0
more-itertools            8.6.0              pyhd3eb1b0_0
msys2-conda-epoch         20160418                      1
multidict                 5.1.0            py37h2bbff1b_2
munch                     2.5.0                      py_0
mypy_extensions           0.4.3                    py37_0
nbclassic                 0.2.5              pyhd8ed1ab_0    conda-forge
nbclient                  0.5.1                      py_0
nbconvert                 6.0.7                    py37_0
nbformat                  5.0.8                      py_0
nest-asyncio              1.4.3              pyhd3eb1b0_0
networkx                  2.5                        py_0
nltk                      3.5                        py_0
nodejs                    15.3.0               h57928b3_0    conda-forge
notebook                  6.1.6            py37haa95532_0
numexpr                   2.7.2            py37h08fd248_0    conda-forge
numpy                     1.19.5           py37hd20adf4_0    conda-forge
numpydoc                  1.1.0              pyhd3eb1b0_1
nxviz                     0.6.2            py37h03978a9_2    conda-forge
oauthlib                  3.1.0                      py_0
olefile                   0.46                     py37_0
openjpeg                  2.3.1                h48faf41_3    conda-forge
openssl                   1.1.1i               h2bbff1b_0
opt_einsum                3.3.0                      py_0    conda-forge
packaging                 20.8               pyhd3eb1b0_0
palettable                3.3.0                      py_0
pandas                    1.2.0            py37hf11a4ad_0
pandoc                    2.11.3.2             h8ffe710_0    conda-forge
pandocfilters             1.4.3            py37haa95532_1
paramiko                  2.7.2                      py_0
parso                     0.7.0                      py_0
pathspec                  0.8.1              pyhd3deb0d_0    conda-forge
patsy                     0.5.1                    py37_0
pcre                      8.44                 ha925a31_0
pendulum                  2.1.2              pyhd3eb1b0_1
pexpect                   4.8.0              pyhd3eb1b0_3
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    8.1.0            py37h4fa10fc_0
pip                       20.3.3           py37haa95532_0
pixman                    0.40.0               he774522_0
plotly                    4.14.1             pyhd3eb1b0_0
pluggy                    0.13.1                   py37_0
ply                       3.11                     py37_0
pooch                     1.3.0              pyhd8ed1ab_0    conda-forge
poppler                   0.89.0               h5d62644_1    conda-forge
poppler-data              0.4.10                        0    conda-forge
postgresql                12.3                 h0f1a9bc_3    conda-forge
proj                      7.1.1                h7d85306_3    conda-forge
prometheus_client         0.9.0              pyhd3eb1b0_0
prompt-toolkit            3.0.10             pyha770c72_0    conda-forge
protobuf                  3.14.0           py37hf2a7229_1    conda-forge
psutil                    5.8.0            py37hcc03f2d_1    conda-forge
ptyprocess                0.7.0              pyhd3eb1b0_2
pyasn1                    0.4.8                      py_0
pyasn1-modules            0.2.8                      py_0
pycodestyle               2.6.0                      py_0
pycparser                 2.20                       py_2
pydocstyle                5.1.1                      py_0
pyflakes                  2.2.0                      py_0
pygments                  2.7.3              pyhd3eb1b0_0
pyjwt                     2.0.0              pyhd8ed1ab_0    conda-forge
pylint                    2.6.0                    py37_0
pyls-black                0.4.6                hd3eb1b0_0
pyls-spyder               0.3.0              pyhd3eb1b0_0
pynacl                    1.4.0            py37h62dcd97_1
pyopenssl                 20.0.1             pyhd3eb1b0_1
pyparsing                 2.4.7                      py_0
pyproj                    2.6.1.post1      py37he3b39cb_3    conda-forge
pyqt                      5.12.3           py37h03978a9_6    conda-forge
pyqt-impl                 5.12.3           py37hf2a7229_6    conda-forge
pyqt5-sip                 4.19.18          py37hf2a7229_6    conda-forge
pyqtchart                 5.12             py37hf2a7229_6    conda-forge
pyqtwebengine             5.12.1           py37hf2a7229_6    conda-forge
pyreadline                2.1                      py37_1
pyreadstat                1.0.8            py37h5b38b69_0    conda-forge
pyrsistent                0.17.3           py37he774522_0
pysocks                   1.7.1                    py37_1
pytables                  3.6.1            py37hdc91d43_3    conda-forge
python                    3.7.9                h60c2a47_0
python-dateutil           2.8.1                      py_0
python-graphviz           0.16               pyhd3deb0d_1    conda-forge
python-jsonrpc-server     0.4.0                      py_0
python-language-server    0.36.2             pyhd3eb1b0_0
python-levenshtein        0.12.0          py37he774522_1001
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.5             pyhd3eb1b0_0
pytzdata                  2020.1                     py_0
pywavelets                1.1.1            py37he774522_2
pywin32                   228              py37hcc03f2d_1    conda-forge
pywin32-ctypes            0.2.0                 py37_1001
pywinpty                  0.5.7                    py37_0
pyyaml                    5.3.1            py37he774522_1
pyzmq                     20.0.0           py37hd77b12b_1
qdarkstyle                2.8.1                      py_0
qt                        5.12.9               hb2cf2c5_0    conda-forge
qtawesome                 1.0.2              pyhd8ed1ab_0    conda-forge
qtconsole                 5.0.1              pyhd8ed1ab_0    conda-forge
qtpy                      1.9.0                      py_0
recordlinkage             0.14                     pypi_0    pypi
regex                     2020.11.13       py37h2bbff1b_0
requests                  2.25.1             pyhd3eb1b0_0
requests-oauthlib         1.3.0                      py_0
retrying                  1.3.3                    py37_2
rope                      0.18.0                     py_0
rsa                       4.6                        py_0
rtree                     0.9.7            py37h13cc57e_1    conda-forge
scikit-image              0.18.1           py37h08fd248_0    conda-forge
scikit-learn              0.24.0           py37heb15398_0    conda-forge
scipy                     1.6.0            py37h6db1a17_0    conda-forge
seaborn                   0.11.1             pyhd3eb1b0_0
send2trash                1.5.0              pyhd3eb1b0_1
setuptools                51.0.0           py37haa95532_2
shapely                   1.7.1            py37h82f916b_1    conda-forge
six                       1.15.0           py37haa95532_0
sklearn-pandas            2.0.3                    pypi_0    pypi
sniffio                   1.2.0            py37h03978a9_0    conda-forge
snowballstemmer           2.0.0                      py_0
sortedcontainers          2.3.0              pyhd3eb1b0_0
soupsieve                 2.1                pyhd3eb1b0_0
sphinx                    3.4.3              pyhd3eb1b0_0
sphinxcontrib-applehelp   1.0.2                      py_0
sphinxcontrib-devhelp     1.0.2                      py_0
sphinxcontrib-htmlhelp    1.0.3                      py_0
sphinxcontrib-jsmath      1.0.1                      py_0
sphinxcontrib-qthelp      1.0.3                      py_0
sphinxcontrib-serializinghtml 1.1.4                      py_0
spyder                    4.2.1            py37h03978a9_0    conda-forge
spyder-kernels            1.10.1           py37haa95532_0
sqlalchemy                1.3.22           py37hcc03f2d_1    conda-forge
sqlite                    3.34.0               h8ffe710_0    conda-forge
statsmodels               0.12.1           py37h2bbff1b_0
tensorboard               2.4.0              pyhd8ed1ab_0    conda-forge
tensorboard-plugin-wit    1.7.0              pyh9f0ad1d_0    conda-forge
tensorflow                2.3.0           mkl_py37h04bc1aa_0
tensorflow-base           2.3.0           eigen_py37h17acbac_0
tensorflow-estimator      2.3.0              pyheb71bc4_0
termcolor                 1.1.0                    py37_1
terminado                 0.9.2            py37haa95532_0
testpath                  0.4.4                      py_0
textdistance              4.2.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0
three-merge               0.1.1              pyhd3eb1b0_0
tifffile                  2020.10.1        py37h8c2d366_2
tiledb                    2.1.6                hf84e3da_1    conda-forge
tk                        8.6.10               he774522_0
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
toolz                     0.11.1                     py_0
tornado                   6.1              py37h2bbff1b_0
tqdm                      4.55.1             pyhd3eb1b0_0
traitlets                 5.0.5                      py_0
tweepy                    3.10.0             pyhd8ed1ab_0    conda-forge
typed-ast                 1.4.2            py37hcc03f2d_0    conda-forge
typing-extensions         3.7.4.3                       0
typing_extensions         3.7.4.3                    py_0
ujson                     4.0.1            py37ha925a31_0
urllib3                   1.26.2             pyhd3eb1b0_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.28.29325          h5e1d092_0    conda-forge
watchdog                  1.0.2            py37h03978a9_1    conda-forge
wcwidth                   0.2.5                      py_0
webencodings              0.5.1                    py37_1
werkzeug                  1.0.1                      py_0
wheel                     0.36.2             pyhd3eb1b0_0
widgetsnbextension        3.5.1                    py37_0
win_inet_pton             1.1.0            py37haa95532_0
wincertstore              0.2                      py37_0
winpty                    0.4.3                         4
wrapt                     1.11.2           py37he774522_0
xerces-c                  3.2.3                ha925a31_0
xgboost                   1.3.0.post0              pypi_0    pypi
xlrd                      2.0.1              pyhd3eb1b0_0
xz                        5.2.5                h62dcd97_0
yaml                      0.2.5                he774522_0
yapf                      0.30.0                     py_0
yarl                      1.6.3            py37h2bbff1b_0
zeromq                    4.3.3                ha925a31_3
zipp                      3.4.0              pyhd3eb1b0_0
zlib                      1.2.11               h62dcd97_4
zstd                      1.4.8                h4e2f164_1    conda-forge
```
This issue has never occurred before in my forge37 mixed env with spyder, so it's something new in spyder 4.2.1.

**Comment by manfred2020** [comment]
my rtree version 0.9.7 is py37h13cc57e_1

what about my above posting on "spatialindex_c-64.dll"? because since then i did not have the spyder/rtree problem anymore. how is that related?

**Comment by ccordoba12** [comment]
@pythonic2020, I figured mixing packages from different providers (in your case, defaults and conda-forge) was the cause of this.

@manfred2020, I guess you installed geopandas with pip or conda-forge and that caused the error.

**Comment by ccordoba12** [comment]
@dalthviz, what do you think we should do about this?

**Comment by dalthviz** [comment]
@ccordoba12 an option to prevent the dialog appearing is to leave the required version set to `None`, right? (not properly a fix but will prevent the annoying user with the dialog). Otherwise we will need to check why the version is not being detected if the package comes from a different channel (not sure at all why that's happening :/)

**Comment by ccordoba12** [comment]
Even if we set the version to `None`, I think the dialog is correctly reporting that `rtree` is missing. At least that's what I understand from the initial screenshot because in previous Spyder versions we reported the version as `None` but put an `Ok` next to it.

And that's probably the case because Spyder is unable to import `rtree` due to mixing conda, conda-forge and/or pip packages. So perhaps we should leave things as they are?

**Comment by dalthviz** [comment]
I think that we need to check why that's happening then. I guess the package version detection logic should handle such situation otherwise this kind of issue probably could happen again with other packages or dependencies, right? Maybe we could improve the dialog and guide users to understand better their situation (mixed packages for example) and also maybe then add a way to dismiss the dialog for future sessions.

**Comment by ccordoba12** [comment]
In the case of @pythonic2020, these are the packages for the environment where the error is displayed:

    libspatialindex           1.9.3                h33f27b4_0
    rtree                     0.9.7            py37h13cc57e_1    conda-forge

(`libspatialindex` is a dependency of `rtree`). So @pythonic2020 is mixing those packages from different channels, which seems to be the cause of the error.

I can't say what happens exactly for @manfred2020, but it seems to be caused by installing `geopandas` (or `rtree`?) with pip.

**Comment by manfred2020** [comment]
i installed geopandas - like 99,9% of my packages - with conda-forge.

my original question was: why is it, that the spyder message about rtree disapears, when i copy "spatialindex_c-64.dll" into the rtree folder. this originally was a tipp to solve an error with a geopandas script. like i wrote above...

**Comment by pythonic2020** [comment]
It's interesting that libspatialindex is somehow involved in both my error and manfred's case...

**Comment by dalthviz** [comment]
@manfred2020 the message appears because Spyder is unable to import rtree and detect is version (I think, right @ccordoba12 ?) which maybe is being fixed in your case by adding the missing `.dll` you mentioned.

@pythonic2020 yep that's what I was thinking. Probably a way to understand better where the error happens is to check if any error/traceback is shown if you try to import `rtree` in the IPython Console.

Maybe a faulty installation of `libspatialindex` could be causing the issue? Maybe importing `rtree` will show an error regarding a missing `.dll`? Could you guys check? Thanks!

**Comment by pythonic2020** [comment]
I my monster forge37 environment, if I try to import rtree I get:

`OSError: could not find or load spatialindex_c-64.dll`

I also get that error if I import rtree in spyder.  The error occurs after I installed libspatialindex from conda-forge.

**Comment by dalthviz** [comment]
Something to try (hopefully in an env that you don't care discard later if something goes wrong!):
- Do `pip list` and `conda list`. Check if different versions are listed for `rtree` (if that's the case maybe multiple version of the same package were installed in the same env).
- Try to uninstall `rtree` using `conda` and then `pip`.
- Reinstall `rtree` using `conda`.

**Comment by pythonic2020** [comment]
Ha!  I just ran geopandas functions in my forge37 env, and got the same error.  Looks like manfred and I are in the same boat.  I think some package updates other than spyder have screwed up libspatialindex and thus rtree.  At this point this doesn't look like a spyder problem.

**Comment by dalthviz** [comment]
Thanks for the feedback @pythonic2020 ! For now then I will mark this as not related with Spyder but if you guys manage to get a root cause leave a comment here (probably other users could face a similar issue regarding `rtree` and a faulty installation of packages)

**Comment by pythonic2020** [comment]
The simplest solution to this non-spyder issue is what manfred suggested above about copying the dll...

**Comment by ccordoba12** [comment]
I completely disagree @pythonic2020, that's hacky and it won't survive a `conda update`.

The simplest solution is to create a Conda-forge environment with Geopandas and the other packages you want to use from it, but not Spyder. Then you need to connect that env to the Spyder version installed in the `base` env by following the instructions in this [FAQ](http://docs.spyder-ide.org/current/faq.html#using-existing-environment),

Or, if you want to use Spyder in the same env than Geopandas, you need to install everything from Conda-forge (i.e. Geopandas and Spyder).

Any of those solutions will avoid mixing the Conda-forge and defaults channels. If you insist on doing that, not only this but other odd errors will certainly appear.

**Comment by pythonic2020** [comment]
Yes, manfred's solution is hacky and not recommended, but it solves all problems in a few seconds.  At this point I don't care about using spyder in the env (and can change the spyder default env as stated in your FAQ).  That py37 env has never had a problem with mixed packages before.  But I do need a functioning geopandas, which is currently hosed because of that missing dll.  Hopefully the rtree people (and/or others) will fix this issue moving forward.  

It will be nasty if I get this problem in a py3.8 env using flexible channel priority and conda-forge #1 priority and pkgs/main #2 priority.  That is my main env which functions perfectly, albeit with spyder 4.2.0.

**Comment by pythonic2020** [comment]
Well, feeling guilty about my operational, yet hacked, environment, I gave in and made a new monster py37 environment using flexible channel priority and conda-forge #1 priority and pkgs/main #2 priority.  Spyder 4.2.1 and geopandas work fine together with no errors.

**Comment by dalthviz** [comment]
Glad to hear that you managed to get everything working @pythonic2020 ! I'm closing this issue then

**Comment by Samk19** [comment]
Got few solutions
FOR LINUX (tested and worked): sudo apt install libspatialindex-dev
FOR MAC: brew install spatialindex

still not sure if its a permanent fix or not

after using above command (i.e linux one).....spyder rtree error message gone

![Screenshot from 2021-03-06 23-56-45](https://user-images.githubusercontent.com/36104528/110217023-e3367f00-7ed7-11eb-99a9-4146d4505a72.png)

**Comment by sweettyler** [comment]
With the latest Spyder 4.2.3, which has been included in the latest Anaconda (run conda update --all, for example, to get it), I still have this problem. I think the problem is on the Spyder side, because when I run "conda list rtree" it appears there.

I am not sure if the problem has anything to do with Python 3.8.8 (you can get it by update Anaconda version 2020.11 to the latest by runing "conda update --all"). I see a lot discussion above talking about setting an environment of Python 3.7.9 and saying Spyder worked well in that environment. This proves SPyder worked, but doesn't necessarily mean Spyder works well now with Python 3.8.8.

**Comment by stephenhallfr** [comment]
> The problem was caused by python 3.8.8. After downgrading python from 3.8.8 to 3.8.5, the error went away.

This worked for me.
For some reason it  took the rtree of the base and not the one for env......

**Comment by stragu** [comment]
@Samk19 thank you, installing `libspatialindex-dev` worked on Ubuntu 18.04, at least for the `rtree` issue!

However, I'm left with the brand new `qtconsole >=5.0.3 : 5.0.2 (NOK)` missing dependency... (using Python 3.8.8 with Anaconda currently, Spyder 4.2.4) – which I assume will be solved as [Anaconda makes a more recent version available](https://anaconda.org/anaconda/qtconsole).

**Comment by archaeologicalglove** [comment]
I guess this is closed now, but this seems to be a solution: 

conda install -c conda-forge/label/cf202003 rtree

https://anaconda.org/conda-forge/rtree

**Comment by ifariasg** [comment]
I also wanted to follow up on this. I created a fresh python 3.9 environment using only conda-forge as a channel and still get this issue with rtree and spyder 5.0.1

**Comment by 24Beast** [comment]
> yes, version 0.9.7.
> 
> but... i had a completely different experience a few days ago:
> 
> i had some problems with a script that uses geopandas. error message was, that "spatialindex_c-64.dll" could not be found ("OSError: could not find or load spatialindex_c-64.dll"). (my script worked all the weeks before, i don't know what happened).
> 
> so i searched the internet and one tipp was to copy the dll file (which existed in folder "...\anaconda3\Library\bin") to the folder "...\anaconda3\envs\MyEnvironmentName\Lib\site-packages\rtree".
> 
> since then everything worked as before, my geopandas script works and spyder 4.2.1 works, no more rtree message.
> 
> what's your opinion on that?
> 
> to me it seems that updating to spyder 4.2.1 caused the geopandas script error message (script worked before the update).

This worked for me as well and I have 
rtree                     0.9.7            py37h13cc57e_1    conda-forge

So, I guess one should probably use this solution.

**Comment by lucianoserafim** [comment]
I was having the same problem. Before I used spyder4 and when I installed spyder5 the problem came,

# Mandatory
rtree >= 0.9.7 : None (NOK)

 I use Debian Buster and I solved it like that, 

sudo apt-get install libspatialindex-dev

**Comment by glefebvr** [comment]
Same problem also for me, with spyder 5.0.3 with the message: "Mandatory rtree >= 0.9.7 : None (NOK)).", but rtree 0.9.7 is installed. 

```
conda list rtree
# packages in environment at C:\ProgramData\Anaconda3:
#
# Name                    Version                   Build  Channel
rtree                     0.9.7            py37h13cc57e_1    conda-forge
```

Moreover, in the Ipython console, if I do
`import rtree`
an error on the DLL spatialindex_c is raised.

So following [https://github.com/spyder-ide/spyder/issues/14466#issuecomment-756499870](the suggestion of manfred2020), I have not copy the full directory "...\anaconda3\Library\bin", because this content is bigger than 1Go in my case, but I have copy only spatialindex_c-64.dll and spatialindex-64.dll.
If you have the problem in a conda environment, destination folder is "...\anaconda3\envs\MyEnvironmentName\Lib\site-packages\rtree", otherwise destination folder is "...\anaconda3\Lib\site-packages\rtree".

In my case, just copy these 2 files works fine.

Hope it is helpfull.

**Comment by lwbaqueros** [comment]
Same issue under Windows and Spyder 5.0.5. As reported by @glefebvr I just copy `spatialindex_c-64.dll` and `spatialindex-64.dll` to `\site-packages\rtree` and the message disappears.

**Comment by vivigb** [comment]
> yes, version 0.9.7.
> 
> but... i had a completely different experience a few days ago:
> 
> i had some problems with a script that uses geopandas. error message was, that "spatialindex_c-64.dll" could not be found ("OSError: could not find or load spatialindex_c-64.dll"). (my script worked all the weeks before, i don't know what happened).
> 
> so i searched the internet and one tipp was to copy the dll file (which existed in folder "...\anaconda3\Library\bin") to the folder "...\anaconda3\envs\MyEnvironmentName\Lib\site-packages\rtree".
> 
> since then everything worked as before, my geopandas script works and spyder 4.2.1 works, no more rtree message.
> 
> what's your opinion on that?
> 
> to me it seems that updating to spyder 4.2.1 caused the geopandas script error message (script worked before the update).

Try this; This will work. Just copy the respective dll file to the directory,which is mentioned in the error message

**Comment by Alex-Bujorianu** [comment]
I can confirm that this bug affects the Linux build as well. Installing Spyder in a venv also raises this error about missing `rtree`, but pip confirms that it is installed. The version of Spyder on the Manjaro repositories is completely broken.

**Comment by ccordoba12** [comment]
> Installing Spyder in a venv also raises this error about missing rtree, but pip confirms that it is installed

This is a problem with the way Rtree tries to load the compiled library it depends on. I think it's going to be fixed in its next release, but for now there's nothing we can do about it.

> The version of Spyder on the Manjaro repositories is completely broken.

That's almost always the case, so please stop using the Manjaro/Arch Spyder packages. Furthermore, if you could let their maintainers know that that's the case and they should distributing Spyder, you'd us a great favor.

So, for now, the only workaround is to use Conda-forge to install Spyder, after installing Miniconda. Let us know if you need instructions on how to do that.
