### ISSUE TITLE
Remote Kernel Connection Hangs when Attempting to Connect Mac to Windows10

### ISSUE THREAD

**Issue by bdeshon** [spyder-ide/spyder#15616]
### Issue Report Checklist

* [x ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ x] Tried basic troubleshooting (if a bug/error)
    * [x ] Restarted Spyder
    * [ x] Reset preferences with ``spyder --reset``
    * [ x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ x] Tried the other applicable steps from the Troubleshooting Guide
* [ x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I have a windows 10 remote server that I use for compute power.  I am attempting to connect Spyder to that on my Mac.  I have followed the instructions on the docs site (https://docs.spyder-ide.org/current/panes/ipythonconsole.html#connect-to-a-remote-kernel).

Steps:
1. I start a kernel on my remote using python -m spyder_kernels.console
2. I find the kernel json file in this location jupyter/runtime/dir/path
3. I copy the kernel json file from my remote to my local
4. I start Spyder and go to 'connect to existing kernal'
5. I point to the connection file and enter my remote server information

<img width="630" alt="image" src="https://user-images.githubusercontent.com/36005411/118139991-8f5f7f00-b3cd-11eb-904b-fd286c7f33f8.png">

<img width="559" alt="image" src="https://user-images.githubusercontent.com/36005411/118138702-40fdb080-b3cc-11eb-9e2f-22467bce1f21.png">

### What steps reproduce the problem?

1. Same as the steps above

### What is the expected output? What do you see instead?
Expected output is to connect to the remote kernel however, my kernel pane just keeps hanging saying 'Connecting to Kernel while the output in my console shows below:

`(spyder-env) ➜  ~ spyder
No QCoreApplication instance found. Application patches not applied. You have to call load_stylesheet function after instantiation of QApplication to take effect.
WARNING:traitlets:kernel died: 3.0003340244293213
WARNING:traitlets:kernel died: 3.00295090675354
WARNING:traitlets:kernel died: 2.999500036239624
WARNING:traitlets:kernel died: 3.003519058227539
WARNING:traitlets:kernel died: 3.0012669563293457
WARNING:traitlets:kernel died: 3.0028798580169678`

<img width="904" alt="image" src="https://user-images.githubusercontent.com/36005411/118138607-275c6900-b3cc-11eb-855e-449862120193.png">

## Versions

On Local:
* Spyder version: 5
* Python version: 3.9.4
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: macOS Catalina

One Remote:
* Spyder version: 5
* Python version: 3.7
* Qt version: 5.12.9
* PyQt version: 5.12.3
* Operating System name/version: Windows 10

### Dependencies

On Local:
```
# Mandatory:
applaunchservices >=0.1.7     :  0.2.1 (OK)
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  22.3.0 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.8.3                 :  0.9.7 (OK)
setuptools >=39.0.0           :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                :  4.0.1 (OK)
spyder_kernels >=2.0.1;<2.1.0 :  2.0.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  20.0.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  None (NOK)
numpy >=1.7                   :  None (NOK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

On Remote:
```
# Name                    Version                   Build  Channel
_r-mutex                  1.0.1               anacondar_1    conda-forge
absl-py                   0.10.0                   pypi_0    pypi
aiohttp                   3.7.4            py37hcc03f2d_0    conda-forge
alabaster                 0.7.12                   pypi_0    pypi
alembic                   1.6.2                    pypi_0    pypi
anyio                     3.0.1            py37h03978a9_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
argon2-cffi               20.1.0           py37hcc03f2d_2    conda-forge
astunparse                1.6.3                    pypi_0    pypi
async-timeout             3.0.1                   py_1000    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
autopep8                  1.5.4                    pypi_0    pypi
azure-common              1.1.27             pyhd8ed1ab_0    conda-forge
azure-core                1.12.0             pyhd8ed1ab_0    conda-forge
azure-storage-blob        12.8.1             pyhd8ed1ab_0    conda-forge
babel                     2.9.0                    pypi_0    pypi
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
black                     21.5b0             pyhd8ed1ab_0    conda-forge
bleach                    3.3.0              pyh44b312d_0    conda-forge
blinker                   1.4                        py_1    conda-forge
blosc                     1.21.0               h0e60522_0    conda-forge
bokeh                     2.3.2            py37h03978a9_0    conda-forge
boost-cpp                 1.74.0               h54f0996_2    conda-forge
boto                      2.49.0                     py_0    conda-forge
boto3                     1.17.72            pyhd8ed1ab_0    conda-forge
botocore                  1.20.72            pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                h0e60522_4    conda-forge
brotlipy                  0.7.0           py37hcc03f2d_1001    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2020.12.5            h5b45459_0    conda-forge
cachetools                4.1.1                    pypi_0    pypi
cairo                     1.16.0            hb19e0ff_1008    conda-forge
ceds                      2.3                      pypi_0    pypi
certifi                   2020.12.5        py37h03978a9_1    conda-forge
certipy                   0.1.3                    pypi_0    pypi
cffi                      1.14.5           py37hd8e9650_0    conda-forge
cfitsio                   3.470                h0af3d06_7    conda-forge
chardet                   4.0.0            py37h03978a9_1    conda-forge
charls                    2.2.0                h39d44d4_0    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.1              pyhd8ed1ab_0    conda-forge
cloudpickle               1.6.0                      py_0    conda-forge
cmdstanpy                 0.9.5                    pypi_0    pypi
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
convertdate               2.2.2                    pypi_0    pypi
covidcast                 0.0.9                    pypi_0    pypi
cryptography              3.4.7            py37h20c650d_0    conda-forge
curl                      7.76.1               hf1763fc_1    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.23          py37hf2a7229_0    conda-forge
cytoolz                   0.11.0           py37hcc03f2d_3    conda-forge
dash-cytoscape            0.2.0                    pypi_0    pypi
dask                      2021.4.1           pyhd8ed1ab_0    conda-forge
dask-core                 2021.4.1           pyhd8ed1ab_0    conda-forge
dataclasses               0.8                pyhc8e2a94_1    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
delphi-epidata            0.0.7                    pypi_0    pypi
descartes                 1.1.0                    pypi_0    pypi
dill                      0.3.3                    pypi_0    pypi
distributed               2021.4.1         py37h03978a9_0    conda-forge
docutils                  0.17.1                   pypi_0    pypi
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
ephem                     3.7.7.1                  pypi_0    pypi
et-xmlfile                1.0.1                    pypi_0    pypi
expat                     2.3.0                h39d44d4_0    conda-forge
fbprophet                 0.7.1                    pypi_0    pypi
fiona                     1.8.19           py37ha8636df_0    conda-forge
fontconfig                2.13.1            h1989441_1005    conda-forge
formulas                  1.0.0                    pypi_0    pypi
freetype                  2.10.4               h546665d_1    conda-forge
freexl                    1.0.6                ha8e266a_0    conda-forge
fsspec                    2021.4.0           pyhd8ed1ab_0    conda-forge
gast                      0.3.3                    pypi_0    pypi
gdal                      3.2.2            py37h3a36fe1_3    conda-forge
gensim                    4.0.1            py37hf2a7229_0    conda-forge
geopandas                 0.9.0              pyhd8ed1ab_0    conda-forge
geos                      3.9.1                h39d44d4_2    conda-forge
geotiff                   1.6.0                h8e90983_5    conda-forge
gettext                   0.19.8.1          h1a89ca6_1005    conda-forge
gevent                    21.1.2                   pypi_0    pypi
giflib                    5.2.1                h8d14728_2    conda-forge
google-api-core           1.26.3             pyhd8ed1ab_0    conda-forge
google-auth               1.21.2                   pypi_0    pypi
google-auth-oauthlib      0.4.1                    pypi_0    pypi
google-cloud-core         1.5.0              pyhd3deb0d_0    conda-forge
google-cloud-storage      1.19.0                     py_0    conda-forge
google-crc32c             1.1.2            py37h9049977_0    conda-forge
google-pasta              0.2.0                    pypi_0    pypi
google-resumable-media    1.2.0              pyhd3deb0d_0    conda-forge
googleapis-common-protos  1.53.0           py37h9ae81ce_0    conda-forge
greenlet                  1.0.0                    pypi_0    pypi
grpcio                    1.32.0                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
hdf4                      4.2.13            h0e5069d_1005    conda-forge
hdf5                      1.10.6          nompi_h5268f04_1114    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
holidays                  0.10.3                   pypi_0    pypi
icu                       68.1                 h0e60522_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
imagecodecs               2021.3.31        py37hc6c0c29_0    conda-forge
imageio                   2.9.0                      py_0    conda-forge
imagesize                 1.2.0                    pypi_0    pypi
importlib-metadata        4.0.1            py37h03978a9_0    conda-forge
intel-openmp              2021.2.0           h57928b3_616    conda-forge
interpret                 0.2.4                    pypi_0    pypi
interpret-core            0.2.4                    pypi_0    pypi
ipykernel                 5.5.5                    pypi_0    pypi
ipyparallel               6.3.0            py37h03978a9_2    conda-forge
ipython                   7.23.1           py37h7813e69_0    conda-forge
ipython-genutils          0.2.0                    pypi_0    pypi
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1              pyh9f0ad1d_1    conda-forge
isodate                   0.6.0                      py_1    conda-forge
jdcal                     1.4.1                    pypi_0    pypi
jedi                      0.17.2                   pypi_0    pypi
jinja2                    3.0.0              pyhd8ed1ab_0    conda-forge
jmespath                  0.10.0             pyh9f0ad1d_0    conda-forge
joblib                    0.16.0                   pypi_0    pypi
jpeg                      9d                   h8ffe710_0    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonschema                3.2.0              pyhd8ed1ab_3    conda-forge
jupyter                   1.0.0                    pypi_0    pypi
jupyter-console           6.2.0                    pypi_0    pypi
jupyter-dash              0.4.0                    pypi_0    pypi
jupyter-kite              2.0.2                    pypi_0    pypi
jupyter-packaging         0.7.12                   pypi_0    pypi
jupyter-server            1.4.1                    pypi_0    pypi
jupyter-telemetry         0.1.0                    pypi_0    pypi
jupyter-tensorboard       0.2.0                    pypi_0    pypi
jupyter_client            6.1.12             pyhd8ed1ab_0    conda-forge
jupyter_core              4.7.1            py37h03978a9_0    conda-forge
jupyter_server            1.7.0            py37h03978a9_1    conda-forge
jupyterhub                1.4.1                    pypi_0    pypi
jupyterlab                2.2.8                    pypi_0    pypi
jupyterlab-code-formatter 1.4.4                    pypi_0    pypi
jupyterlab-execute-time   2.0.2                    pypi_0    pypi
jupyterlab-git            0.30.0b2                 pypi_0    pypi
jupyterlab-kite           2.0.2                    pypi_0    pypi
jupyterlab-server         2.3.0                    pypi_0    pypi
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         2.5.1              pyhd8ed1ab_0    conda-forge
jxrlib                    1.1                  h8ffe710_2    conda-forge
kealib                    1.4.14               h96bfa42_2    conda-forge
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.3.1            py37h8c56517_1    conda-forge
korean-lunar-calendar     0.2.1                    pypi_0    pypi
krb5                      1.17.2               hbae68bd_0    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      2.2.1                h0e60522_0    conda-forge
libaec                    1.0.4                h39d44d4_1    conda-forge
libblas                   3.9.0                     8_mkl    conda-forge
libcblas                  3.9.0                     8_mkl    conda-forge
libclang                  11.1.0          default_h5c34c98_1    conda-forge
libcrc32c                 1.1.1                h0e60522_2    conda-forge
libcurl                   7.76.1               hf1763fc_1    conda-forge
libdeflate                1.7                  h8ffe710_5    conda-forge
libffi                    3.3                  h0e60522_2    conda-forge
libgdal                   3.2.2                hade8cfc_3    conda-forge
libglib                   2.68.2               h1e62bf3_0    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
libkml                    1.3.0             h9859afa_1013    conda-forge
liblapack                 3.9.0                     8_mkl    conda-forge
libnetcdf                 4.8.0           nompi_hee75d68_101    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libpq                     13.2                 h4f54205_2    conda-forge
libprotobuf               3.16.0               h7755175_0    conda-forge
libpython                 2.0              py37h03978a9_1    conda-forge
librttopo                 1.1.0                hb340de5_6    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libspatialindex           1.9.3                h39d44d4_3    conda-forge
libspatialite             5.0.1                h6b539a6_4    conda-forge
libssh2                   1.9.0                h680486a_6    conda-forge
libtiff                   4.2.0                hc10be44_1    conda-forge
libwebp-base              1.2.0                h8ffe710_2    conda-forge
libxml2                   2.9.10               hf5bbc77_4    conda-forge
libzip                    1.7.3                hfed4ece_0    conda-forge
libzopfli                 1.0.3                h0e60522_0    conda-forge
lime                      0.2.0.1                  pypi_0    pypi
llvmlite                  0.36.0           py37habb0c8c_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
lunarcalendar             0.0.9                    pypi_0    pypi
lz4-c                     1.9.3                h8ffe710_0    conda-forge
m2w64-binutils            2.25.1                        5    conda-forge
m2w64-bwidget             1.9.10                        2    conda-forge
m2w64-bzip2               1.0.6                         6    conda-forge
m2w64-crt-git             5.0.0.4636.2595836               2    conda-forge
m2w64-expat               2.1.1                         2    conda-forge
m2w64-fftw                3.3.4                         6    conda-forge
m2w64-flac                1.3.1                         3    conda-forge
m2w64-gcc                 5.3.0                         6    conda-forge
m2w64-gcc-ada             5.3.0                         6    conda-forge
m2w64-gcc-fortran         5.3.0                         6    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gcc-objc            5.3.0                         6    conda-forge
m2w64-gettext             0.19.7                        2    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-gsl                 2.1                           2    conda-forge
m2w64-headers-git         5.0.0.4636.c0ad18a               2    conda-forge
m2w64-isl                 0.16.1                        2    conda-forge
m2w64-libiconv            1.14                          6    conda-forge
m2w64-libjpeg-turbo       1.4.2                         3    conda-forge
m2w64-libmangle-git       5.0.0.4509.2e5a9a2               2    conda-forge
m2w64-libogg              1.3.2                         3    conda-forge
m2w64-libpng              1.6.21                        2    conda-forge
m2w64-libsndfile          1.0.26                        2    conda-forge
m2w64-libtiff             4.0.6                         2    conda-forge
m2w64-libvorbis           1.3.5                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
m2w64-libxml2             2.9.3                         3    conda-forge
m2w64-make                4.1.2351.a80a8b8               2    conda-forge
m2w64-mpc                 1.0.3                         3    conda-forge
m2w64-mpfr                3.1.4                         4    conda-forge
m2w64-pcre2               10.34                         0    conda-forge
m2w64-pkg-config          0.29.1                        2    conda-forge
m2w64-speex               1.2rc2                        3    conda-forge
m2w64-speexdsp            1.2rc3                        3    conda-forge
m2w64-tcl                 8.6.5                         3    conda-forge
m2w64-tk                  8.6.5                         3    conda-forge
m2w64-tktable             2.10                          5    conda-forge
m2w64-toolchain           5.3.0                         7    conda-forge
m2w64-tools-git           5.0.0.4592.90b8472               2    conda-forge
m2w64-windows-default-manifest 6.4                           3    conda-forge
m2w64-wineditline         2.101                         5    conda-forge
m2w64-winpthreads-git     5.0.0.4634.697f757               2    conda-forge
m2w64-xz                  5.2.2                         2    conda-forge
m2w64-zlib                1.2.8                        10    conda-forge
mako                      1.1.4                    pypi_0    pypi
markdown                  3.2.2                    pypi_0    pypi
markupsafe                2.0.0            py37hcc03f2d_0    conda-forge
matplotlib                3.4.2            py37h03978a9_0    conda-forge
matplotlib-base           3.4.2            py37h0d1fb12_0    conda-forge
matplotlib-inline         0.1.2              pyhd8ed1ab_2    conda-forge
metakernel                0.27.5             pyhd3deb0d_0    conda-forge
mistune                   0.8.4           py37hcc03f2d_1003    conda-forge
mkl                       2020.4             hb70f87d_311    conda-forge
mouseinfo                 0.1.3                    pypi_0    pypi
msgpack-python            1.0.2            py37h8c56517_1    conda-forge
msrest                    0.6.21             pyh44b312d_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
multidict                 5.1.0            py37hcc03f2d_1    conda-forge
munch                     2.5.0                      py_0    conda-forge
mypy                      0.812            py37hcc03f2d_2    conda-forge
mypy_extensions           0.4.3            py37h03978a9_3    conda-forge
nb_conda_kernels          2.3.0            py37hc8dfbb8_2    conda-forge
nbclassic                 0.2.6                    pypi_0    pypi
nbclient                  0.5.3              pyhd8ed1ab_0    conda-forge
nbconvert                 6.0.7            py37h03978a9_3    conda-forge
nbdime                    3.0.0b1                  pypi_0    pypi
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
nest-asyncio              1.5.1              pyhd8ed1ab_0    conda-forge
networkx                  2.5.1              pyhd8ed1ab_0    conda-forge
nltk                      3.6.2              pyhd8ed1ab_0    conda-forge
nodejs                    13.10.1                       0    conda-forge/label/cf202003
nose                      1.3.7                    pypi_0    pypi
notebook                  6.1.4            py37hc8dfbb8_0    conda-forge
numba                     0.53.1           py37h4e635f9_0    conda-forge
numpy                     1.18.5                   pypi_0    pypi
oauthlib                  3.1.0                    pypi_0    pypi
octave_kernel             0.32.0             pyh9f0ad1d_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                h48faf41_0    conda-forge
openpyxl                  3.0.6                    pypi_0    pypi
openssl                   1.1.1k               h8ffe710_0    conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 20.9               pyh44b312d_0    conda-forge
pandas                    1.2.4            py37h90003fb_0    conda-forge
pandoc                    2.13                 h8ffe710_0    conda-forge
pandocfilters             1.4.2                    pypi_0    pypi
parso                     0.7.1                    pypi_0    pypi
partd                     1.2.0              pyhd8ed1ab_0    conda-forge
pathspec                  0.8.1              pyhd3deb0d_0    conda-forge
pcre                      8.44                 ha925a31_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.1.2            py37h96663a1_1    conda-forge
pip                       21.1.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h8ffe710_0    conda-forge
plotly                    4.10.0                   pypi_0    pypi
pooch                     1.3.0              pyhd8ed1ab_0    conda-forge
poppler                   21.03.0              h9ff6ed8_0    conda-forge
poppler-data              0.4.10                        0    conda-forge
portalocker               1.7.0            py37h03978a9_1    conda-forge
postgresql                13.2                 h0f1a9bc_2    conda-forge
proj                      8.0.0                h1cfcee9_0    conda-forge
prometheus_client         0.10.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.18             pyha770c72_0    conda-forge
protobuf                  3.13.0                   pypi_0    pypi
psutil                    5.8.0            py37hcc03f2d_1    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
py4j                      0.10.9                   pypi_0    pypi
pyarrow                   2.0.0                    pypi_0    pypi
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.8                    pypi_0    pypi
pyautogui                 0.9.52                   pypi_0    pypi
pycodestyle               2.6.0                    pypi_0    pypi
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygetwindow               0.0.9                    pypi_0    pypi
pygments                  2.9.0              pyhd8ed1ab_0    conda-forge
pyjwt                     2.1.0              pyhd8ed1ab_0    conda-forge
pymeeus                   0.3.7                    pypi_0    pypi
pymsgbox                  1.0.9                    pypi_0    pypi
pyodbc                    4.0.30                   pypi_0    pypi
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyperclip                 1.8.1                    pypi_0    pypi
pyproj                    3.0.1            py37h66f9032_1    conda-forge
pyqt                      5.12.3           py37h03978a9_7    conda-forge
pyqt-impl                 5.12.3           py37hf2a7229_7    conda-forge
pyqt5-sip                 4.19.18          py37hf2a7229_7    conda-forge
pyqtchart                 5.12             py37hf2a7229_7    conda-forge
pyqtwebengine             5.12.1           py37hf2a7229_7    conda-forge
pyrect                    0.1.4                    pypi_0    pypi
pyrsistent                0.17.3           py37hcc03f2d_2    conda-forge
pyscreeze                 0.1.26                   pypi_0    pypi
pysocks                   1.7.1            py37h03978a9_3    conda-forge
pyspark                   3.0.1                    pypi_0    pypi
pystan                    2.19.1.1                 pypi_0    pypi
python                    3.7.10          h7840368_100_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-editor             1.0.4                    pypi_0    pypi
python-json-logger        2.0.1                    pypi_0    pypi
python_abi                3.7                     1_cp37m    conda-forge
pytweening                1.0.3                    pypi_0    pypi
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pywavelets                1.1.1            py37hda49f71_3    conda-forge
pywin32                   228                      pypi_0    pypi
pywinpty                  1.0.1            py37h7f67f24_0    conda-forge
pyyaml                    5.4.1            py37hcc03f2d_0    conda-forge
pyzmq                     19.0.2                   pypi_0    pypi
qt                        5.12.9               h5909a2a_4    conda-forge
qtconsole                 5.0.2                    pypi_0    pypi
qtpy                      1.9.0                    pypi_0    pypi
r-base                    4.0.5                hddad469_0    conda-forge
regex                     2021.4.4         py37hcc03f2d_0    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
requests-oauthlib         1.3.0              pyh9f0ad1d_0    conda-forge
retrying                  1.3.3                    pypi_0    pypi
rpy2                      3.4.4           py37r40h81a7dd6_0    conda-forge
rsa                       4.6                      pypi_0    pypi
rtree                     0.9.7            py37h13cc57e_1    conda-forge
ruamel-yaml               0.17.4                   pypi_0    pypi
ruamel-yaml-clib          0.2.2                    pypi_0    pypi
s3transfer                0.4.2              pyhd8ed1ab_0    conda-forge
salib                     1.3.12                   pypi_0    pypi
schedula                  1.2.6                    pypi_0    pypi
scikit-image              0.18.1           py37h08fd248_0    conda-forge
scikit-learn              0.24.2           py37h8ded0a9_0    conda-forge
scipy                     1.4.1                    pypi_0    pypi
seaborn                   0.11.0                   pypi_0    pypi
selenium                  3.141.0                  pypi_0    pypi
send2trash                1.5.0                      py_0    conda-forge
setuptools                49.6.0           py37h03978a9_3    conda-forge
setuptools-git            1.2                      pypi_0    pypi
shap                      0.36.0           py37h414f9d2_0    conda-forge
shapely                   1.7.1                    pypi_0    pypi
simplegeneric             0.8.1                      py_1    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
skope-rules               1.0.1                    pypi_0    pypi
slicer                    0.0.7              pyhd8ed1ab_0    conda-forge
smart_open                5.0.0              pyhd8ed1ab_0    conda-forge
snappy                    1.1.8                ha925a31_3    conda-forge
sniffio                   1.2.0            py37h03978a9_1    conda-forge
snowballstemmer           2.1.0                    pypi_0    pypi
sortedcontainers          2.3.0              pyhd8ed1ab_0    conda-forge
sphinx                    4.0.1                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    1.0.3                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.4                    pypi_0    pypi
spyder-kernels            1.10.0           py37h03978a9_0    conda-forge
sqlalchemy                1.4.15                   pypi_0    pypi
sqlite                    3.35.5               h8ffe710_0    conda-forge
tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
tensorboard               2.3.0                    pypi_0    pypi
tensorboard-plugin-wit    1.7.0                    pypi_0    pypi
tensorflow                2.3.0                    pypi_0    pypi
tensorflow-estimator      2.3.0                    pypi_0    pypi
tensorflow-hub            0.11.0                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.9.4            py37h03978a9_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tifffile                  2021.4.8           pyhd8ed1ab_0    conda-forge
tiledb                    2.2.9                hf84e3da_0    conda-forge
tk                        8.6.10               h8ffe710_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
toolz                     0.11.1                     py_0    conda-forge
tornado                   6.1              py37hcc03f2d_1    conda-forge
tqdm                      4.49.0                   pypi_0    pypi
traitlets                 4.3.3                    pypi_0    pypi
treeinterpreter           0.2.3                    pypi_0    pypi
typed-ast                 1.4.3            py37hcc03f2d_0    conda-forge
typing-extensions         3.7.4.3                       0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
tzlocal                   2.1                pyh9f0ad1d_0    conda-forge
urllib3                   1.26.4             pyhd8ed1ab_0    conda-forge
utils                     1.0.1                    pypi_0    pypi
vc                        14.2                 hb210afc_4    conda-forge
vs2015_runtime            14.28.29325          h5e1d092_4    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                    pypi_0    pypi
websocket-client          0.57.0           py37h03978a9_4    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
widgetsnbextension        3.5.1            py37h03978a9_4    conda-forge
win_inet_pton             1.1.0            py37h03978a9_2    conda-forge
wincertstore              0.2             py37h03978a9_1006    conda-forge
winpty                    0.4.3                         4    conda-forge
xerces-c                  3.2.3                h0e60522_2    conda-forge
xlrd                      2.0.1                    pypi_0    pypi
xlsxwriter                1.3.7                    pypi_0    pypi
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                he774522_0    conda-forge
yarl                      1.6.3            py37hcc03f2d_1    conda-forge
zeromq                    4.3.4                h0e60522_0    conda-forge
zfp                       0.5.5                h0e60522_5    conda-forge
zict                      2.0.0                      py_0    conda-forge
zipp                      3.4.1              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h62dcd97_1010    conda-forge
zope-event                4.5.0                    pypi_0    pypi
zope-interface            5.3.0                    pypi_0    pypi
zstd                      1.4.9                h6255e5f_0    conda-forge
```

**Comment by ccordoba12** [comment]
Hey @bdeshon, thanks for reporting. According to the info you posted above, you have spyder-kernels **2.0.1** in your local machine and **1.10.0** in your remote one.

Please update to **2.0.1** in your remote machine and try again.

**Comment by bdeshon** [comment]
Thanks @ccordoba12.  I updated Spyder-kernels on my remote and attempted but still had the same issue.  I also created a separate Conda env on my remote to remove any possible interactions.  Even with the new Conda env it still acts the same.

**Comment by bdeshon** [comment]
I wanted to add... I dont believe it is a firewall issue either.  I am able to connect jupyterlab to my remote via an ssh tunnel.

**Comment by ccordoba12** [comment]
Ok, please update to Spyder 5.0.2 in your local machine and try again. We fixed an error regarding remote connections on that version that could solve your problem too.

**Comment by bdeshon** [comment]
it definitely changed.  it no longer has the error in the terminal but it still hangs in Spyder, saying it is trying to connect.

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by HUtangge** [comment]
Have you solved this issue? I have the same problem, local Mac and remote Windows. I have tried all the methods in this article. :(

**Comment by anellenson** [comment]
I'm also having this problem, local Mac and remote Linux, upgraded Spyder and Spyder kernels
