### ISSUE TITLE
Slow Typing and High CPU Usage

### ISSUE THREAD

**Issue by Nomia** [spyder-ide/spyder#16067]
## Problem Description
I installed spyder just today, I found it very slow when I type code, so I start it in verbose mode, here is the screenshot 
![image](https://user-images.githubusercontent.com/1707818/126738560-750a2b86-b089-45db-9751-0ce35ee2efba.png)

I found that, whenever I type something, it will issue a net request, how can i stop it? I tried to disable the code completion, but still very slow when typing, sluggish

And I haven't enable that kite thing, you can see from the screenshot above that the spyder is trying to connect to kite, why? how can i stop it?

## Versions

* Spyder version: 4.2.5
* Python version: 3.8.8
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: MacOs Catalina 10.15.3

**Comment by Nomia** [comment]
I almost disabled everything in the code completion and linting preference settings, it's still slow when typing.

Where can i disable that LSP, cannot find it anywhere in the completion and linting section. There is no `general` tab anymore

I really don't wanna give up on this editor right now. coz it looks good and promising

thx

**Comment by ma-sadeghi** [comment]
Same for me, it's sluggish when typing.

**Comment by ma-sadeghi** [comment]
Update: I disabled Kite and it's back to normal.

**Comment by jsh9** [comment]
@Nomia what's your screen resolution?

This issue has been present since the Spyder 4 era.  On 4k monitors, this issue is very prominent, and on monitors with 2k resolution or below, there is no slowness in typing.

Disclaimer:
1. I am not part of the Spyder development team; I'm also a Spyder user
2. I am **in no way** implying that this issue should not be fixed

**Comment by ma-sadeghi** [comment]
@jsh9 Mine is 4K (3840px x 2160px)

**Comment by Nomia** [comment]
@jsh9 mine is 2560 x 1600

**Comment by Nomia** [comment]
seems that this issue is ignored by the dev team, 2 days after, no response while as other issues all got reply or at least a `enhancement` label

I've mentioned this issue at another issue #15042 , hope they will get there and give a hand

**Comment by juanis2112** [comment]
hi @Nomia thanks for reporting this. What installation method did you use? I would suggest trying Spyder from our standalone installers https://docs.spyder-ide.org/current/installation.html and letting us know if you find the same problem.

**Comment by Nomia** [comment]
one of your team member @ccordoba12 said this issue will be fixed in the Spyder 5.1.0. I'd wait for that

and I will try the standalone installer

Before, I installed the Spyder from the standalone installer the first time, and I found some problem(don't remember what that is now), so I tried to install it from the anaconda, then I found the typing latency problem

I'll try again the standalone installer to see what will happen, thx

**Comment by Nomia** [comment]
I just tried the standalone installer, and......the typing latency is gone! @ma-sadeghi @juanis2112 @jsh9 @ccordoba12 

I can't find the version of it coz I can't find the `about spyder` menu item

so I `conda list | grep spyder` I get 
`spyder                    5.0.5            py38hecd8cb5_2 `

I think this is the version I just installed, coz before it was 4.2.5
so this bug is fixed before version 5.1.0?

**Comment by ma-sadeghi** [comment]
I installed my spyder using `conda install spyder`. I currently have the latest, which is `5.0.5` I think. So, you're saying that I should uninstall my `conda` installation and reinstall using the standalone installer?

**Comment by Nomia** [comment]
@ma-sadeghi  try the standalone installer without removing the old one first, if it doesn't work, then try to remove the old one and reinstall the new one(standalone installer)

for me, I keep them both

**Comment by juanis2112** [comment]
Yes @ma-sadeghi. But as @Nomia said you don't need to uninstall your conda installation. Try the installer without doing that first.

**Comment by ccordoba12** [comment]
The problem with Spyder in Anaconda and Mac is that Anaconda uses a very old version of PyQt (the graphical toolkit on top of which Spyder is built), which introduces the huge latency you're seeing. Since our Mac installer uses a more recent version, that's why the latency is gone with it.

Things should work the same if you installed Spyder from conda-forge, but unfortunately (I don't know why), every person we have suggested to do that said that it doesn't, and only our installers lack the latency issues.

**Comment by ccordoba12** [comment]
By the way, you can use our installers with your current conda environments, by following this advice in [our FAQ](https://docs.spyder-ide.org/5/faq.html#using-packages-installer).

**Comment by rggs** [comment]
Just wanted to also point out that if you use conda for package management but don't really care about using Anaconda Navigator, you can upgrade qt and pyqt with:
`conda install qt=5.12.9 -c conda-forge --force-reinstall`
which will upgrade qt and its dependencies. This will break Anaconda Navigator and you won't be able to open it, but you can just launch Spyder from your terminal.

**Comment by TukuToi** [comment]
The typing issue is resolved as soon as using https://docs.spyder-ide.org/current/installation.html instead of anaconda.

Thus, if to using anaconda, just drop that and use https://docs.spyder-ide.org/current/installation.html - worked for me.

**Comment by ccordoba12** [comment]
Thanks @TukuToi for pointing that out. It's correct that most lagging issues in the editor are fixed now in our 5.1.5 version, available through our installers.

You can also install that version from conda-forge, by running the following commands in the Anaconda Prompt or Terminal.app

    conda create -n spyder-env -c conda-forge spyder
    conda activate spyder-env
    spyder

**Comment by ccordoba12** [comment]
I'm going to close this issue for now. If after installing 5.1.5 you still encounter sluggishness in the editor, please open a new one.
