### ISSUE TITLE
5.1.0: Outline Pane not loading on Windows installer

### ISSUE THREAD

**Issue by sharon92** [spyder-ide/spyder#16118]
### What steps will reproduce the problem?

1. Open Spyder
2. Load a Python Script with functions and classes
3. Outline pane will not show any of these functions or classes

**Comment by ccordoba12** [comment]
Hey @sharon92, thanks for reporting. How did you install Spyder 5.1.0?

**Comment by sharon92** [comment]
@ccordoba12 I used the standalone Installer for Windows 10 from here https://github.com/spyder-ide/spyder/releases/tag/v5.1.0

**Comment by ccordoba12** [comment]
Ok, could you post a screenshot of what you're seeing?

**Comment by ccordoba12** [comment]
I mean, an screenshot of the entire Spyder window.

**Comment by sharon92** [comment]
![image](https://user-images.githubusercontent.com/51754340/127894876-5232efa3-e393-4bf6-b50f-6e7c1b8c5a78.png)

**Comment by ccordoba12** [comment]
Ok, thanks. Are code completion and warnings in the editor working for you?

**Comment by sharon92** [comment]
@ccordoba12 Good Morning, the code completion and warnings (code errors are appearing [red cross for invalid syntax] but not the warn triangle [for unused variable]) seem to be working:

![image](https://user-images.githubusercontent.com/51754340/127972665-343554c7-d614-4df2-ab53-ca8e912bb237.png)

**Comment by hofsaess** [comment]
I have the same issue with the outline plane.
I use a linux (debian) system with the new v5.1.0.

**Comment by ccordoba12** [comment]
Thanks @sharon92 for the extra info. I can confirm this bug is present in 5.1.0 and I'll try to fix it in our next release (5.1.1)

**Comment by ccordoba12** [comment]
Update: I found a fix for this and it'll definitely be available in our next version.

**Comment by sharon92** [comment]
@ccordoba12 Thank you for your good work 👍

**Comment by hofsaess** [comment]
Hi @ccordoba12, I don't know why you add the os:windows tag and change the name of the topic, because I had the same issue (https://github.com/spyder-ide/spyder/issues/16118#issuecomment-891863231) with my linux system?

**Comment by ccordoba12** [comment]
If you installed 5.1.0 using pip (the only possible way right now), you should be have received a message saying that it's broken. That should be fixed in 5.1.1, but the problem reported by @sharon92 is specifically about the Windows installer.

**Comment by hofsaess** [comment]
yes i have installed v5.1.0 via pip. When I start spyder I do not get any message. The outline plane still shows nothing.
