### ISSUE TITLE
Project explorer doesn't refresh its contents

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1964]
_From [mishok...@gmail.com](https://code.google.com/u/104975048361012621268/) on 2014-09-12T11:37:22Z_

There is no refresh button for the project. If the folder was changed outside of spyder then it can't pick up the change. In many cases it is necessary to modify the files by some external program (such as source control)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1964_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-18T15:42:33Z_

**Labels:** Cat-ProjectExplorer MS-v2.4

**Comment by dzosz** [comment]
still no refresh : (

**Comment by ccordoba12** [comment]
As you can see, this bug is still open, so it hasn't been fixed :-)

**Comment by dignitas123** [comment]
It's not very convenient to restart spyder everytime a file name has been updatet. Voting for a refresh option!

**Comment by ccordoba12** [comment]
@dignitas123, what's your Spyder version? As you can see, this was fixed a long time ago.

**Comment by andyrevell** [comment]
On Spyder 4.1.4 - still an issue it seems. I'm new to Sypder and coming from PyCharm. They have a "sync to disk" option when right clicking a folder in their own version of a project explorer. Is there a force refresh button and I'm just missing it somewhere?

**Comment by jmoraispk** [comment]
I would reopen this issue. I found a set of actions that make a folder not update its contents.

1- create a function that saves an array to a folder, and creates the folder if it doesn't exist.
2- run in the cwd. A folder is created and the array goes inside it. We see in Spyder's explorer that a new folder appears and, say, array x is saved as x.npy and put inside that folder.
3- click on that arrow on Spyder's file explorer to expand the contents of a folder
4- run the function again, but change the name of the array file. Say, array y is saved as y.npy. Notice now that the folder contents are not updated, but if you open your OS's file explorer, you can see the contents there.

This seems a simple issue, but it _definitely_ exists and can be quite confusing. I'm using Spyder 5.0.5.
