### ISSUE TITLE
Rust and Cargo are now part of Spyder's dependencies

### ISSUE THREAD

**Issue by Mark531** [spyder-ide/spyder#21447]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I created a fresh anaconda environment with python 3.12 and installed spyder-kernels successfully. But when trying to install Spyder, I ran into an error saying that Rust and Cargo must be installed. Since when did these new dependencies appear? It's precised nowhere in Spyder's documentation.

### What steps reproduce the problem?
In an Anaconda prompt, just run these commands:
1. conda create --name=dev python
2. conda activate dev
3. pip install spyder-kernels
4. pip install spyder

### What is the expected output? What do you see instead?
I expected Spyder to be installed without additional dependencies (or the latter should be installed automatically via pip).

### Paste Traceback/Error Below (if applicable)

```python-traceback
      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/
```

## Versions

* Spyder version: 5.4.5 (target)
* Python version: 3.12.0
* Qt version: /
* PyQt version: /
* Operating System name/version: Windows 10

**Comment by ccordoba12** [comment]
Hey @Mark531, thanks for reporting. Spyder doesn't require Rust and Cargo directly. My guess is that some dependency of our dependencies doesn't have wheels for Python 3.12 yet and it needs those packages to build it.

But to be sure, please post the last 50 or 100 lines before the message you posted above to better understand what's happening.

**Comment by Mark531** [comment]
Hi @ccordoba12 thanks for your prompt reply. The package which seems to require Rust and Cargo is jellyfish. Here are the complete logs:

> (dev) C:\Users\Mark4>pip install spyder
> Collecting spyder
>   Using cached spyder-5.4.5-py3-none-any.whl.metadata (22 kB)
> Collecting atomicwrites>=1.2.0 (from spyder)
>   Using cached atomicwrites-1.4.1.tar.gz (14 kB)
>   Preparing metadata (setup.py) ... done
> Collecting chardet>=2.0.0 (from spyder)
>   Using cached chardet-5.2.0-py3-none-any.whl.metadata (3.4 kB)
> Requirement already satisfied: cloudpickle>=0.5.0 in c:\users\mark4\anaconda3\envs\dev\lib\site-packages (from spyder) (3.0.0)
> Collecting cookiecutter>=1.6.0 (from spyder)
>   Using cached cookiecutter-2.4.0-py3-none-any.whl.metadata (7.0 kB)
> Collecting diff-match-patch>=20181111 (from spyder)
>   Using cached diff_match_patch-20230430-py3-none-any.whl (42 kB)
> Collecting intervaltree>=3.0.2 (from spyder)
>   Using cached intervaltree-3.1.0.tar.gz (32 kB)
>   Preparing metadata (setup.py) ... done
> Requirement already satisfied: ipython!=8.10.0,!=8.11.0,!=8.12.0,!=8.12.1,!=8.8.0,!=8.9.0,<9.0.0,>=7.31.1 in c:\users\mark4\anaconda3\envs\dev\lib\site-packages (from spyd
> er) (8.16.1)
> Collecting jedi<0.19.0,>=0.17.2 (from spyder)
>   Using cached jedi-0.18.2-py2.py3-none-any.whl (1.6 MB)
> Collecting jellyfish>=0.7 (from spyder)
>   Using cached jellyfish-1.0.1.tar.gz (363 kB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... done
>   Preparing metadata (pyproject.toml) ... error
>   error: subprocess-exited-with-error
> 
>   × Preparing metadata (pyproject.toml) did not run successfully.
>   │ exit code: 1
>   ╰─> [6 lines of output]
> 
>       Cargo, the Rust package manager, is not installed or is not on PATH.
>       This package requires Rust and Cargo to compile extensions. Install it through
>       the system's package manager or via https://rustup.rs/
> 
>       Checking for Rust toolchain....
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed

**Comment by ccordoba12** [comment]
As I guessed, Rust and Cargo are required by Jellyfish, one of our direct dependencies. That means that for now it's not possible to install Spyder in a Python 3.12 environment. And it could take a couple of months until the Jellyfish maintainers add support for it.

But that's really not important because I'm sure you can install Spyder-kernels on that env. And then, after doing that, you need to connect Spyder to it by following these instructions in our documentation:

http://docs.spyder-ide.org/current/faq.html#using-existing-environment

to start developing for Python 3.12.

Let us know if that works for you.

**Comment by Mark531** [comment]
Well, at least you're aware of it now. You're going to receive many messages of this kind. :)

So, I tried to connect Spyder to my 3.12 env and it failed because the version of spyder-kernels I've installed (2.4.4) is not compatible with my current version of Spyder (5.1.5):

> Your Python environment or installation doesn't have the spyder‑kernels module or the right version of it installed (>= 2.1.0 and < 2.2.0). Without this module is not possible for Spyder to create a console for you.

So, what's the correct way to handle this, do I have to downgrade spyder-kernels, or install the latest version of spyder supporting my spyder-kernels version?

**Comment by ccordoba12** [comment]
> Well, at least you're aware of it now. You're going to receive many messages of this kind. :)

Yep, we'll probably do.

> So, what's the correct way to handle this, do I have to downgrade spyder-kernels, or install the latest version of spyder supporting my spyder-kernels version?

You have to update Spyder because there's an incompatibility between the Spyder-kernels that you need to install to work with Spyder 5.1.5 and Python 3.12.

Please update by closing Spyder, opening the Anaconda Prompt and running there the commands mentioned in [our documentation](http://docs.spyder-ide.org/current/installation.html#updating-with-anaconda).

**Comment by Mark531** [comment]
I tried to install spyder 4.5.3, but it also failed... What is the version of spyder I should install in order to be compatible with python 3.12 and my spyder-kernels version (2.4.4)?

**Comment by ManuelPopp** [comment]
> I tried to install spyder 4.5.3, but it also failed... What is the version of spyder I should install in order to be compatible with python 3.12 and my spyder-kernels version (2.4.4)?

My solution (in this case on Windows 10):
I had a related issue: I had a previous version of Spyder (v 5.0.2) already installed. I installed Python 3.12 and Spyder kernels, but the old Spyder version required distutils which has been deprecated in Python 3.12.

I managed to make it work using Spyder 2.4.4 installed through an older Python version's pip (v 3.9). In my case:
C:\Users\Manuel\Python\Scripts\pip3.9.exe install --upgrade spyder==5.4.4

(I guess any Python version < 3.12 with pip should be able to install Spyder.)

Then, use Python 3.12's pip to install Spyder kernels
pip install spyder-kernels==2.4.*

Finally, open Spyder and go to "Tools" -> "Preferences" -> "Python interpreter", check "Use the following interpreter" and set the path to the Python 3.12 exe.

**Comment by Mark531** [comment]
@ManuelPopp thanks for your tips, but I don't understand the relation between the missing dependencies and the version of pip.

**Comment by ccordoba12** [comment]
@Mark531, you said:

> I tried to install spyder 4.5.3, but it also failed...

What was the error you encountered?

> What is the version of spyder I should install in order to be compatible with python 3.12 and my spyder-kernels version (2.4.4)?

It's Spyder 5.4.5 or any other version equal or greater than Spyder 5.4.0. Unfortunately, versions of Spyder-kernels older than 2.4.3 are incompatible with Python 3.12. And it's not possible for any Spyder version older than 5.4.0 to work with that version of Spyder-kernels.

**Comment by Mark531** [comment]
@ccordoba12 I found a solution. Everytime I tried to install Spyder (whatever the version), pip used to grab the Jellyfish package I had in cache (v1.0.1) and this triggered the error with Rust and Cargo. So, I installed Jellyfish v0.7.1 beforehand, and then installed Spyder v5.4.5. It worked like a charm! I can now use Spyder with python v3.12.

I now have to find a way to create a desktop link to open this version of Spyder (I ran it from my Anaconda prompt in the right environment). The one created by Anaconda still opens my old version. I haven't found any tips in your installation guide to solve such an issue.

**Comment by ccordoba12** [comment]
Great! Glad to know you finally found a solution for this. I'm going to leave your issue open though in case more people hit the same problem.

**Comment by Mark531** [comment]
Ok, thank you for your support!

**Comment by pwbriggs** [comment]
This issue is fixed as per jamesturk/jellyfish#197, so `pip install spyder` should work on Python 3.12 now.

**Comment by ccordoba12** [comment]
@pwbriggs, thanks for letting us know about it! I'm going to close this issue then.

**Comment by muriloasouza** [comment]
For Python 3.13 the problem persists. Can anyone else confirm this?

Created a fresh venv:

`py -3.13 -m venv tf-gpu`

Then, inside of it:

`(tf-gpu) C:\Users\ldsp_>pip install spyder`

```
Collecting spyder
  Using cached spyder-6.0.2-py3-none-any.whl.metadata (23 kB)
Collecting aiohttp>=3.9.3 (from spyder)
  Using cached aiohttp-3.11.9-cp313-cp313-win_amd64.whl.metadata (8.0 kB)
Collecting asyncssh<3.0.0,>=2.14.0 (from spyder)
  Using cached asyncssh-2.18.0-py3-none-any.whl.metadata (9.9 kB)
Collecting atomicwrites>=1.2.0 (from spyder)
  Using cached atomicwrites-1.4.1.tar.gz (14 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting chardet>=2.0.0 (from spyder)
  Using cached chardet-5.2.0-py3-none-any.whl.metadata (3.4 kB)
Collecting cloudpickle>=0.5.0 (from spyder)
  Using cached cloudpickle-3.1.0-py3-none-any.whl.metadata (7.0 kB)
Collecting cookiecutter>=1.6.0 (from spyder)
  Using cached cookiecutter-2.6.0-py3-none-any.whl.metadata (7.3 kB)
Collecting diff-match-patch>=20181111 (from spyder)
  Using cached diff_match_patch-20241021-py3-none-any.whl.metadata (5.5 kB)
Collecting importlib-metadata>=4.6.0 (from spyder)
  Using cached importlib_metadata-8.5.0-py3-none-any.whl.metadata (4.8 kB)
Collecting intervaltree>=3.0.2 (from spyder)
  Using cached intervaltree-3.1.0.tar.gz (32 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting jedi<0.20.0,>=0.17.2 (from spyder)
  Using cached jedi-0.19.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting jellyfish>=0.7 (from spyder)
  Using cached jellyfish-1.1.0.tar.gz (364 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]

      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/

      Checking for Rust toolchain....
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
