### ISSUE TITLE
Next file / previous file keyboard shortcuts

### ISSUE THREAD

**Issue by cnolanAU** [spyder-ide/spyder#2546]
## Description

In Spyder under OS X I attempt to redefine keyboard shortcuts to move between open files in the editor to "Cmd-shift-BracketLeft" and "Cmd-shift-BracketRight". This redefinition has no effect, and despite the shortcut not appearing at all in the list, "Cmd-PgUp" and "Cmd-PgDn" switch between editors.

**What steps will reproduce the problem?**

1. Open Preferences | Keyboard shortcuts.
2. Find "editor | go to next file" and "editor | go to previous file" entries and modify to those in the description.
3. Focus on the editor and try to use the new key bindings.

**What is the expected output? What do you see instead?**

The redefined keybindings do not work.

**Please provide any additional information below**

## Version and main components

* Spyder Version: 2.3.5.2 
* Python Version: 3.4.3
* Qt Versions:  4.8.6, PyQt4 (API v2) 4.11.3 on Darwin

## Optional dependencies
```
pyflakes >=0.6.0:  0.9.2 (OK)
pep8 >=0.6      :  1.6.2 (OK)
IPython >=1.0   :  3.2.1 (OK)
zmq >=2.1.11    :  14.7.0 (OK)
pygments >=1.6  :  2.0.2 (OK)
pandas >=0.13.1 :  0.16.2 (OK)
sphinx >=0.6.6  :  1.3.1 (OK)
psutil >=0.3    :  2.2.1 (OK)
rope >=0.9.2    :  0.9.4-1 (OK)
jedi >=0.8.1    :  0.8.1 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  None (NOK)

```

**Comment by ccordoba12** [comment]
You need to press `Enter` after each key change you do when defining your new shortcut.

That's an unpleasant limitation that's already fixed in master because we have now a new and easier way to change shortcuts.

Sorry for the current inconvenience :-)

**Comment by cnolanAU** [comment]
Thanks for the response Carlos. I've tried going in to each element of the
shortcut (both modifiers and the key selection itself), scroll to the
modifier / key I want and press enter, then press apply and ok. The key
combination still doesn't work.

But not a big deal if this is fixed in the next release anyway.

**Comment by FlyingMoses** [comment]
Sorry to necro this, I’m new so I don’t know exactly how this should work, but this still isn’t working for me. I set the new keyboard commands and it still doesn’t switch the active tab/script, even after hitting apply or enter and whatnot. I’m on Spyder 2.3.7, macbook air, Mavericks 10.9.5

**Comment by cnolanAU** [comment]
I never managed to make the modified shortcuts work, I've just been dealing
with it until a new version updates the shortcut mechanics.

**Comment by FlyingMoses** [comment]
Hmm. Any idea when that will be? It seems a little silly that Spyder doesn’t have an easy way to swap tabs/files (other than via cmd-E, which is not faster at all) like, say, ctl-tab on Chrome/Safari/etc. Is it not a default shortcut? I see cmd-tab, which not only doesn’t work but is silly as cmd-tab is a system-wide common shortcut on mac (the alt-tab equivalent)

**Comment by cnolanAU** [comment]
There is a default: cmd-pgdn and cmd-pgup (if you're on the laptop
keyboard, that's cmd-fn-down and cmd-fn-up).
