### ISSUE TITLE
Spyder crash relating to libpng16.dll, windows 7/Anaconda

### ISSUE THREAD

**Issue by jrronimo** [spyder-ide/spyder#2803]
Hello,

I'm trying to use Spyder and having a lot of trouble. After installing Anaconda, I cannot run spyder.

At the moment, when I try to run python spyder-script.py from my anaconda\scripts folder, python.exe crashes. Windows reports "APPCRASH" in python.exe with the "fault module name" of "libpng16.dll".

If I rename libpng16.dll to libpng16.dll.bak, I get "cannot import name QKeySequence".

Does anyone have any ideas? I'm new to this, but I'm having a lot of trouble.

**Comment by ccordoba12** [comment]
Please run

    conda update conda-env

That should fix your problem.

**Comment by jrronimo** [comment]
Thanks for the quick response. Here's what I got:
[code]Fetching package metadata: ....
# All requested packages already installed.
# Packages in environment at C:\Anaconda2b:
# 
conda-env         2.4.4           py27_1[/code]

Running Spyder from either the Start Menu or from "python spyder-script.py" results in pythonw.exe crashing with libpng16.dll still.

(Anaconda is installed to c:\anaconda2b because I was trying to troubleshoot the problem by clean installing anaconda to a new location.)

**Comment by ccordoba12** [comment]
This is a problem with Anaconda, not with Spyder. The current solution is to run

    conda update python

That should fix your problem.

**Comment by aristotll** [comment]
I have the same problem.

**Comment by jrronimo** [comment]
Running
  conda update python

Did not solve the problem. I had another install where Spyder crashes on start as well -- it seems like if a machine has ever had any version of python installed, even if one uninstalls it, Spyder doesn't work when installed alongside Anaconda. I can't find what's causing the crash, just that Spyder crashes when one tries to start it.

**Comment by ccordoba12** [comment]
@jrronimo, what's your Python version?

**Comment by cwberardi** [comment]
I am having the same issue.  Using python 3.4.4 on windows 7 64-bit.  I tried both `conda update python` and `conda update conda-env`, no luck with either. Windows reports "APPCRASH" in python.exe with the "fault module name" of "QtGui4.dll".  Any suggestions?

**Comment by ccordoba12** [comment]
I think this problem only happens on Anaconda installations that uses Python 3.4 on Windows, according to ContinuumIO/anaconda-issues#654.

Since this issue was already fixed, I'm closing this one too.

**Comment by cwberardi** [comment]
This issue was not fixed, I tried `conda update python` and `conda update conda-env` this morning after the issue was closed and spyder still crashes on opening.  Windows still reports "APPCRASH" in python.exe with the "fault module name" of "QtGui4.dll". Any suggestions?

**Comment by ccordoba12** [comment]
You have to update Qt and PyQt for this to work, but I don't know if the packages are already available in Continuum channels.

You have to keep trying until new packages are available.

**Comment by nbrakeES** [comment]
@ccordoba12 the original issue mentioned by @jrronimo is still unresolved.  I'm using the latest anaconda distribution, with python 3.5, on windows and have tried all of the solutions listed in this thread and the referenced threads.  The fault I'm seeing occurs in libpng16.dll and I have not seen a fault in QtGui4.dll.  

![image](https://cloud.githubusercontent.com/assets/16159836/13675476/aef764a4-e696-11e5-94f3-14923681dc94.png)

**Comment by ccordoba12** [comment]
Sorry, I don't know how to help you solve this.

@msarahan, I thought this was solved. Do you know what could it be happening here?

**Comment by jrronimo** [comment]
I apologize for not returning with further information. It was taking a lot of my time to try and troubleshoot this for my user, and I had other things to do.

It seems like the problem definitely occurs in a scenario like this:
1. User installs regular python.
2. User installs Anaconda.
3. User tries to install qutip / spyder.
4. Spyder seems to not work, erroring out.

Even after uninstalling regular python, the problem seems to persist. I'm not sure why libpng16.dll would crash like this. I'm not even sure the scenario I outlined up there is 100% accurate, but I remember, when I last looked at it, that a pre-existing python install seemed especially poisonous.

**Comment by msarahan** [comment]
The way that Windows finds DLLs is documented here:  https://msdn.microsoft.com/en-us/library/7d83bc18.aspx

If users are using the root environment, then we are at the mercy of their PATH environment variable, which can, and often does go wrong, with other DLLs shadowing our internal ones.

If users are creating environments, then we put our PATH first when activating the environment.  This is a little bit safer, but doesn't preclude errors if 3rd party libraries are installed to C:\Windows\System32, which is terrible practice, but not unheard of.

One way to avoid this would be to have packages copy all of their dependencies into their folder, so that they would be found before anything else.  That's what wheels do, as I understand it.  You then lose assurance of only a single DLL for a given functionality, and might end up in DLL hell if two packages depend on different versions of the same library.

**Comment by ccordoba12** [comment]
Closing as this should be solved now.
