### ISSUE TITLE
It seems the kernel died unexpectedly. Use 'Restart kernel' to continue using this console.

### ISSUE THREAD

**Issue by Timen123** [spyder-ide/spyder#3434]
## Description of your problem

Hi! I am quite new to Python. I have a code of a few hundred lines. The execution time is roughly 15 minutes. Often the code is working just fine and I can run the script without the kernel crashing, but sometimes I get the message: 'It seems the kernel died unexpectedly. Use 'Restart kernel' to continue using this console.' When this happens feels very random: sometimes after it happens I restart spyder, run the exact code again, and it works just fine.

**What steps will reproduce the problem?**

1. I haven't found anything that reproduces the problem at all times.
2. -
3. -

**What is the expected output? What do you see instead?**
It seems the kernel died unexpectedly. Use 'Restart kernel' to continue using this console.
It seems the kernel died unexpectedly. Use 'Restart kernel' to continue using this console.
It seems the kernel died unexpectedly. Use 'Restart kernel' to continue using this console.
It seems the kernel died unexpectedly. Use 'Restart kernel' to continue using this console.
It seems the kernel died unexpectedly. Use 'Restart kernel' to continue using this console.
It seems the kernel died unexpectedly. Use 'Restart kernel' to continue using this console.
It seems the kernel died unexpectedly. Use 'Restart kernel' to continue using this console.

**Please provide any additional information below**
Sorry for the vague problem, but I have no idea where to look for the cause of the problem, since it seems to happen at a random time.
Installed everything using Anaconda (4.1.1), also some additional packages.

## Versions and main components

* Spyder Version: 2.3.9
* Python Version: 3.5.2
* Operating system: Windows 10 Enterprise

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=1.0      :  4.2.0 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
pandas >=0.13.1    :  0.18.1 (OK)
pep8 >=0.6         :  1.7.0 (OK)
pyflakes >=0.6.0   :  1.2.3 (OK)
pygments >=1.6     :  2.1.3 (OK)
pylint >=0.25      :  None (NOK)
qtconsole >=4.0    :  4.2.1 (OK)
rope >=0.9.2       :  0.9.4-1 (OK)
sphinx >=0.6.6     :  1.3.1 (OK)
sympy >=0.7.3      :  1.0 (OK)
zmq >=2.1.11       :  15.2.0 (OK)

Thanks for the help!

**Comment by ccordoba12** [comment]
We try to fix this for Spyder 3.0, i.e. to make our IPython consoles more stable.

We're about to release this new version, so please comment here again when you test your code against that version :-)

**Comment by Timen123** [comment]
Ok! I will keep my eye out for the 3.0 update.
Thanks for the reply! :)

**Comment by ccordoba12** [comment]
This should be fixed in Spyder 3.0. Please open a new issue if the problem continues to happen.

**Comment by randomgambit** [comment]
```
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.19.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.5.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

```

**Comment by LainerDonet** [comment]
The trouble still happen in Spyder 3.0 and 3.0.1. I don't has this problem in older version of Spyder if someone have the solution please comment.

**Comment by dmitrenkoivan** [comment]
It was helpfull for me
```
conda install nomkl numpy scipy scikit-learn numexpr
conda remove mkl mkl-service
```
