### ISSUE TITLE
More errors with auto-indentation

### ISSUE THREAD

**Issue by mayurpande** [spyder-ide/spyder#4300]
## Description of your problem
Each time I hit the return key, the cursor moves 40 px to the right from where I currently have the cursor.
In result messing up the indentation. 

**What steps will reproduce the problem?**

1. Each time pressing the return key.
2. 
3. 

**What is the expected output? What do you see instead?**
It does not return to the under the previous line written.

**Please provide any additional information below**
I have tried to `spyder --reset` but this did not work.
I have also clicked fix indentation but this does not work.

## Versions and main components

* Spyder Version: Spyder3 
* Python Version: Python3
* Qt Version:
* PyQt Version:
* Operating system: Ubuntu 16.04

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
This was fixed in version **3.1.3**. Please update.

**Comment by mayurpande** [comment]
@ccordoba12 I have just done this. But still getting problems, now when I try and copy and paste some code, I cannot move a line of code to the appropriate indent once pasted using backspace and other indentations are still messing up. Not sure what's going on, it was all working fine this morning.

**Comment by ccordoba12** [comment]
Please post a simple and reproducible example that shows this problem so we can fix it in our side.

**Comment by mayurpande** [comment]
@ccordoba12 Ok so I have attached two images.
![showcursorafterreturn](https://cloud.githubusercontent.com/assets/6522456/24367089/46c9d498-1313-11e7-800a-abb36b56927c.png)

On the first image, where I have marked the red. This is where when I press the return key it takes me to, and therefore when I write code, shows and indent error. So I then have to go and press the "Fix indent" button, each time.

However after I do this if I copy and paste some code it also messes up the indent again, but if I press back space, it either doesn't let me move it back, or it goes to a certain point and stops. I could show the backspace part in the image, but have uploaded another one with the problem in question in red.

![copypaste](https://cloud.githubusercontent.com/assets/6522456/24367280/f695f23a-1313-11e7-9404-a69b3595643c.png)

**Comment by ccordoba12** [comment]
Thanks for the screenshots. We'll take a look at this to see what's happening.

**Comment by mayurpande** [comment]
@ccordoba12 I tried to uninstall and reinstall however now I am getting the error;

```
Segmentation fault (core dumped)

```

When I run `spyder3` from my terminal.

The way I uninstalled spyder was like so;

```
sudo apt-get purge spyder

```

then to reinstall I ran this command

```
sudo apt-get install spyder3
```

**Comment by ccordoba12** [comment]
> sudo apt-get install spyder3

That installs the Spyder version for Python 3,  not the version 3 of Spyder. I think Ubuntu 16.04 doesn't come with Spyder 3, but I'm not so sure.

**Comment by mayurpande** [comment]
@ccordoba12 I ended up reinstalling version 3 with `pip` and am still getting the original indentation errors, its really odd, my friend has the exact same version, and he has no problems.

**Comment by ccordoba12** [comment]
Please uninstall the package you installed with apt-get and try again.

**Comment by mayurpande** [comment]
@ccordoba12 Finally managed to resolve the issue. I uninstalled spyder3 using;

```
sudo apt-get purge spyder3
sudo apt autoremove

```

I then installed via pip3 using

```
sudo pip3 install spyder3
sudo pip3 install pyqt5

```

However then I was still getting the errors. So I went to preferences and  `Reset to defaults` this never worked before but now it did.

**Comment by ccordoba12** [comment]
Great!! Glad it finally worked for you!
