### ISSUE TITLE
Missing "x" on tab for open files in editor

### ISSUE THREAD

**Issue by mjherold** [spyder-ide/spyder#4580]
## Description

Missing "x" symbol on tabs for open files in editor. The "x" used to be an icon to close the file.

**What steps will reproduce the problem?**

1. Open any file in the editor. The tab for that file does not have "x" symbol to close the file. But if you click on the tab in the area where the "x" used to be you still manage to close the file.
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.1.4 
* Python Version: 2.7.13
* Qt Versions: 5.8.0, PyQt5 5.8.2 on Darwin

## Dependencies
```
pyflakes >=0.5.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.6.2 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
sympy >=0.7.3    :  None (NOK)
pylint >=0.25    :  1.7.1 (OK)

```

**Comment by ccordoba12** [comment]
Thanks for reporting. This is probably caused by Qt 5.8 on macOS. The thing is we mainly test Spyder with Anaconda, which comes with Qt 5.6.

**Comment by LudgerHentschel** [comment]
I recently noticed this problem (missing "x" in Spyder IDE file tabs) after updating to Anaconda 5.2.0 on MacOS 10.13.4.

Of the items the previous posts focused on, Anaconda 5.2.0 installed 

Python        2.7.15
Spyder        3.2.8
qt                5.9.5

Thank you, 

Ludger

**Comment by ccordoba12** [comment]
According to https://github.com/gideros/gideros/issues/326 this was fixed in Qt **5.9.2**.

**Comment by LudgerHentschel** [comment]
Updating qt to 5.9.2 or later by itself does not seem to fix this. 

The "x" marking the spot to close the tabs in Spyder are still missing in my setup -- despite using qt 5.9.5 and Spyder 3.2.8.

I hope I managed to attach a screenshot with evidence:

![screen shot 2018-06-28 at 17 27 29](https://user-images.githubusercontent.com/28766875/42061648-f8d14588-7af8-11e8-9232-58ec955525a5.png)

The remainder of my installation is Anaconda 5.2.0. 

Thank you, 

Ludger

**Comment by ccordoba12** [comment]
Unfortunately none of the current developers use macOS, so we don't have a chance to fix this, sorry.

**Comment by denson** [comment]
I found a workaround:

Change the Qt windows style to either Fusion or WIndows in Preferences > General > Appearance > Qt windows style 

It is ugly (by Mac standards) but works.

![spyder_qt_windows_prefs](https://user-images.githubusercontent.com/1481000/43651934-5df06878-9709-11e8-8af2-8429bba19d52.png)

**Comment by cbw99** [comment]
This workaround works for me.

**Comment by d-rams** [comment]
After trying this workaround, I now have 'x' boxes but they do nothing.

pyqt 5.9.2, spyder 3.3.1, mac osx 10.14

**Comment by ranxiao** [comment]
although the "x" is missing, but by clicking where it supposes to be, the close function still works!
