### ISSUE TITLE
Open GL support

### ISSUE THREAD

**Issue by fizwit** [spyder-ide/spyder#4624]
spyder3 fails while starting with this error
[13936:14070:0620/132454:ERROR:gl_surface_qt.cpp(251)] glXCreatePbuffer failed.

I have loaded Mesa and libGLX to execution path.  Which additional libraries are required?

'spyder', '3.1.4',
Python 3.6.1
Qt 4.8.7
PyQt5 5.8.2
Mesa 12.0.2
freeglut 3.0.0

**Comment by ccordoba12** [comment]
I think this will be fixed in Spyder 3.2 because we added `pyopengl` as a new dependency to fix this kind of errors.

3.2 will be released in a couple of weeks. In the meantime, please take a look at #4601 for the solution.

**Comment by boegel** [comment]
@ccordoba12 I'm seeing this exact same issue currently with Spyder 3.2.5 and with PyOpenGL (in place:

```
$ spyder3
[18391:18548:0111/213943:ERROR:backend_impl.cc(1385)] Unable to map Index file
[18391:18557:0111/213943:ERROR:gl_surface_qt.cpp(251)] glXCreatePbuffer failed.
Segmentation fault
```

I also tried after `$ export GALLIUM_DRIVER=swr` (which has helped in other similar situations), but not in this case.

Any suggestions how to further debug this?

**Comment by ccordoba12** [comment]
I think this was fixed in 3.2.6, please update.

**Comment by boegel** [comment]
Just tried, still seeing the same issue with Spyder 3.2.6.

The error message is slightly more informative (maybe) when using `swr`:

```
$ export GALLIUM_DRIVER=swr
$ spyder3
SWR detected AVX
[57950:57994:0112/103246:ERROR:gl_surface_qt.cpp(251)] glXCreatePbuffer failed.
[58019:58019:0100/000000:ERROR:broker_posix.cc(41)] Invalid node channel message
Segmentation fault

$ unset GALLIUM_DRIVER
$ spyder3
[58066:58108:0112/103304:ERROR:gl_surface_qt.cpp(251)] glXCreatePbuffer failed.
Segmentation fault
```

**Comment by ccordoba12** [comment]
I don't think we can do anything about it in Spyder. This seems a 
problem with Qt.

**Comment by boegel** [comment]
@ccordoba12 Any suggestions on how to debug it?

**Comment by ccordoba12** [comment]
Using the Intel driver should work, I guess. Sorry, I'm not expert on OpenGL.
