### ISSUE TITLE
Add a refresh button to the File Explorer

### ISSUE THREAD

**Issue by gb119** [spyder-ide/spyder#5314]
This is a pure feature request - it would be very nice if the file explorer had a button to force it to refresh its view of the filesystem. You can sort of work around this by using the working directory widget to move away and back again, but it's not very obvious. The rational is that I sometimes find myself copying files into my project and then wanting to edit them, but they don't show up in the file explorer tree. A little refresh button next to the back/forward/up arrows would do the trick nicely.

**Comment by ccordoba12** [comment]
Good idea! We'll try to look at this for Spyder 4.

**Comment by silentquasar** [comment]
I just noticed this today. I'm a bit surprised that the file explorer doesn't update itself even when I delete a file from within the file explorer. That seems like a bug to me.

**Comment by manipuladordedados** [comment]
This problem has already been resolved?
In the latest version of Spyder3 the file explorer update all files/directories changes automatically.

**Comment by dhirajpatra** [comment]
No, it does not auto-refresh in latest Spyder 3

**Comment by ccordoba12** [comment]
@dhirajpatra, you're probably using a very old version on Linux, because this was solved a long time ago. In other words, when you change a directory with `%cd` in the IPython console, or using the working directory toolbar, the file explorer will be updated automatically.

**Comment by zouluclara** [comment]
I install Spyder 4 on my system , the file explorer is not refreshing when adding or deleting a file , this problem is not fixed

**Comment by sergentd** [comment]
On Ubuntu LTS 18.04 with spyder 4 the file explorer is not refreshing when adding/deleting files from external nor when closing and re-opening the project. Need to close and re-run spyder to see changes.

**Comment by ccordoba12** [comment]
@sergentd, if you're using the Spyder version that can be installed with `apt-get`, then you're stuck with a very, very old one.

If that's the case, please download and install Anaconda instead.
