### ISSUE TITLE
Spyder crashes on start in new Conda environment on macOS

### ISSUE THREAD

**Issue by khalilia2000** [spyder-ide/spyder#5423]
## Description of the problem
Python crashes on start in new Conda Environment.

**What steps will reproduce the problem?**

1.  Conda version 4.3.28
2. Create a new environment with Python 3.6.3
3. Install Spyder 3.2.3
4a. Run Spyder from Conda Navigator: The program crashes with message "Python Quit Unexpectedly". 
4b. Run Spyder from the terminal: Same as above + the following message in the terminal:

/bin/pythonw: line 3:  1080 Illegal instruction: 4  /Users/.../python.app/Contents/MacOS/python "$@"

**Please provide any additional information below**
Running macOS Sierra version 10.12.6 on MacBook Pro

## Versions and main components

* Spyder Version: 3.2.3
* Python Version: 3.6.3
* Qt Version: 5.6.2
* PyQt Version: 5.6.0
* Operating system: macOS Sierra 10.12.6 

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

Spyder doesn't start so this is not possible

**Comment by Khris777** [comment]
I've had a similar issue on Windows 10 today.

After doing Windows 10 updates and updating Python packages, Spyder wouldn't start anymore, instead it was just crashing on startup telling me Python wasn't working anymore.

In the end I decided to cleanly remove my old Anaconda installation and made completely new one, now Spyder is working normally again.

**Comment by ccordoba12** [comment]
@khalilia2000, this seems to be a problem with Anaconda. We're investigating what its cause is.

**Comment by khalilia2000** [comment]
Thanks @ccordoba12,
Update: I created another environment with Python 3.5, and everything works. Seems like Python 3.6 is the problem somehow.

**Comment by ccordoba12** [comment]
Great! Thanks a lot for the feedback!

**Comment by ccordoba12** [comment]
This was fixed in Anaconda. To get the fix you need to run

    conda update python.app

in a terminal.

**Comment by gilfoyle1995** [comment]
still it crashes

**Comment by fandang** [comment]
still crashes on Mac after "conda update python.app", that didn't help

**Comment by jonas6000** [comment]
Still crashes

**Comment by erkangz** [comment]
happened to me today on fresh Anaconda install. Did anyone figure out how to solve this? TIA
