### ISSUE TITLE
Using getpass in (i)python console widget echos password

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#693]
_From [airdrik@gmail.com](https://code.google.com/u/airdrik@gmail.com/) on 2011-06-18T20:04:49Z_

What steps will reproduce the problem?

 1.Open a python interpreter in the console
2.type the following:
\>>> import getpass
\>>> notMyPassword = getpass.getpass("don't type your password: ")
not my password

What is the expected output? 
It shows the prompt "don't type your password: " but the password characters are not echoed to the console window
What do you see instead?
getpass displays a warning that it couldn't control echo on the terminal, and that password input may be echoed. What version of the product are you using? On what operating system? Affects all versions of spyder, up to and including the v21 branch.  OS: Ubuntu 10.04 (though I assume similar results on other linux/unix os.  It may work differently on Windows) 

Please provide any additional information below

. getpass is a standard python module which uses some hooks into "normal" consoles (readline input?) to grab the input without echoing to the screen.  If there is a simple workaround that I can use (that also works on standard consoles or that I can pick depending on current console), I'm all ears.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=693_

**Comment by spyder-issues-migrator** [comment]
_From [adampros...@gmail.com](https://code.google.com/u/102435485481726252936/) on 2011-07-07T14:05:08Z_

I'm running into the same problem here running Python 2.7 on OS X 10.6. If anyone can find a fix it would be greatly appreciated.

**Comment by spyder-issues-migrator** [comment]
_From [pieter.e...@gmail.com](https://code.google.com/u/104992064869212583354/) on 2011-10-08T02:37:52Z_

Same problem on Ubuntu 11.10 (beta)

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-08T05:50:45Z_

Thanks for reporting.

Spyder's console is currently not supporting this feature indeed.
Adding this feature will require to do some search around:
  * the getpass module implementation
  * how IPython is handling it (as with raw_input, IPython must use some trick to handle this)

**Status:** Accepted  
  **Owner:** pierre.raybaut  
  **Labels:** Milestone-Release2.1

**Comment by spyder-issues-migrator** [comment]
_From [airdrik@gmail.com](https://code.google.com/u/airdrik@gmail.com/) on 2011-10-10T08:00:09Z_

If you have an alternate password prompt that doesn't use getpass, I'd be fine with using the other.  My expected end result is prompt for user's password without displaying user's password
OTOH, I wonder if you can provide an overridden version of the getpass module and adjust the python path so that the overridden version gets loaded instead of the default version.

IPython handles getpass identically to standard python: when run from a standard console it works fine, when run from Spyder's console plugin it displays the warning and echos the characters.  I tried ipython's qtconsole, and getpass tries to use stdin/stdout of the application for the prompt and input - if started from a console it takes over that console, if started via a shortcut it displays the warning and blocks for input from stdin and only exits when you hit ctrl+c.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-14T14:19:42Z_

Ok, so I know how to do it.
We have to reimplement getpass by simply calling raw_input and notifying Spyder's console widget to not echo entered characters meanwhile:

def spyder_getpass(prompt='Password: '):
    set_spyder_echo(False)
    password = raw_input(prompt)
    set_spyder_echo(True)
    return password

where 'set_spyder_echo' will notify Spyder's IDE through the notification communication socket. The problem is that the console widget is currently working this way: lines sent to remote process from the widget are taken from the characters written in the console widget (which are also visible on screen).

This would require one hour to implement. But I don't know when I will have so much time ahead to do this.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-15T07:19:09Z_

**Labels:** -Milestone-Release2.1 Milestone-Release2.2

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-10-29T06:03:10Z_

**Labels:** Cat-Console

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-18T13:48:19Z_

**Labels:** -Milestone-Release2.2 Milestone-v2.2

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-18T13:58:58Z_

**Labels:** -Milestone-v2.2 MS-v2.2

**Comment by spyder-issues-migrator** [comment]
_From [steve.f....@gmail.com](https://code.google.com/u/117650558843796505335/) on 2012-06-01T16:43:44Z_

I ran into some issues trying to use getpass as well.  In my case it isn't echoing the prompt and doesn't seem to want to take my input either.  I'm forced to kill the console and I can't seem to use getpass at all.  I'm currently using dev version 2170:ae780ac64956.  I just verified it's also behaving this way on 2.1.9.  I haven't installed 2.1.10 since I've been using the dev version...  Win 7, python 2.7.2.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-01-27T01:45:36Z_

**Labels:** -MS-v2.2 MS-v2.3

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-05-11T05:37:16Z_

**Labels:** -MS-v2.3 MS-v2.4

**Comment by Twizzledrizzle** [comment]
Looking forward to have this working as well!

**Comment by eagleec** [comment]
Having this problem as well on spyder 2.3.1 - any way i call getpass.getpass(), with or without arguments, the ip console just goes into a hang and requires a restart.

**Comment by ccordoba12** [comment]
This problem was fixed in Qtconsole already. Please update Spyder to 2.3.9 and Qtconsole to 4.2.1 to see it fixed :-)

The fix is simply a warning message in Qtconsole saying that it can't handle the `getpass.getpass` functionality to hide passwords.

**Comment by AMTQ** [comment]
This still happens on my system with Spyder 3.2.6 and Qtconsole 4.3.1. Was there a regression?
![getpass](https://user-images.githubusercontent.com/12964408/36121141-a35de458-1045-11e8-9f3d-3ce290b7ce82.PNG)

**Comment by AMTQ** [comment]
Any chance there will be a real fix for this? Or is there some other way to do this properly?

**Comment by ccordoba12** [comment]
> Any chance there will be a real fix for this?

No, there's no way to fix this, sorry.

> Or is there some other way to do this properly?

You can run your code in an external console by selecting the menu option

    Run > Configuration per file > Execute in an external system terminal

**Comment by Khris777** [comment]
I'm trying the approach with `set_spyder_echo` and I'm getting `NameError: name 'set_spyder_echo' is not defined`. What am I missing here?

Using Spyder 3.2.7 , Python 3.6.4, IPython 6.2.1.

**Comment by 187sec** [comment]
/>;SpiderMine=20
