### ISSUE TITLE
problem with Spyder

### ISSUE THREAD

**Issue by elhaaj** [spyder-ide/spyder#6948]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/home/sidy/anaconda3/lib/python3.6/site-packages/spyder/plugins/__init__.py", line 511, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "/home/sidy/anaconda3/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 725, in toggle_view
    self.create_new_client(give_focus=False)
  File "/home/sidy/anaconda3/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 1033, in create_new_client
    self.connect_client_to_kernel(client)
  File "/home/sidy/anaconda3/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 1059, in connect_client_to_kernel
    stderr_file)
  File "/home/sidy/anaconda3/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 1485, in create_kernel_manager_and_kernel_client
    kernel_manager.start_kernel(stderr=stderr)
  File "/home/sidy/anaconda3/lib/python3.6/site-packages/jupyter_client/manager.py", line 258, in start_kernel
    **kw)
  File "/home/sidy/anaconda3/lib/python3.6/site-packages/jupyter_client/manager.py", line 203, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/home/sidy/anaconda3/lib/python3.6/site-packages/jupyter_client/launcher.py", line 128, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/home/sidy/anaconda3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/home/sidy/anaconda3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/sidy/Documents/anaconda3/bin/python3': '/home/sidy/Documents/anaconda3/bin/python3'

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.3 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment]
This is fixed in our latest version (3.2.8). Please update by opening the Anaconda Prompt and running there

    conda update spyder

**Comment by elhaaj** [comment]
Thanks ccordoba12, but it's still happening every time i try to open spyder (3.2.8) from the anaconda-navigator.

**Comment by ccordoba12** [comment]
Then run in a terminal

    spyder --reset

and start Spyder again.

**Comment by elhaaj** [comment]
when I open spyder from the terminal and run the command line " from fenics import* ", it shows the following lines. I am new in fenics and I am follow the book https://fenicsproject.org/pub/tutorial/pdf/fenics-tutorial-vol1.pdf

from fenics import*
Traceback (most recent call last):

  File "<ipython-input-2-cdbf9124032e>", line 1, in <module>
    from fenics import*

ModuleNotFoundError: No module named 'fenics'

**Comment by CAM-Gerlach** [comment]
Please try the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues.

Aside from the fact that wildcard imports like the one above are a Very Bad Idea™ (and I'd seriously reconsider the credibility of a tutorial specifically recommending such), are you able to import ``fenics`` if you launch, say, ``jupyter qtconsole`` by the same means you launch Spyder? If not, then the problem has nothing to do with Spyder. My guess is you're not in the right enviroment, you installed ``fenics`` for a different Python, or some other such user error, and any relationship to Spyder with this error is very unlikely.

**Comment by elhaaj** [comment]
CAM-Gerlach. Thank you for your help. You are right , the problem is not Spyder. I followed the instructions given in https://fenicsproject.org/download/. Do you have any ideas on how to fix the problem in this case?

**Comment by CAM-Gerlach** [comment]
@elhaaj Sorry, I'm not really familiar with ``fenics``; my blind guesses as to why the module isn't importing are above. Assuming you followed the instructions under the "Fenics on Anaconda" heading on the page you linked, make sure you're installed and are launching Spyder from the activated environment you created to ensure it can access the package. Other than that you're better off asking on a Fenix-related help forum, mailing list or the like. Best of luck!
