### ISSUE TITLE
ValueError: malformed node or string: <_ast.Call object at 0x000000001A5BA588>

### ISSUE THREAD

**Issue by agnesbao** [spyder-ide/spyder#7444]
## Description

**What steps will reproduce the problem?**

1. After I run this code snippet, it pops the error window:
        try:
            kwls = record['PubmedArticle'][0]['MedlineCitation']['KeywordList'][0]
            for w in kwls:
                abs_str.append(w)
        except:
            abs_str.append('')

2. Then I cannot run any code unless I restart Spyder
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\Xiaojun\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "C:\Users\Xiaojun\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 220, in _handle_execute_reply
    self.handle_exec_method(msg)
  File "C:\Users\Xiaojun\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 354, in handle_exec_method
    view = ast.literal_eval(literal)
  File "C:\Users\Xiaojun\Anaconda3\lib\ast.py", line 85, in literal_eval
    return _convert(node_or_string)
  File "C:\Users\Xiaojun\Anaconda3\lib\ast.py", line 66, in _convert
    in zip(node.keys, node.values))
  File "C:\Users\Xiaojun\Anaconda3\lib\ast.py", line 65, in <genexpr>
    return dict((_convert(k), _convert(v)) for k, v
  File "C:\Users\Xiaojun\Anaconda3\lib\ast.py", line 66, in _convert
    in zip(node.keys, node.values))
  File "C:\Users\Xiaojun\Anaconda3\lib\ast.py", line 65, in <genexpr>
    return dict((_convert(k), _convert(v)) for k, v
  File "C:\Users\Xiaojun\Anaconda3\lib\ast.py", line 84, in _convert
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: <_ast.Call object at 0x000000001A5BA588>

**Comment by dalthviz** [comment]
Hi @agnesbao this seems like a duplicate of #5636 

Please update Spyder with:
```
conda update spyder
```

**Comment by ccordoba12** [comment]
Thanks @dalthviz! Closing because this was solved a long time ago.

**Comment by Sherochen** [comment]
@ccordoba12 Hello, May I know how did you solve this problem? I am facing the same error now but cannot manage to solve it. Thanks.

**Comment by miriamkl** [comment]
@ccordoba12 Hi, unfortunately, I still have this problem, even though I updated Spyder to 3.3.2.
Is there anything else I can do?

**Comment by ccordoba12** [comment]
@miriamkl, please open a new issue and give us a simple and reproducible code that generates this problem.

**Comment by Zhongyi-89** [comment]
@mkkuemmel @ccordoba12 @Sherochen  You may want to try to use "eval" instead of "literal_eval()". 
 Or check your Object type by "type(literal)",  as <The string or node provided may only consist of the following Python literal structures: **strings, bytes, numbers, tuples, lists, dicts, sets, booleans, and None**.>
