### ISSUE TITLE
spyder crash after viewing big matrix - huge memory leak

### ISSUE THREAD

**Issue by sebg1** [spyder-ide/spyder#7793]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1.  create the variable 
import numpy as np
a = np.zeros((1400,150,90))
2. explore the numpy array a, change the slice, scroll the data then quit the explorer view
3. after somes seconds, the RAM consumption increases from 0 to several Go, until the system is fully freezed

### What is the expected output? What do you see instead?
No messages preventing large data from being displayed.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.2.8
* Python version: 3.6.5
* Qt version: 5.9.5
* PyQt version: 5.9.2
* Operating System name/version: ubuntu 18.04, RAM 32 Go

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by sebg1** [comment]
Seems fixed with spyder 3.3.1
Thks !

SÉBASTIEN GÉNETÉ
Lead Data Scientist
+33 (0)6 16 81 54 23 <+33616815423>
sgenete@insideboard.com

www.insideboard.com

Paris <https://goo.gl/maps/fnWi5pmYNpK2> • New-York
<https://goo.gl/maps/NJepncnNZST2> • San Francisco
<https://goo.gl/maps/9MHLSLHnLdP2>
[image: Logotype Insideboard] <https://www.insideboard.com/>
<https://www.linkedin.com/company/5259101/>
<https://twitter.com/insideboard_tw>
<https://www.youtube.com/channel/UCfUmKP5HlpC9hBdVglsvm9Q>
<https://www.facebook.com/M-inside-1582016848711968/>
<https://plus.google.com/u/0/104161323686518017080>


2018-08-31 11:21 GMT+02:00 Jitse Niesen <notifications@github.com>:

**Comment by guyts** [comment]
I'm using Spyder 3.3.3 but still have this issue occasionally. 
One example is with a matrix of about 250x16, with ints and floats inside. Unsure how to resolve.
