### ISSUE TITLE
"Parent poll failed" warning

### ISSUE THREAD

**Issue by emanspeaks** [spyder-ide/spyder#8205]
### What steps will reproduce the problem?

1. Start Spyder
2. Do something in the IPython console (probably not necessary)
3. Restart kernel

The resulting message is the "parent poll failed" message"

```
parentpoller.py:116: UserWarning: Parent poll failed.  If the frontend dies,
                the kernel may be left running.  Please let us know
                about your system (bitness, Python, etc.) at
                ipython-dev@scipy.org
  ipython-dev@scipy.org""")
```
                
This may be related to some of the discussion in #7842, but I seem to only see this when I restart a kernel now.

## Versions

* Spyder version: 4.0.0.dev0 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  2.0.0 (OK)
pyls >=0.19.0     :  0+unknown (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.28.5 (OK)
qtconsole >=4.2.0 :  4.4.2 (OK)
IPython >=4.0     :  7.0.1 (OK)
matplotlib >=2.0.0:  3.0.1 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by ccordoba12** [comment]
This is not something we can address in Spyder because it's an `ipykernel` and (as far as I know) it only happens in Python 3.7.

@minrk, have you seen this before?

**Comment by emanspeaks** [comment]
FWIW if I am running in debug level 3 and check the terminal, i see this in the debug terminal:
```
2018-11-08 20:11:56,828 [DEBUG] [traitlets] -> stream: {'name': 'stderr', 'text': 'C:\\miniconda\\miniconda3\\lib\\site-packages\\ipykernel\\parentpoller.py:116: UserWarning: Parent poll failed.  If the frontend dies,\n                the kernel may be left running.  Please let us know\n                about your system (bitness, Python, etc.) at\n                ipython-dev@scipy.org\n  ipython-dev@scipy.org""")\n'}
```
But I don't see that in the kernel at Spyder startup.  I'm not sure why this warning is not being printed to the GUI console the first time, but is being printed on subsequent kernel restarts.

I thought that behavior was also curious and worth noting here.

**Comment by minrk** [comment]
I haven't seen this before, but parent polling on windows uses a Windows API call, so it could be that something changed here that we need to take care of.

**Comment by ccordoba12** [comment]
@minrk, how can we help to solve this?

**Comment by minrk** [comment]
The check is implemented [here](https://github.com/ipython/ipykernel/blob/5.1.0/ipykernel/parentpoller.py#L74-L111), calling [WaitForMultipleObjects](https://docs.microsoft.com/en-us/windows/desktop/api/synchapi/nf-synchapi-waitformultipleobjects). I think we'd need some testing of the WaitForMultipleObjects behavior to see what might have changed.

I don't currently have win10 to test on.

Is this a 32b or 64b process? It's possible we've done something slightly wrong with our 32/64b check.

**Comment by minrk** [comment]
From the docs, I'm guessing we are getting the `WAIT_FAILED` result, and we should be calling `GetLastError` to get the informative error from Windows. This might point us in the right direction.

**Comment by ccordoba12** [comment]
@CAM-Gerlach or @jnsebgosselin (Spyder devs) have Windows 10 boxes, so they could you to test anything you need.

**Comment by emanspeaks** [comment]
I am also on Windows 10 64-bit

**Comment by CAM-Gerlach** [comment]
@minrk Make sure to check out #7842 for some more details from when this was originally reported. This also occurs on my Win 8.1 x64 machine running Python 3.7.0 (64-bit, ofc) and the latest Spyder ``3.x`` at the time, in both ``ipykernel`` 4.8,2 and (IIRC) 4.9.x, but not under Python 3.6.6 in an otherwise identical configuration. Let me know what you'd like me to specifically test further.

**Comment by CAM-Gerlach** [comment]
@minrk I can repro this in QtConsole on Py3.7/Win 8.1, so the problem definitely isn't with Spyder's codebase. Should I report it there and see if any of the Jupyter guys know how to fix it, or what the cause is? Is there something you'd like me to test?

**Comment by jamessong** [comment]
C:\''''\Anaconda3\envs\work\lib\site-packages\ipykernel\parentpoller.py:116: UserWarning: Parent poll failed.  If the frontend dies,
                the kernel may be left running.  Please let us know
                about your system (bitness, Python, etc.) at
                ipython-dev@scipy.org
  ipython-dev@scipy.org""")

I got the same thing

**Comment by jamessong** [comment]
I am using python 3.7 and 3.6 ... the same error

**Comment by jamessong** [comment]
One problem with spyder is that if I run from the  recently added menu (the window bar on the left under windows 10),  it will show
os.environ['PROJ_LIB']
Traceback (most recent call last):

  File "<ipython-input-2-2c7134a76458>", line 1, in <module>
    os.environ['PROJ_LIB']

  File "C:\Users\Ja\Anaconda3\envs\work\lib\os.py", line 669, in __getitem__
    raise KeyError(key) from None

KeyError: 'PROJ_LIB' 

but  if I echo in the anaconda prompt, it shows normally:

echo %PROJ_LIB%
C:\Users\Ja\Anaconda3\Library\share

**Comment by ccordoba12** [comment]
@jamessong, your problem has ***nothing** to do with what is discussed here, so please don't try to derail this issue. Besides, I told you already how to fix it: start Spyder from the Anaconda prompt. If you don't want to maintain it open, use this command: `spyder --hide-console`.

**Comment by jamessong** [comment]
It is exactly related to the original post  

    On Monday, November 26, 2018 10:02 PM, Carlos Cordoba <notifications@github.com> wrote:
 

 @jamessong, your problem has *nothing to do with what is discussed here, so please don't try to derail this issue. Besides, I told you already how to fix it: start Spyder from the Anaconda prompt. If you don't want to maintain it open, use this command: spyder --hide-console.—

**Comment by CAM-Gerlach** [comment]
> One problem with spyder is that if I run from the recently added menu (the window bar on the left under windows 10), it will show
> os.environ['PROJ_LIB']

I'm not sure how I understand how that has any to do with the original post, sorry, about the ``Parent poll failed`` message appearing on Python 3.7 when a kernel is restarted.

**Comment by tuannhtn** [comment]
I encountered the same issue. Then I downgraded mkl (2019.1->2018.0.3), upgraded matplotlib (2.2.3->3.0.1) and numpy (1.15.1->1.15.4) via conda upgrade command and the issue disappeared. Hope this helps.

**Comment by sureshd2014** [comment]
I had installed Anaconda 3, with Spyder 3.3.1 and Python 3.7.0 64 bit |Qt 5.9.6| PyQt5.5.9.2| Windows 10. and was experiencing this peoblem.
Yesterday, I upgraded to Spyder 3.3.2. 
I have been running the same scrits for last 24 hours and the Kernel has not crashed yet. Maybe, this problem has been solved.
Thanks to the teams of Pierre Raybaut and   Carlos Cordoba and the international Spyder Community. 
Proud of all of you.
- Suresh

**Comment by sureshd2014** [comment]
I had installed Anaconda 3, with Spyder 3.3.1 and Python 3.7.0 64 bit |Qt 5.9.6| PyQt5.5.9.2| Windows 10. and was experiencing this peoblem.
Yesterday, I upgraded to Spyder 3.3.2. 
I have been running the same scrits for last 24 hours and the Kernel has not crashed yet. Maybe, this problem has been solved.
Thanks to the teams of Pierre Raybaut and   Carlos Cordoba and the international Spyder Community. 
Proud of all of you.
- Suresh

**Comment by NdaAzr** [comment]
Since I did restart the kernel today, I am experiencing the same issue on Windows 10 with Python 3.7. I did upgrade to the Spyder 3.3.2, but still warning UserWarning: Parent poll failed.  If the frontend dies,                 the kernel may be left running. How can I solve this?

**Comment by CAM-Gerlach** [comment]
@NdaAzr Its just a warning, so there's nothing to really "solve" unless you see specific symptoms. It seems likely to be an issue with ``ipykernel`` or ``jupyter_client`` rather than anything with Spyder, given the warning comes from the former package. @minrk any ideas?

**Comment by NdaAzr** [comment]
@CAM-Gerlach Thank you for the reply. Even warning makes user worry. Today I was trying to do something like clear all and I did change run configuration per file to remove all variables before execution, and I got an error `AttributeError: module '__main__' has no attribute '__spec__'`  while my code will run without any error in Anaconda Prompt window. any idea?

**Comment by ccordoba12** [comment]
@NdaAzr, please update spyder-kernels to **0.3.0**. That version fixes your error.

**Comment by ccordoba12** [comment]
I think @CAM-Gerlach was clear enough, I don't know what else you want from me.

**Comment by NdaAzr** [comment]
@ccordoba12 Yes that one is solved. Thank you. 
I was just refering to the 
> Since I did restart the kernel today, I am experiencing the same issue on Windows 10 with Python 3.7. I did upgrade to the Spyder 3.3.2, but still warning UserWarning: `Parent poll failed. If the frontend dies, the kernel may be left running` How can I solve this?

**Comment by CAM-Gerlach** [comment]
And @ccordoba12 was referring to my direct response to that comment:

> @NdaAzr Its just a warning, so there's nothing to really "solve" unless you see specific symptoms. It seems likely to be an issue with ipykernel or jupyter_client rather than anything with Spyder, given the warning comes from the former package.

So no, you should not worry.

**Comment by geochemistry** [comment]
> 
> 
> @NdaAzr, please update spyder-kernels to **0.3.0**. That version fixes your error.

Hi Carlos,
I updated this module to 0.3.0, but the problem still occurred
![fig1](https://user-images.githubusercontent.com/33366392/50291527-d02b6600-04a9-11e9-9af1-972733b70cb1.jpg)

**Comment by ccordoba12** [comment]
@geochemistry, I was talking about the multiprocessing error.

**Comment by ccordoba12** [comment]
Closing because this has not been reported anymore.

**Comment by CAM-Gerlach** [comment]
> I have the same problem with jupiter notebook (anaconda)

> Does anyone know how to fix it for jupyter notebook?

This is the Spyder bug tracker, not Jupyter notebook. Please report your issue to them instead; thanks.

**Comment by Gfqwy** [comment]
![image](https://user-images.githubusercontent.com/52851180/79429645-61591100-7ffa-11ea-9ff3-d87c92136255.png)
I installed tensorflow but failed, then pop up “UserWarning: Parent poll failed.  If the frontend dies,
                the kernel may be left running.  Please let us know
                about your system (bitness, Python, etc.) at
                ipython-dev@scipy.org
  ipython-dev@scipy.org""")”

other, I could not open spyder ,reset it will pop up “python 停止工作”

how I could do ?

**Comment by CAM-Gerlach** [comment]
@Gfqwy Please read this issue you posted to. What is shown is just a warning, which is not necessarily indicative of any specific problem. Furthermore, you should upgrade to latest Spyder-Kernels version, as stated earlier. You are using ancient (years old), unsupported IPython, Spyder-Kernels, Spyder, etc. packages, so please update your entire Anaconda environment to a modern version

From your description, its very unclear what the Spyder-specific problem(s) are, if any, that your are experiencing. Please reference [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) section for some basic steps to try to fix it or at least narrow it down for us. Thanks, and best of luck!

**Comment by Gfqwy** [comment]
Thanks, I have solved this issue.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"CAM Gerlach"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月16日(星期四) 下午4:49
收件人:&nbsp;"spyder-ide/spyder"<spyder@noreply.github.com&gt;;
抄送:&nbsp;"雨越瑜时，钟子芷"<1839434513@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [spyder-ide/spyder] "Parent poll failed" warning (#8205)





 
@Gfqwy Please read this issue you posted to. What is shown is just a warning, which is not necessarily indicative of any specific problem. Furthermore, you should upgrade to latest Spyder-Kernels version, as stated earlier. You are using ancient (years old), unsupported IPython, Spyder-Kernels, Spyder, etc. packages, so please update your entire Anaconda environment to a modern version
 
From your description, its very unclear what the Spyder-specific problem(s) are, if any, that your are experiencing. Please reference Spyder Troubleshooting Guide, specifically the Basic First Aid section for some basic steps to try to fix it or at least narrow it down for us. Thanks, and best of luck!
