### ISSUE TITLE
ctrl+c in ipdb on windows

### ISSUE THREAD

**Issue by ali-r** [spyder-ide/spyder#8459]
### What steps will reproduce the problem?

I am used-to stop any thing with crtl+c but when i am in ipdb console it causes freezes so i should restart ipython console 
and it is really really annoying

maybe related to ipython bug:
https://github.com/ipython/ipython/issues/2472

i am using:
python 3.6.6
ipython 7.2.0

i tried changing ipython version

## Versions

* Spyder version: 3.3.2 
* Python version: 3.6.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  1.5.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.1.3 (OK)
sphinx >=0.6.6    :  1.5.1 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
nbconvert >=4.0   :  4.2.0 (OK)
pandas >=0.13.1   :  0.19.2 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.0 (OK)
cython >=0.21     :  0.25.2 (OK)
qtconsole >=4.2.0 :  4.2.1 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  2.2.2 (OK)
pylint >=0.25     :  1.6.4 (OK)
```

**Comment by ccordoba12** [comment]
Closing as a duplicate of #5401.

**Comment by jabowery** [comment]
Once one has made the mistake of reflexively pressing CTRL-C, is there any way to get ipdb to again respond to Enter other than stopping debugging and restarting the program from scratch?

**Comment by ccordoba12** [comment]
Please update Spyder to it's latest version (3.3.4). The problem you reported should be fixed already.

**Comment by mmagnuski** [comment]
@ccordoba12 
I am still experiencing this issue on Spyder 3.3.6 (but I am sure there was a period where it worked ok). Are there other dependencies I should update to fix the problem? Or might this be a regression?
