### ISSUE TITLE
install spyder twice

### ISSUE THREAD

**Issue by Ss-wW** [spyder-ide/spyder#8829]
## Description

**What steps will reproduce the problem?**

1. create a new tensorflow environment
2.  install spyder in the tensorflow env through anaconda navigator
3.  install spyder (again) in the terminal of tensorflow through "conda install spyder"
4. (I did the above step 3 since I forgot that I've installed a spyder for the tensorflow env. )

**What is the expected output? What do you see instead?**
I see an error prompt whenever I open the spyder(tensorflow).  The contents are as below.
And I cannot run codes like "import tensorflow as tf"

**Please provide any additional information below**

    plugin = mod.PLUGIN_CLASS(self)
AttributeError: '_ModuleMock' object has no attribute 'PLUGIN_CLASS'

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.5.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
This is fixed in our latest version (3.3.3). Please update by opening the Anaconda Prompt and running there

    conda update spyder

**Comment by Ss-wW** [comment]
I used the update code as below. However, it not working. When I open spyder(tensorflow), the problem still exits and the version of spyder is still 3.2.3.

(base) C:\Users\songwei>activate tensorflow
(tensorflow) C:\Users\songwei>conda update spyder
Collecting package metadata: done
Solving environment: done

# All requested packages already installed.

**Comment by Ss-wW** [comment]
It's not just the spyder problem. When I open the tensorflow enviroment with iPython, the following problem occurs.
![image](https://user-images.githubusercontent.com/28401896/53283022-d6c0ad00-377a-11e9-9e66-126f49eb509b.png)

**Comment by Ss-wW** [comment]
I know how to update syper. It's the problem of the mirror channel. I should use the default channel instead of the tsinghua channel.

**Comment by CAM-Gerlach** [comment]
> When I open spyder(tensorflow), the problem still exits and the version of spyder is still 3.2.3.

Either your mirror channel is incredibly out of date (3.2.3 is like a year and a half old; there have been no fewer than 12 releases since then), or something in your Tensorflow environment has Spyder, or more likely one of its dependencies, pinned at that version. You can tell if you run ``conda install spyder=3.3.3`` to get the latest version; it will either state the version is not available from your current channel or will tell you what's conflicting with it.

> I should use the default channel instead of the tsinghua channel.

They look to be up to date on Win32 and Win64, so not sure that's the problem. Of course, still I don't see the point of using them over ``defaults``, so we recommend sticking with the latter unless its blocked by the GFW or something silly like that, or there is a major difference in connection quality.
