### ISSUE TITLE
Variable explorer keeps crashing after applying make_column_transformer 

### ISSUE THREAD

**Issue by carina3** [spyder-ide/spyder#8986]
## Description
Hi guys, I'm trying out regression with sklearn (following a tutorial on Udemy). After reading in a csv file, there's one column of string inputs that I want to transform with one hot encoding. Before applying one hot encoding, the variable explorer has no problems inspecting my matrix X. However, after applying one hot encoding with the make_column_transformer command, I can no longer inspect my matrix. The variable explorer keeps crashing, and I don't know why that is.

**What steps will reproduce the problem?**

1. dataset = pd.read_csv(file), X = dataset.iloc[:, :-1]
2.  col_Transf = make_column_transformer((OneHotEncoder(categories='auto'),[3]), remainder='passthrough')
3. X = col_Transf.fit_transform(X)

**What is the expected output? What do you see instead?**
I expect the variable explorer to show something like [this](https://www.dropbox.com/s/hp53jdk5pgzs9zz/expected_output.png?dl=0). 

Instead, I get a crash notification like [this](https://www.dropbox.com/s/6xf8e88habcv3e3/received_output.png?dl=0). (full error message below)

**Please provide any additional information below**
This is the full error message I get everytime I try to explore the transformed matrix X:

  File "/usr/lib/python3/dist-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 449, in createEditor
    if not editor.setup_and_check(value, title=key, readonly=readonly):
  File "/usr/lib/python3/dist-packages/spyder/widgets/variableexplorer/arrayeditor.py", line 619, in setup_and_check
    self.data.flags.writeable = True
ValueError: cannot set WRITEABLE flag to True of this array

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.7
* Qt Versions: 5.11.1, PyQt5 5.11.2 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pygments >=2.0   :  2.3.1 (OK)
pandas >=0.13.1  :  0.24.1 (OK)
numpy >=1.7      :  1.16.2 (OK)
sphinx >=0.6.6   :  1.7.9 (OK)
rope >=0.9.4     :  0.11.0 (OK)
jedi >=0.9.0     :  0.13.1 (OK)
psutil >=0.3     :  5.4.6 (OK)
nbconvert >=4.0  :  5.4.0 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.4.2 (OK)
IPython >=4.0    :  7.1.1 (OK)
pylint >=0.25    :  2.1.1 (OK)

```

**Comment by ccordoba12** [comment]
This is fixed in our latest version (3.3.3). Please update.

**Comment by carina3** [comment]
> This is fixed in our latest version (3.3.3). Please update.

So I updated, however the problem is still there. 

  File "/home/carina/anaconda3/lib/python3.7/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 476, in createEditor
    if not editor.setup_and_check(value, title=key, readonly=readonly):
  File "/home/carina/anaconda3/lib/python3.7/site-packages/spyder/widgets/variableexplorer/arrayeditor.py", line 620, in setup_and_check
    self.data.flags.writeable = True
ValueError: cannot set WRITEABLE flag to True of this array

**Comment by ccordoba12** [comment]
Then you didn't update correctly because I can assure the problem is fixed in that version.
