### ISSUE TITLE
KeyError in PyLS when opening projects

### ISSUE THREAD

**Issue by IonutBarbu** [spyder-ide/spyder#9522]
### What steps will reproduce the problem?

The error occurred immediately after Sypder startup

### Traceback
```python-traceback
  File "C:\Continuum\miniconda3\envs\vmx_cms_model_gxmxxx_01\lib\site-packages\pyls_jsonrpc\endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "C:\Continuum\miniconda3\envs\vmx_cms_model_gxmxxx_01\lib\site-packages\pyls_jsonrpc\endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "C:\Continuum\miniconda3\envs\vmx_cms_model_gxmxxx_01\lib\site-packages\pyls_jsonrpc\dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "C:\Continuum\miniconda3\envs\vmx_cms_model_gxmxxx_01\lib\site-packages\pyls\python_ls.py", line 236, in m_text_document__did_close
    self.workspace.rm_document(textDocument['uri'])
  File "C:\Continuum\miniconda3\envs\vmx_cms_model_gxmxxx_01\lib\site-packages\pyls\workspace.py", line 74, in rm_document
    self._docs.pop(doc_uri)
```

## Versions

* Spyder version: 4.0.0b2 
* Python version: 3.6.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pygments >=2.0     :  2.4.0 (OK)
qdarkstyle >=2.6.4 :  2.6.8 (OK)
sphinx >=0.6.6     :  2.0.1 (OK)
pyls >=0.19.0;<0.25:  0.24.0 (OK)
nbconvert >=4.0    :  5.5.0 (OK)
pandas >=0.13.1    :  0.24.2 (OK)
numpy >=1.7        :  1.16.4 (OK)
sympy >=0.7.3      :  None (NOK)
cython >=0.21      :  None (NOK)
qtconsole >=4.2.0  :  4.5.1 (OK)
IPython >=4.0      :  7.5.0 (OK)
matplotlib >=2.0.0 :  None (NOK)
pylint >=0.25      :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
Thanks for reporting. Is this something that appears every time you close Spyder and open it again?

**Comment by IonutBarbuMcK** [comment]
No, it appears infrequently. It also appears when opening a new script in an already active Spyder session

**Comment by ccordoba12** [comment]
@andfoy, was this fixed in PR #9468?

**Comment by jitseniesen** [comment]
I still get this, or a very similar, error on master post PR 9468. The error dialog shows
```
  File "/home/jitse/misc/miniconda/envs/std/lib/python3.6/site-packages/pyls_jsonrpc/endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "/home/jitse/misc/miniconda/envs/std/lib/python3.6/site-packages/pyls_jsonrpc/endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "/home/jitse/misc/miniconda/envs/std/lib/python3.6/site-packages/pyls_jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/home/jitse/misc/miniconda/envs/std/lib/python3.6/site-packages/pyls/python_ls.py", line 236, in m_text_document__did_close
    self.workspace.rm_document(textDocument['uri'])
  File "/home/jitse/misc/miniconda/envs/std/lib/python3.6/site-packages/pyls/workspace.py", line 74, in rm_document
    self._docs.pop(doc_uri)
  File "/home/jitse/misc/miniconda/envs/std/lib/python3.6/site-packages/pyls_jsonrpc/endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "/home/jitse/misc/miniconda/envs/std/lib/python3.6/site-packages/pyls_jsonrpc/endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "/home/jitse/misc/miniconda/envs/std/lib/python3.6/site-packages/pyls_jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/home/jitse/misc/miniconda/envs/std/lib/python3.6/site-packages/pyls/python_ls.py", line 236, in m_text_document__did_close
    self.workspace.rm_document(textDocument['uri'])
  File "/home/jitse/misc/miniconda/envs/std/lib/python3.6/site-packages/pyls/workspace.py", line 74, in rm_document
    self._docs.pop(doc_uri)
```
Unfortunately, the error message seems to have disappeared.

This error appeared when opening a new project. It is not triggered all the time, only about half the time when opening a project.

Versions:

Spyder 4.0.0.dev0 (Commit: 15868e54a) | Python 3.6.8 64-bit | Qt 5.9.6 | PyQt5 5.9.2 | Linux 4.19.0-5-amd64
```
$ conda list python-language-server
# packages in environment at /home/jitse/misc/miniconda/envs/std:
#
# Name                    Version                   Build  Channel
python-language-server    0.24.0                   py36_0    spyder-ide

pygments >=2.0     :  2.3.1 (OK)
qdarkstyle >=2.6.4 :  2.6.4 (OK)
sphinx >=0.6.6     :  1.8.5 (OK)
psutil >=0.3       :  5.6.1 (OK)
pyls >=0.19.0;<0.25:  0.24.0 (OK)
nbconvert >=4.0    :  5.4.1 (OK)
pandas >=0.13.1    :  0.24.2 (OK)
numpy >=1.7        :  1.16.2 (OK)
sympy >=0.7.3      :  1.3 (OK)
cython >=0.21      :  0.29.6 (OK)
qtconsole >=4.2.0  :  4.4.3 (OK)
IPython >=4.0      :  7.4.0 (OK)
matplotlib >=2.0.0 :  3.0.3 (OK)
pylint >=0.25      :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
@andfoy, please take a look at this one.

**Comment by andfoy** [comment]
@IonutBarbu @jitseniesen Thanks for reporting this issue, is it possible to get a copy of the Spyder LSP client log?

**Comment by ccordoba12** [comment]
@jitseniesen, you can do that by starting Spyder with

    python bootstrap.py --debug

and then going to

    ~/.config/spyder-py3-dev/lsp_logs/client_python.log

**Comment by jitseniesen** [comment]
> Thanks for reporting this issue, is it possible to get a copy of the Spyder LSP client log?

I sent it to you by email.

**Comment by ccordoba12** [comment]
@jitseniesen, could you test again with the latest master? I think this was fixed by PR #9482 (at least I can't generate the error anymore).

**Comment by jnsebgosselin** [comment]
It seems to be fixed for me too.

**Comment by jnsebgosselin** [comment]
I do not get an error anymore  after switching project, but the codestyle analysis stop working.

**Comment by ccordoba12** [comment]
@jnsebgosselin, I can't reproduce that on Linux, but please open another issue for it (it's probably a Windows only problem).

**Comment by jitseniesen** [comment]
> could you test again with the latest master?

I can't reproduce the error anymore, so it seems to be fixed. Thanks, @andfoy!

**Comment by ccordoba12** [comment]
Thanks for the confirmation @jitseniesen and @jnsebgosselin!

**Comment by jnsebgosselin** [comment]
> 
> 
> @jnsebgosselin, I can't reproduce that on Linux, but please open another issue for it (it's probably a Windows only problem).

Ok, what can I provide as information or logs to help with this? `client_python.log` and `server_python.log`?

**Comment by ccordoba12** [comment]
Yeah, please create a gist for both of them and put its link in the description.
